### ISSUE TITLE
Complete Tree Retrieval

### ISSUE THREAD

**Issue by abhinav1602** [dowjones/react-dropdown-tree-select#100]
How can I retrieve the complete tree structure containing the selected as well as unselected nodes? Till now I only have the 'selecteNodes' array and 'clickedElement' information but I am unable to save the complete tree on submit button.

**Comment by mrchief** [comment]
`selectedNodes` **_is_** the complete list of everything's that's selected. How you use that data is up to you.

If you want to submit entire tree with its selections, there are 2 ways:

 - keep track of selections (on your end) by listening to node change events
 - leverage [tree-node-paths-hoc](https://dowjones.github.io/react-dropdown-tree-select/#/story/tree-node-paths-hoc) approach to easily find and update the selected state.

The component doesn't mutate it's inputs. 

Once initialized, it doesn't store any tree structure, nor you should not depend on its internals.

**Comment by mrchief** [comment]
Nice home page, by the way!

**Comment by abhinav1602** [comment]
@mrchief I am unable to find any working example in reference to the same. can you help me with that? 
 Apart from that, what about removing selections from the complete tree(as I'll not be having the removed element in SelectedNodes)? If I am using a library, I expect to minimize the lines of code I write and reduce the overall time for the task, but it is not the case here. Why haven't you made it a feature already(optional feature maybe)?
