### ISSUE TITLE
Is it possible to hide the search bar and just display the tree?

### ISSUE THREAD

**Issue by abhinav1602** [dowjones/react-dropdown-tree-select#104]
I don't want the tree to be displayed only after the click event is performed on the search bar. Is it possible to display only the tree by default and hide the search bar?

**Comment by mrchief** [comment]
Yes. You'd need the following setup:

 - pass `showDropdown: true`
 - hide search bar via css: `.dropdown-trigger {display: none}`

Here's a demo: 

[![Edit Static dropdown without Search Bar](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ywx2x557j9)
