### ISSUE TITLE
Search seems to only search in the first node

### ISSUE THREAD

**Issue by josvegit** [dowjones/react-dropdown-tree-select#111]
https://dowjones.github.io/react-dropdown-tree-select/#/story/large-tree

When I try, it seems to only find results from the first node. Maybe I'm doing something wrong.  Tried with my own data, had the exact same behaviour.

**Comment by josvegit** [comment]
If it is indeed an issue, I'll see if I can help, now that the GDPR hype is over I have more time..

**Comment by mrchief** [comment]
Yeah I noticed it a few times but couldn't put my finger on it. I think it may have to do with the accented characters.  We could use unicode aware regex search instead but that would mean IE 11 and below users will be out of luck. (We could use something like [regexpu](https://github.com/mathiasbynens/regexpu)) but I don't want to add bloat for obsolete browsers.

**Comment by josvegit** [comment]
Ill try by removing all occurences of åäö later today

**Comment by josvegit** [comment]
Adding support for that seems Overkill

**Comment by mrchief** [comment]
If there is fair demand I don't mind supporting unicode characters. IE bloat is something I'd like to avoid at all costs.

**Comment by zig145** [comment]
FWIW, I'm running into this issue as well, and from what I can tell I don't think it appears to be related to special characters (I don't have these characters in my data set).  It looks like search is only searching the first X # of nodes.  For example in the large-tree example, the cutoff is around node "enbacken123-eneby-d3".  If you search for anything after that you will get no results.  In my local project I see search also only getting results from roughly the first X # of nodes.

In my local project I've tried going back to 1.10.0 to test, and I do see all matches there, but of course this is before the search enhancements, so performance is too slow to be usable (I'm looking to support ~15k nodes as well).

**Comment by mrchief** [comment]
@zig145 Any chance you can share your dataset? Random/redacted values would do as long as they are representative of the tree's complexity.

**Comment by mrchief** [comment]
@zig145 I think this will do. 

> I don't ever see results after the "-0-2-0" node.

Now I know what to look for. Thanks for the tip!

**Comment by mrchief** [comment]
I found the problem. But it's not an easy one to fix. :(

**Comment by fpauer** [comment]
Still happening!

**Comment by mrchief** [comment]
@fpauer can you try the beta version and let me know?

**Comment by fpauer** [comment]
@mrchief now it is working, version `1.13.0`
