### ISSUE TITLE
Simple select with tree view structure

### ISSUE THREAD

**Issue by vikrametc** [dowjones/react-dropdown-tree-select#119]
Hi Team,

I have a need to show the dropdown option in a hierarchy form and allow only to select one of them.
I tried passing keepTreeOnSearch and simpleSelect to the component but it is not working.
Do you know if there is a way to acheive this?

**Comment by mrchief** [comment]
`simpleSelect` is the same as HTML `select`, except for autosuggest and tags. When I added that, I didn't think of a use case that combines tree and single value select. 

It should be easy to support though - it currently stops processing the tree if `simpleSelect` is true. Removing that shortcisrcuit will accomplish what you're looking for. 

Feel free to send a PR if you need this soon.

**Comment by vikrametc** [comment]
Thanks Hrusikesh for your reply.
I am not seeing any option in the dropdown itself when I passed the data with children and give simpleSelect as true.
We do have a requirement for user to see the options as tree hierarchy and allow only single select.
I do not want to mess your code with the PR, if possible could you please make required modification to incorporate the changes?

one more thing: do we need to provide data in special format for single select or data having children should work fine?

**Comment by mrchief** [comment]
> I do not want to mess your code with the PR, if possible could you please make required modification to incorporate the changes?

PRs do not mess up the code - you'll be working on your own copy of the code. If you're not familiar with them, then I encourage you to read this [guide](https://help.github.com/articles/about-pull-requests/).

I'm currently swamped with other stuff. I can make the changes but I cannot promise a timeline.

> one more thing: do we need to provide data in special format for single select or data having children should work fine?

You do not have to do anything special there. Same data will work as is. Feel free to play with the online demo or CodeSandboxes.

**Comment by matejstrasek** [comment]
Could we reopen this? Would be wonderful for our use case also.
