### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by ajiejot** [dowjones/react-dropdown-tree-select#130]
![image](https://user-images.githubusercontent.com/36364052/42210831-91ffdcc6-7ee4-11e8-938b-408ff33b99f5.png)

I got this error when I am import first on the component:
`import DropdownTreeSelect from 'react-dropdown-tree-select'`

**Comment by mrchief** [comment]
Can you share your sample repo/setup for this?
