### ISSUE TITLE
Error running tests with PhantomJS

### ISSUE THREAD

**Issue by nusudoers** [dowjones/react-dropdown-tree-select#136]
Hi All,
I am trying to use this component in order to replace an older hierarchy selector component. I am facing issue while running the tests on webpack `yarn run test-once` (which basically runs `karma start --log-level info --single-run --browsers PhantomJS`) while the test pass with Chrome browser running continuously using `yarn run test`. I installed the component using `yarn add react-dropdown-tree-select` and using a mix of default and custom styles.I have copied default styles into a scss file in our project and also import the react-dropdown-tree-select styles like this `@import '../node_modules/react-dropdown-tree-select/dist/styles.css'` in our common app.scss file which includes all the style imports. We use webpack to bundle the code and following is the error in Jenkins:
```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  {
    "message": "SyntaxError: Unexpected token 'const'\nat tests.webpack.js:140960:0",
    "str": "SyntaxError: Unexpected token 'const'\nat tests.webpack.js:140960:0"
  }
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  {
    "message": "SyntaxError: Unexpected token 'const'\nat tests.webpack.js:140960:0",
    "str": "SyntaxError: Unexpected token 'const'\nat tests.webpack.js:140960:0"
  }
```
Anyone faced this issue before while using this component? Any help/suggestions would be appreciated.

**Comment by mrchief** [comment]
It sounds like you need to setup transpilation or run it with a node js version that understands `const`.

**Comment by mrchief** [comment]
Since this is not an issue with the core component, I'm closing this for now. I'll be happy to reopen this if needed.

**Comment by nusudoers** [comment]
@mrchief Yes, this issue got resolved by moving to Headless chrome instead of using PhantomJS. Thanks.
