### ISSUE TITLE
Incorrect behavior while using showPartiallySelected property

### ISSUE THREAD

**Issue by priyanshu92** [dowjones/react-dropdown-tree-select#137]
Hi,

Thanks for this awesome component 😄 . I am using it to show multiple hierarchies on a page and the data for these hierarchies is pulled from a web API. When the data is loaded then the component is rendered. 

The problem which I am facing is when I use `showPartiallySelected` property then the root node(s) become automatically checked in the UI and I see the pill(s) for all of them. I have explicitly marked the property `checked` as `false` in the data but that doesn't help also. 

Could you please look into this issue? Let me know if you need more details.

PS: I cloned the repo and used `showPartiallySelected` in the `Large Tree` example and same thing happens. The root node is checked by default. However, it works fine in the `Default Values` example. 🤔 

Thanks,
Priyanshu

**Comment by mrchief** [comment]
It sounds like one of the child nodes is selected - that will cause the root node (and any parent nodes) to get selected. Check your data again and if it still looks like an issue, please post a codesandbox or sample repo.

**Comment by priyanshu92** [comment]
I checked but none of the child nodes is selected and even if was selected then the root will be partially checked but in my case it is displaying as completely checked. I have created a sample repo, please check [here](https://github.com/priyanshu92/react-checkbox-tree-test-app). You can start the app using `npm start` or `yarn start`.

**Comment by priyanshu92** [comment]
I think I found the problem. The component shows parent node selected if there is empty `children` array for the item. In my case (as in the sandbox above) if we remove `children: [ ]` then it is working fine otherwise the nodes become selected.

**Comment by priyanshu92** [comment]
Yep Sure. Will do. 👍
