### ISSUE TITLE
material design css not working

### ISSUE THREAD

**Issue by xporium** [dowjones/react-dropdown-tree-select#147]
hi,
i m new in react, actually  i follow your steps and install react dropdown tree select in my project.
even i also added webpack rule which mentioned.
But if i try with custom css like material or bootstrap than its not working.
if i remove rule from webpack than default css also not working
so can any one tell me which rule or configuration i have to add in webpack?

i{
            test: /\.css$/,
            use: ExtractTextPlugin.extract({
              fallback: 'style-loader',
              use: [
                {
                  loader: 'css-loader'
                }
              ]
            }),
            include: /node_modules[/\\]react-dropdown-tree-select/
          },
{
            test: /\.css$/,
            use: [
              require.resolve('style-loader'),
              {
                loader: require.resolve('css-loader'),
                options: {
                  importLoaders: 1,
                  modules:true,
                  localIdentName:'[Name]__[local]__[has:base64:5]'
                },
              },
              {
                loader: require.resolve('postcss-loader'),
                options: {
                  // Necessary for external CSS imports to work
                  // https://github.com/facebookincubator/create-react-app/issues/2677
                  ident: 'postcss',
                  plugins: () => [
                    require('postcss-flexbugs-fixes'),
                    autoprefixer({
                      browsers: [
                        '>1%',
                        'last 4 versions',
                        'Firefox ESR',
                        'not ie < 9', // React doesn't support IE8 anyway
                      ],
                      flexbox: 'no-2009',
                    }),
                  ],
                },
              },
            ],
          },

**Comment by mrchief** [comment]
I formatted your rules to better understand it and I see a subtle typo

```
{
    test: /.css$/,
    use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [{
            loader: 'css-loader'
        }]
    }),
    include: /node_modules[/\]react-dropdown-tree-select/
}, {
    test: /.css$/,
    use: [
        require.resolve('style-loader'),
        {
            loader: require.resolve('css-loader'),
            options: {
                importLoaders: 1,
                modules: true,
                localIdentName: '[Name][local][has:base64:5]'
            },
        },
        {
            loader: require.resolve('postcss-loader'),
            options: {
                // Necessary for external CSS imports to work
                // https://github.com/facebookincubator/create-react-app/issues/2677
                ident: 'postcss',
                plugins: () => [
                    require('postcss-flexbugs-fixes'),
                    autoprefixer({
                        browsers: [
                            '>1%',
                            'last 4 versions',
                            'Firefox ESR',
                            'not ie < 9', // React doesn't support IE8 anyway
                        ],
                        flexbox: 'no-2009',
                    }),
                ],
            },
        },
    ],
},
```

You're missing an extra slash in `include: /node_modules[/\]react-dropdown-tree-select/`. Should be `include: /node_modules[/\\]react-dropdown-tree-select/` (notice it's `[/\\]`). In case of regex, that extra slash matters. 

The other thing I would ask you to verify is that you're importing your custom css (the one that has material design overrides) somehwere in your code. Nothing else pops out.

If you still have issues, I'd suggest to create a sample repo that reproduces your issue and I can look further.

**Comment by mrchief** [comment]
Try importing your css after the dropdown’s css. Or increase the “specificity” of your css selectors.

**Comment by xporium** [comment]
hi,
i did (Try importing your css after the dropdown’s css) but still same problem. I think any rule i have to add in webpack config file, but if i used only 


//   test: /\.css$/,
          //   use: ExtractTextPlugin.extract({
          //     fallback: "style-loader",
          //     use: "css-loader"
          //   })
          // },

than default css not work proper


and if i add
 // {
          //   test: /\.css$/,
          //   use: ExtractTextPlugin.extract({
          //     fallback: 'style-loader',
          //     use: [
          //       {
          //         loader: 'css-loader'
          //       }
          //     ]
          //   }),
          //   include: /node_modules[/\\]react-dropdown-tree-select/
          // },

than default work but custom css not work...

**Comment by mrchief** [comment]
Can you create a github repo with all the files/code?

**Comment by xporium** [comment]
hi,
sorry actually i cant create github repo for this. but please see below code. but i can provide u specific file.

1)Multiselect.JS

import React from 'react';
import DropdownTreeSelect from 'react-dropdown-tree-select'
import 'react-dropdown-tree-select/dist/styles.css'
import classes from   './Multiselect.css';

const Multiselect = ( props ) => {
    return (        
        <DropdownTreeSelect placeholderText="Search" data={props.data} onChange={props.changed}  className={classes.multiselect}/>        
    );
};
export default Multiselect;

2) Index.js
let multiselect = null;
        if ( this.props.industrydata  !== null) {
            multiselect = <MultiSelect data={this.props.industrydata} changed={this.onmultiselectchange}/>
        }        
        return (
            <div className={classes.Auth}>
           
                    {multiselect}
                                

            </div>

if add below rule in webpack than default react dropdown tree select css working ok.
But in  if i want to add custom css like className={classes.multiselect} than its not working.
So tell me rule that default css and custom css work for "react dropdown tree select"

{
            test: /\.css$/,
            use: ExtractTextPlugin.extract({
              fallback: 'style-loader',
              use: [
                {
                  loader: 'css-loader'
                }
              ]
            }),
            include: /node_modules[/\\]react-dropdown-tree-select/
          },

{
            test: /\.css$/,
            use: [
              require.resolve('style-loader'),
              {
                loader: require.resolve('css-loader'),
                options: {
                  importLoaders: 1,
                  modules:true,
                  localIdentName:'[Name]__[local]__[has:base64:5]'
                },
              },
              {
                loader: require.resolve('postcss-loader'),
                options: {
                  // Necessary for external CSS imports to work
                  // https://github.com/facebookincubator/create-react-app/issues/2677
                  ident: 'postcss',
                  plugins: () => [
                    require('postcss-flexbugs-fixes'),
                    autoprefixer({
                      browsers: [
                        '>1%',
                        'last 4 versions',
                        'Firefox ESR',
                        'not ie < 9', // React doesn't support IE8 anyway
                      ],
                      flexbox: 'no-2009',
                    }),
                  ],
                },
              },
            ],
          },

**Comment by mrchief** [comment]
Took the liberty of formatting the code blocks in your post.

Your code looks fine. I don't know what's not working. Simply stating "it's not working" is not very helpful. That's a very vague thing.

Take a look at this branch: https://github.com/dowjones/react-dropdown-tree-select/tree/b7fe7bc77e1a7734bebb36b8de9b8e7aa443f1cc/docs/examples/material

And in your 2nd webpack rule, try excluding `node_modules`

```
{
            test: /\.css$/,
            use: ExtractTextPlugin.extract({
              fallback: 'style-loader',
              use: [
                {
                  loader: 'css-loader'
                }
              ]
            }),
            include: /node_modules[/\\]react-dropdown-tree-select/         // <--keep this as is
          },

{
            test: /\.css$/,
            exclude: /node_modules/           // <-- new condition to exclude css coming from node_modules
            ...
```

**Comment by xporium** [comment]
Hi, 

test: /\.css$/,
            exclude: /node_modules/  <-- new condition to exclude css coming from node_modules
            ...

that also included in webpack.
my main concern is all working fine without webpack. but if i suppose to run eject command in application so webpack would generated automatically. I had add  below rule for default css.

{
            test: /\.css$/,
            use: ExtractTextPlugin.extract({
              fallback: 'style-loader',
              use: [
                {
                  loader: 'css-loader'
                }
              ]
            }),
            include: /node_modules[/\\]react-dropdown-tree-select/   <--keep this as is
          },

now i want custom css, in that case add one css file and import that file to js file
and than add className={classses.multiselect} its not affect by custom css, its render like default dropdown.

**Comment by mrchief** [comment]
I believe this question has been answered. Happy to reopen this if you find any issues.
