### ISSUE TITLE
Configuring which level of child nodes can be selectable

### ISSUE THREAD

**Issue by ahmoha** [dowjones/react-dropdown-tree-select#150]
Hi, 

Is there a way we can specify which level the tree is selectable from? 
For Eg, if I have a tree P1->P2-C1->P3-C2->C4

Is there any props or data attribute that can be used to define that this tree can be selectable from level 3 only? i.e., P3-C2 onwards?

Thanks
Omair

**Comment by mrchief** [comment]
You can set `disabled: true` on the nodes you want to disable. Now disabling parents will disable its children, but you can override that by explicitly setting `disabled: false` on child nodes.

**Comment by priyamtrivedi9199** [comment]
Hi i did have a look at your solution but i found it quite abstract could you share me a sandbox or a code snippet showcasing exactly what needs to be done.
I am looking for the same feature but my requirement is that if the length of selected nodes reach an specific number the remaining nodes get disabled . the nodes should be visible but a user should not be able to select it.

**Comment by mrchief** [comment]
>  if the length of selected nodes reach an specific number the remaining nodes get disabled . the nodes should be visible but a user should not be able to select it.

You would need to massage the dat in that case. What you want is some sort of logic that walks the `data` object and

```
if(child.depth > MAX)
  child.disabled = true
```
