### ISSUE TITLE
can follow default structure is i want to apply some changes in react dropdown tree select?

### ISSUE THREAD

**Issue by xporium** [dowjones/react-dropdown-tree-select#159]
Hi,

mentioned below from "dowjones/react-dropdown-tree-select read me" 
means if i want to changes some css or change from scratch than i have to follow same structure and naming? is that ok what i understood?

I do not want the default styles, do I need to fork the project?
Absolutely not! Simply do not import the styles (webpack) or include it in your html (link tags). Roughly, this is the HTML/CSS skeleton rendered by the component:

div.react-dropdown-tree-select
  div.dropdown
    a.dropdown-trigger
      span
    ul.tag-list
      li.tag-item
        input
    div.dropdown-content
      ul.root
        li.node.tree
          i.toggle.collapsed
          label
            input.checkbox-item
              span.node-label
Write your own styles from scratch or copy existing styles and tweak them. Then include your own custom styles in your project.

**Comment by mrchief** [comment]
I believe this question has been answered. Closing this as it is not an issue. Happy to answer any further questions.
