### ISSUE TITLE
No event passed in onFocus and onBlur

### ISSUE THREAD

**Issue by JankiAmrutia** [dowjones/react-dropdown-tree-select#176]
I am trying to do event.stopPropogation in onFocus and onBlur but there is no event for these actions. 

Can you please explain why?

**Comment by mrchief** [comment]
These are simulated events as we really don't have a native control. Also, these were kind of experimental (I was debugging some issue with redux-forms). 

What use-case are you looking for?

**Comment by JankiAmrutia** [comment]
I wanted to check if i can use the event to stop outside click but i figured out this is not related to outside click of dropdown. Hence closing the issue. Thank you.
