### ISSUE TITLE
Scroll bar in the drop down does not appear

### ISSUE THREAD

**Issue by nreact** [dowjones/react-dropdown-tree-select#179]
In some of the examples provided, the scroll bar is present in the drop down, How ever in the sandbox examples I couldn't see the scroll bar, I am using the default css , how do I get the scroll bar working.
Thanks in advance

**Comment by mrchief** [comment]
Some of the sandboxes use a smaller dataset, which may not overflow. The idea was to make it easy for someone new to grasp the code. 

If there's a particular sandbox that you feel has an issue, please link it here and I can take a look.

**Comment by nreact** [comment]
This issues is with my data which is quite a big tree.. Is there any option in drop down that needs to set . or some kind of css tweaking that I have to do

**Comment by mrchief** [comment]
I would see if something is suppressing overflow in those divs. There is no special logic for scroll - just overflow-y. 

If you can provide a codesandbox to repro this, I can look deeper.

**Comment by nreact** [comment]
Ok, I will try to see if I am doing any thing weird with div and css ..thanks for response

**Comment by nreact** [comment]
Thanks for looking into issue, I fixed it by adding css property to scroll component

**Comment by nreact** [comment]
Re opening this ..issue ..
The way I fixed the issue is by below
.infinite-scroll-component  {
    height:300px !important;
}
As the infinite-scroll component uses inline style
<div class="infinite-scroll-component" style="height: auto; overflow: auto;">

Can this issue be fixed , so that we don't have to use !important to force it ?

**Comment by mrchief** [comment]
You can open a issue in infinite-scroll-component repo. That style is not mine.

**Comment by nreact** [comment]
okay thanks !
