### ISSUE TITLE
Selecting all nodes with same name renders duplicate tags in textbox

### ISSUE THREAD

**Issue by BaarishRain** [dowjones/react-dropdown-tree-select#185]
When there are multiple nodes with the same name, on selection of two or more of these nodes, duplicate tags appear in the box. Is there any way we can customize the component so that only unique tags appear?

**Comment by mrchief** [comment]
I checked this by creating some nodes with same label/value in my sample data and the component works as expected. Selecting one node doesn't select the other. 

However, if you have 2 or more identical names, when selected, it'll look as if duplicate tags are appearing. This is not bug, just a mere data oddity. Each tag represents a selected node. How do you suggest we handle removing/hiding a tag while the node is selected? 

I'm not sure how to answer this without knowing your use case, its requirements and constraints. I can suggest to tweak your data so that names have some kind of distinction.

**Comment by BaarishRain** [comment]
I am trying to create a tree where node label/value can be duplicate. My requirement is when I select a node which has duplicates then all nodes across the tree with the same label/value should be selected as well.

 I could tweak this in onChange and send updated tree as data. But I am unable to control the tags that appear in the text box. Though I am trying to update the

**Comment by BaarishRain** [comment]
I am trying to create a tree where multiple nodes exist with same label/value. My requirement is, when I select a node then all nodes across the tree with the same label/value should be selected as well.

I could tweak this in onChange and send updated tree using prop data. But I am unable to control the tags that appear in the text box. I tried to update the state of tags using setState, but no luck.

**Comment by mrchief** [comment]
Hmm, I see. It seems like you have a special case. I think one way you can achieve your goal is by using same CSS class for the duplicate nodes and hiding them via CSS. Something like:

```
.dupNode {
  display: none;
}

.dupNode:first-of-type {
  display: block;
}
```

**Comment by BaarishRain** [comment]
We have multiple nodes in our tree and assigning each node a className to resolve this might not be a good workaround. Also, our tree is dynamic. Hence, adding css definition for every new node is cumbersome.

Is it possible to tweak the component to allow for a prop to remove duplicate tags?

**Comment by mrchief** [comment]
Not easily. Your is a special case - you want the nodes to act as a special select-all-identical and then the tags to be deselect-all-identical buttons. To do so, we'd need to build that logic in the component and expose it via options or extend the component to take custom renderers that can do their own special handling. Both would be adding to the complexity of the component for something that seems like a one-off requirement. 

If you have any ideas on how to do so without sacrificing the simplicity or performance needs, I'd be open to hear them.

**Comment by manjkul** [comment]
when displaying the tags is there a way in which we can allow the parent node name to be displayed as well along with the selected node?

**Comment by mrchief** [comment]
@manjkul There isn't at the moment. Also, please open a new issue for a new question. Do not hijack existing threads.
