### ISSUE TITLE
Full tree gets drawn after selecting a node in search mode

### ISSUE THREAD

**Issue by JKapostins** [dowjones/react-dropdown-tree-select#190]
**Description**
After selecting a node while in search mode, the entire tree gets drawn.

**To Reproduce**
Use the following props, search for a node in the tree, and select it. Note that if you clearSearchOnChange you won't be able to see the issue.

```html
<DropdownTreeSelect
    showPartiallySelected={true}
    keepTreeOnSearch={true}
    clearSearchOnChange={false}
    data={this.props.treeData}
/>
```

**Expected behavior**
The demo behaves as expected, the tree structure does not change when nodes are selected.

**Screenshots**
![bug](https://user-images.githubusercontent.com/7006862/47611682-65792380-da40-11e8-8187-176a063aefb1.gif)

**Environment**
 - Browser Chrome Version 69.0.3497.100 (Official Build) (64-bit) and Microsoft Edge 42.17134.1.0
 - OS: Windows 10 x64
 - react-dropdown-tree-select@1.13.0

**Comment by mrchief** [comment]
@JKapostins That dropdown looks pretty cool! 

Thanks for reporting this and creating that wonderful gif. It helps tremendously in understanding your problem.

From what I gather, I think you're referring to the **lost** scroll position, correct?

**Comment by JKapostins** [comment]
@mrchief thanks! You are correct the scroll position does go to the top of the tree, but notice the entire tree gets drawn after i select a node. When i type in "sales" notice there is only two nodes under the "Job Functions" parent ("Outside Sales" and "Sales"). After i select the "sales" node, all of the nodes under "Job Functions" that do not contain "sales" in the name become visible even though "sales" is still in the search box.

**Comment by mrchief** [comment]
Ah, I see. I knew something else was happening but couldn't put my finger on it. 

I think I've an idea where to start looking. Let me take a deep dive and I'll let you know. 

As always, if you'd like to send a fix, I can help you with some pointers; so let me know.

**Comment by JKapostins** [comment]
Thanks @mrchief I haven't had time to dive in myself. Were you able to repro this?

**Comment by mrchief** [comment]
Yeah, I can repro this in the basic demo as well.

**Comment by mrchief** [comment]
I found the root cause and working on a fix. It's taking a bit longer because I don't want to monkey patch things. Stay tuned!

**Comment by JKapostins** [comment]
Thanks @mrchief looking forward to your updates!

**Comment by mrchief** [comment]
After going through several possible solutions, I settled for one that is least intrusive. It also turns out to be the solution that requires the least amount of code change. :) 

Try `v1.13.1-beta.1` or do `yarn add react-dropdown-tree-select@next` and let me know if it works for you.

**Comment by JKapostins** [comment]
@mrchief I just tested v1.13.1-beta.1 and i'm still getting the issue. I triple checked that I got your changes. I see them in the react-dropdown-tree-select.js.map that is distributed with the package. I blew away all my cached data and did a clean build but still get same result as before.

**Comment by JKapostins** [comment]
@mrchief disregard my previous comment. After studying your change I realized the issue is now caused by how i'm maintaining the state of the tree in redux. I'll need to re-think how i'm handling things on my end. Thanks for all your hard work!

**Comment by mrchief** [comment]
Hah! I just created a [sandbox](https://codesandbox.io/s/yvk0j1v2yx) to test and was about to post the updated gif here!

Let me know if there's anything I can do to help alleviate your issue. If all else looks good, I'll publish this soon.

**Comment by JKapostins** [comment]
Yep everything is looking great. Thanks again!
