### ISSUE TITLE
Error occured -  [Safari] Unexpected keyword 'const'. Const declarations are not supported in strict mode

### ISSUE THREAD

**Issue by abhishekvishwakarmagate6** [dowjones/react-dropdown-tree-select#199]
This error occured in dist/react-dropdown-tree-select.js under node_modules,if u find  "const n=e.filter(t)",due to this line the issue occured and site got blank and not working on ipad(chrome/safari).
Please help me regarding this as the site is not working on ipad

**Comment by mrchief** [comment]
@abhishekvishwakarmagate6 That's a limitation of older iOS Safari browser [caniuse.com/#feat=const](https://caniuse.com/#feat=const).

![image](https://user-images.githubusercontent.com/781818/50410986-8d7bcd80-07ca-11e9-8d88-d5f660826ce3.png)

Can you run the dist files through your own build step to produce ES5 code? I would also suggest to try and get off older browsers if possible or get rid of strict mode but I've got a feeling those aren't easy objectives to achieve.

**Comment by ellinge** [comment]
Probably fixed by #267 now

**Comment by davidrenne** [comment]
Wow, cool two people reported it.  @ellinge, even though const might feel dirty, its like the one line of code which somehow transpiles back to const out of millions of lines of javascript we might have in our application.  @mrchief thanks for a fix.  Ill try it out today and im sure it will fix the safari version.
