### ISSUE TITLE
Is it possible to set the selectedNodes programmatically

### ISSUE THREAD

**Issue by pablopareja** [dowjones/react-dropdown-tree-select#2]
Hi,

I am searching for a way to programmatically set the nodes that are selected in the tree without requiring user interaction, is it possible at all?

Thanks in advance!

Pablo

**Comment by mrchief** [comment]
You mean _after_ you've initialized the tree? If so, then you can do that by setting the props again (passing `checked: true` for selected nodes).

Once initialized, the tree maintains its internal state based on the passed in props.

**Comment by pablopareja** [comment]
Cool thanks, great component by the way!

**Comment by abhinav1602** [comment]
Can you post here the code for same?

**Comment by abhinav1602** [comment]
How can I edit the original tree and save the selections(along with the complete tree)?

**Comment by Arjav97** [comment]
How can I set the selected nodes based on the list view where all the selected nodes are rendered and it has delete(cross-icon) button how can we set the updated nodes in the list view to reflect upon the tree???
