### ISSUE TITLE
DropDownTree selection can be broken when using multiple instances on the same component

### ISSUE THREAD

**Issue by elias551** [dowjones/react-dropdown-tree-select#208]
**Describe the bug**
When using two or more DropDownTree components in the same page, sometimes clicks for selecting a dropdown do not unselect the previously selected dropdown.

**To Reproduce**
https://codesandbox.io/s/j2z20j56rw

1. click on the first dropdown
2. select an element
3. click on the second dropdown

Result: Both dropdowns are open

**Expected behavior**

There should only be only one dropdown selected or opened at a time

**Screenshots**

![image](https://user-images.githubusercontent.com/1853013/53357143-79209200-392d-11e9-95d4-b0fd452cd0b9.png)

**Environment (please complete the following information):**
Reproducible on any browser

**Additional context**
It seems like the function `utils/isOutsideClick` can detect if the dropdowns are different only if the `className` property is different, maybe an additional generated key by component instance could fix this method.

**Comment by mrchief** [comment]
> It seems like the function `utils/isOutsideClick` can detect if the dropdowns are different only if the `className` property is different, maybe an additional generated key by component instance could fix this method.

Yes, you can actually pass your own unique classname to each instance via props.
