### ISSUE TITLE
TypeScript bindings

### ISSUE THREAD

**Issue by statico** [dowjones/react-dropdown-tree-select#209]
This is a great library. However, it would be even better if it included TypeScript bindings, or at least third-party bindings via https://github.com/DefinitelyTyped/DefinitelyTyped .

For now I've created a `types/react-dropdown-tree-select.d.ts` file which contains the following:

```typescript
declare module 'react-dropdown-tree-select' {
  export default class DropdownTreeSelect extends React.Component<any, any> {}
}
```

**Comment by mrchief** [comment]
I've thought about this and IMO (and I think you'd agree) that having `React.Component<any, any> {}` is as good as not having any typing. It's a good first step though.

I'd be open for a PR on this if someone wants to do it with the proper types.

**Comment by mrchief** [comment]
@allcontributors[bot] please add @statico for ideas

**Comment by ellinge** [comment]
What about actually converting it to TypeScript instead? Can easily start of by the root/entry and convert / add typings as you move along.
