### ISSUE TITLE
uglifyjs-webpack-plugin is not giving error of this project

### ISSUE THREAD

**Issue by brijesh-p9** [dowjones/react-dropdown-tree-select#228]
For optiomization in our application, we are using [uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) to reduce the file size. 

I am facing issue while building the application.
![Screenshot 2019-03-29 at 1 44 04 PM](https://user-images.githubusercontent.com/45349639/55218680-c8a5f680-5228-11e9-9ba5-a7f64d2b963a.png)

Would you please try to uglify and check the code? If required, we can use any other application.

**Comment by mrchief** [comment]
`dist` already contains uglified/minified code. You'd need to exclude it from your uglification. In general, uglifying node modules is not a good idea.

**Comment by ellinge** [comment]
Probably fixed by #267 now without exclusion now
