### ISSUE TITLE
clear input method.

### ISSUE THREAD

**Issue by gakeko2018** [dowjones/react-dropdown-tree-select#236]
Hi 
is there a way to clear all selected and clear the input.
thanks

**Comment by ellinge** [comment]
You have a sample here https://github.com/dowjones/react-dropdown-tree-select/blob/develop/docs/HOC.md#external-select-all-unselect-all-buttons

**Comment by gakeko2018** [comment]
Thanks a lot.

**Comment by ellinge** [comment]
This a better sample for you I guess: https://codesandbox.io/s/rjwqq86p1n
