### ISSUE TITLE
making this element a single select instead of multi-select?

### ISSUE THREAD

**Issue by baradhili** [dowjones/react-dropdown-tree-select#237]
I'd like to be able to make the tree-select a single select component instead of multi-select. ie. the first selection is the only value it handles.. is this possible?

**Comment by ellinge** [comment]
You can use [simpleSelect](https://github.com/dowjones/react-dropdown-tree-select#simpleselect)
It does however not support any hierarchy/children.

#217 is on it's way which allows hierarchy but only single select as well. If you don't like the radio buttons they can be hidden by css. You can view the different types in the link available in the PR:s description. Unfortunately don't have any estimated time of release.

**Comment by baradhili** [comment]
I'll watch #217 then :)

Sent from my phone 

-----Original Message-----

**Comment by ecamaj** [comment]
I need this too...

**Comment by mrchief** [comment]
This issue has been resolved in version [1.18.0](https://www.npmjs.com/package/react-dropdown-tree-select)
