### ISSUE TITLE
pre-loading data into component

### ISSUE THREAD

**Issue by baradhili** [dowjones/react-dropdown-tree-select#238]
If I'm using this to edit existing data, is it possible to preload the field? I'm probably being blind here.. but I can't find anything along those lines

**Comment by ellinge** [comment]
You can set **checked** or **isDefaultValue** on the node data passed to the component.
See https://github.com/dowjones/react-dropdown-tree-select#data

The difference between the two is that isDefaultValue will be restored if all values are cleared.
You can see the different behaviours here:
https://ellinge.github.io/react-dropdown-tree-select-test/

**Comment by baradhili** [comment]
Where do I find the source for these?

**Comment by ellinge** [comment]
If you mean the ellinge.github.io page the source is here:
https://github.com/ellinge/react-dropdown-tree-select-test

You can however find samples here:
https://github.com/ellinge/react-dropdown-tree-select/tree/develop/docs/src/stories

Which is hosted here: https://dowjones.github.io/react-dropdown-tree-select/
