### ISSUE TITLE
disable dropdown onClick search box

### ISSUE THREAD

**Issue by moonjy1993** [dowjones/react-dropdown-tree-select#239]
Hello,

Is there way to force dropdown content open? or like any disable when onClick of search box so that I can force the dropdown always expanded? if not, do you have any plan to implement such props? 

Thank you very much for reading this.

**Comment by mrchief** [comment]
You can probably use [`showDropdown`](https://github.com/dowjones/react-dropdown-tree-select#showdropdown) to accomplish this.

**Comment by moonjy1993** [comment]
unfortunately, `showDropdown` is only to intialiaze the state of dropdown. 
I am looking for a props that always keeps dropdown expanded.

**Comment by mrchief** [comment]
@moonjy1993 I was thinking more like using `showDropdown` and hiding the dropdown toggle with CSS. But even with that, any outside click will close it. 

So, unfortunately, the answer to your question is no. 

Implementing this change seems [simple](https://github.com/dowjones/react-dropdown-tree-select/blob/develop/src/index.js#L102) though. Something like this should do the trick, I think:

```
const showDropdown = this.props.showDropdownAlways || this.keepDropdownActive || !prevState.showDropdown
```

I can get to it sometime but if you want this soon, feel free to send me a PR.

**Comment by moonjy1993** [comment]
@mrchief  Hi, thank you for your response!
I will create a PR soon.

**Comment by mrchief** [comment]
@moonjy1993 Great! Will look forward to it.

Got few things in my mind as I think about this:

 - would it be better to disable register the outsideClick handler for showDropdownAlways? 
 - Maybe we can bundle this new prop and `showDropdown` into a single one (not in this PR but the bundle props one - `showDropdown: initial|always`)
 - Or we can accept mixed values - true/false for current behavior and "always" for new behavior. This feels like a hack though and I'm not convinced if this is a good pattern (even though JavaScript will let us get away with it).

Thoughts? 

/cc @ellinge @Gregcop1

**Comment by moonjy1993** [comment]
@mrchief 

- would it be better to disable register the outsideClick handler for showDropdownAlways?
 Yes. I guess that makes. I will also include that logic in PR.
   
- Maybe we can bundle this new prop and showDropdown into a single one (not in this PR but the bundle props one - showDropdown: initial|always)

- Or we can accept mixed values - true/false for current behavior and "always" for new behavior. This feels like a hack though and I'm not convinced if this is a good pattern (even though JavaScript will let us get away with it).

This is something you guys(author) can decide, but I will be fine with either way. 
But this might confuse the current/future users, I think. showDropdown is for setting initialState, and showDropdownAlways is forcing the state..? 
I dunno...

**Comment by moonjy1993** [comment]
@mrchief  hi! 
I have created PR according to what we've discussed..not sure if you'll be able to review it and merge it soon? 

Thank you vm!
