### ISSUE TITLE
Separate Search and Selected Elements 

### ISSUE THREAD

**Issue by asos-dominickiaune** [dowjones/react-dropdown-tree-select#243]
Would it be possible to separate Search field from the selected elements (tags)?
At the moment search acts as a tag of selection and gets rendered at the end. This complicates everything when I'm trying to add style to everything. 

If Search field and Selection would be in separate divs it would allow not only style both, but separate or even hide elements on selection.

**Comment by asos-dominickiaune** [comment]
This would be amazing:

```return (
      <Fragment>
        <div className={cx('search-bar')}>
          <input
            type="text"
            disabled={disabled}
            ref={inputRef}
            className={cx('search')}
            placeholder={placeholderText}
            onChange={this.handleInputChange}
            onFocus={onFocus}
            onBlur={onBlur}
            readOnly={readOnly}
          />
        </div>
        <ul className={cx('tag-list')}>{getTags(tags, onTagRemove, readOnly, disabled)}</ul>
      </Fragment>

**Comment by mrchief** [comment]
`input` is always the last element and has it's own class `search`. As such, it's easy to target with the straight class selector or  `:last-child` or `:nth-last-child` or `:nth-last-of-type` pseudo-selectors. 

The general idea is that you'd style your tags and override the last one to reset/undo those styles if needed. This is the same technique input uses: https://github.com/dowjones/react-dropdown-tree-select/blob/develop/src/input/index.css#L12-L23

Can you create a CodeSandbox highlighting your problem?

**Comment by asos-dominickiaune** [comment]
So how would you wrap all the tags in one box with a nice little border around and keep search bellow it?

**Comment by ellinge** [comment]
We have thought about the search box being in top of the dropdown content (the expanded) instead. A prop to decide where the search is rendered could be an option?

**Comment by mrchief** [comment]
> So how would you wrap all the tags in one box with a nice little border around and keep search bellow it?

That doesn't sound like a traditional pills list design. But I know designers can come up with crazy ideas. 😉 

> We have thought about the search box being in top of the dropdown content (the expanded) instead. We hade some difficulties styling our instance, separting them would have made it easier

> A prop to decide where the search is rendered could be an option?

There's only so much a prop or an option can do. What if someone wants the search box in the middle? Or out of the container? Or something else? Another example would be styling with material design. There is an example which implements "one-of-the-many" material design implementations but if you look at Google's newer designs, one would need a few more divs around every checkbox/label to make it work.

To support every such scenario, the most flexible option would be to accept a renderer as a prop which would allow folks to decide their own layout. (The component doesn't have this ability as of now. I had thought about initially but decided to hold off on adding more complexity until it was actually needed.)

All event handling, decision making happens at the top level and most of the child components are just in charge of rendering data (this is not 100% accurate but bear with me). So this enables us to move towards a plug-n-play architecture. The renderer prop would have to define an API which any custom renderer would need to adhere to. If you think about it, `input`, `checkbox`, `taglist` ***are** the default renderers. Ensuring ARIA, Keyboard etc. would be up to the caller in this case.

We can start with accepting search/pill list as a custom renderer and expand it to other elements if the need arises. 

Let me know if this is something worth pursuing.

**Comment by ioterateam** [comment]
@asos-dominickiaune 
> So how would you wrap all the tags in one box with a nice little border around and keep search bellow it?

I somehow able to separate style between _search box_ and _selected tag box_ with :


> `input` is always the last element and has it's own class `search`. As such, it's easy to target with the straight class selector or `:last-child` or `:nth-last-child` or `:nth-last-of-type` pseudo-selectors.

As you can see here
![image](https://user-images.githubusercontent.com/29442149/57119871-9d6a7600-6d97-11e9-99cd-da34936c5070.png)
My _selected tag box_ have `min-width=0%` while my _search box_ has `min-width=90%`

Here my `.css `code 

```
.tag-item {
  min-width: 0%;
  display: inline-block;
  margin: 4px;
}

.tag-item:last-child {
  min-width: 90%;
  margin-right: 4px;
}

```
