### ISSUE TITLE
Select the parent doesn't mean to select all children inside

### ISSUE THREAD

**Issue by ioterateam** [dowjones/react-dropdown-tree-select#244]
**Is your feature request related to a problem? Please describe.**
I want to give an authentication to some role.

Super Admin can access :
- Asia
  - Singapore
  - Indonesia
    - Jakarta
    - West Java
    - East Java

Technician Singapore can only access :
- Asia
  - Singapore

Technician Indonesia can only access :
- Asia
  - Indonesia
    - East Java

**Describe the solution you'd like**
I like to use this _react-dropdown-tree-select_ as my solution, if i can select parent without automatically select all children inside. I was thought by using props `simpleSelect={true}` would be a solution to my case, but it's not.

**Comment by ellinge** [comment]
There's an undocumented property (in the readme) Hierarchical which avoids checking children.
You can try it here:
https://dowjones.github.io/react-dropdown-tree-select/#/story/options

**Comment by ioterateam** [comment]
Yeah i just finally figure it out about that **hierarchical** props after i try it on _local service_ , thanks btw @ellinge fyi.
I just didn't know why it's not work on [codesandbox](https://codesandbox.io/s/2p9oppwzk0).

**Comment by mrchief** [comment]
> There's an undocumented property (in the readme)

That seems like an oversight. Created #245.

> I just didn't know why it's not work on codesandbox.

I checked the sandbox and the version of the control there is older. If you update the dependency to v1.17.0 or higher, you can see it working.
