### ISSUE TITLE
Custom Style for paddingLeft based on _depth

### ISSUE THREAD

**Issue by ioterateam** [dowjones/react-dropdown-tree-select#249]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when trying to **customize** the style on item drop down. I currently want to _re-style_ the padding inside, but it looks like the padding was set **programmatically** instead using **class (style)**.
The code that I mentioned is in [here](https://github.com/dowjones/react-dropdown-tree-select/commit/d7604e7b28d0f3ba3b69e2f69112f146c925dee8?diff=split#diff-58ff2104ff4b5eeefca620c3a913058a) on line _88_

**Describe the solution you'd like**
Is it able to send probs or anything to set **_20_** to become a **variable**? 
Maybe something like this :

> before

```
const style = keepTreeOnSearch || !searchModeOn ? { paddingLeft: `${(_depth || 0) * 20}px` } : {}
```

> after

```
const style = keepTreeOnSearch || !searchModeOn ? { paddingLeft: `${(_depth || 0) * this.props.custom}px` } : {}
```

Can someone help me with this? Or there is already solution to customize styling this? Because I can't find any solution right now

**Comment by mrchief** [comment]
It's currently not possible to customize this. Padding is how it creates the "tree" or "hierarchy" effect so it's an essential part of it. That and the fact that it's the only solution (unless you're talking about generating CSS classes on the fly which is just plain horrible).

I wanted to avoid too many props from the get-go but if having that solves your problem, then I'll gladly accept a PR on this.

**Comment by ioterateam** [comment]
> it's an essential part of it. 

Yes yes yes, I'm agree with you!


> That` and the fact that it's the only solution (unless you're talking about generating CSS classes on the fly which is just plain horrible).

I also know that make it from CSS classes is horrible solution, so that's why I ask about having props so users can configure it out by themselves.


> I wanted to avoid too many props from the get-go but if having that solves your problem, then I'll gladly accept a PR on this.

Yes please, I really need it tho, and somehow I think it's gonna be useful in the future

**Comment by ellinge** [comment]
As a workaround until any render override or similar is available you should be able to style it with the help of aria-level:
```css
.customlevelstyle {
  .node[aria-level='2'] {
    padding-left: 30px !important;
  }
  .node[aria-level='3'] {
    padding-left: 60px !important;
  }
  .node[aria-level='4'] {
    padding-left: 90px !important;
  }
  .node[aria-level='5'] {
    padding-left: 120px !important;
  }
}

Can see it in work here https://ellinge.github.io/react-dropdown-tree-select-test/#DevelopTemp-customlevelstyle

Tried with a combination of calc() and attr() to avoid specify each level but unfortunately did not work.
