### ISSUE TITLE
Option to change pageSize

### ISSUE THREAD

**Issue by jenovs** [dowjones/react-dropdown-tree-select#257]
**Is your feature request related to a problem? Please describe.**
I have a use case with a list of ~250 elements and the pageSize of 100 causes jarring when selecting an item from the end of the list.

**Describe the solution you'd like**
Ability to set custom `pageSize` value.

**Comment by mrchief** [comment]
@jenovs Will it be possible for you to create a codesandbox or a sample repo?

**Comment by jenovs** [comment]
https://codesandbox.io/s/falling-field-zhvdl
Scroll to the end and try to select something.
With `pageSize` >= element count (e.g. 250) everything is fine.

There is another bug (not related), but I'm not sure if it's not caused by me: if you search for something, then select the result using arrow keys/enter, that element will stay always focused, i.e. if you scroll that selected element out of the view and select another element, that previous element is scrolled back into view. And then if you try to navigate via keys you'll get and error in console.

**Comment by mrchief** [comment]
Thanks for the sandbox. I tried scrolling up and down a few times using the mouse wheel and I didn't notice any jarring. Here's a video: https://drive.google.com/file/d/1TjBQEWXDVaYEEpiHUP_qE6kKzJomDcfh/view?usp=sharing

Regarding the other bug, it does sound like a separate issue and could be related to recent changes that enable keyboard navigation. Do you mind opening a separate issue for that, preferably with a reproducible example (CodeSandbox or sample git repo should do)?

**Comment by ellinge** [comment]
Cannot reproduce the error in console but #259 should fix the scrolling issue (should only be triggered by keyboard nav by changing current focus now)

**Comment by jenovs** [comment]
Jarring is when you select an element closer to the end of the list: https://drive.google.com/file/d/1-1A56ne0PA3x8Dpz5Cbp-MczZnn88n2p/view

**Comment by ellinge** [comment]
I've seen it before also. It happens in Firefox and not in Chrome. 
In Edge it scrolls all the way to the top in your example. Not sure if that's related though.

**Comment by jenovs** [comment]
Well, the video is from Chrome. I checked in Firefox and there clicking on an item around the end jumps to the middle and stays there.

I already figured out that setting `pageSize` to 250 helps
https://github.com/dowjones/react-dropdown-tree-select/blob/1f24344f3f284810a31d3e9cac8c8ac5711708e7/src/tree/index.js#L36
The problem is that it's not accessible as a prop.

**Comment by ellinge** [comment]
Perhaps fixing it for Firefox (worse result) will solve it for Chrome as well.
Can be the infinite scroll-component used which does it or some rerendering which caused the scroll to change. Changing the pageSize is just a dirty fix, it does not solve the actual issue.

**Comment by jenovs** [comment]
Agree, but for my use case infinite scroll is really not needed and setting pageSize to >= element count basically disables it :slightly_smiling_face:

**Comment by mrchief** [comment]
There's a reason for not exposing the prop and as @ellinge mentioned, it's a band-aid, not a real solution. The video is not loading for me at the moment (loader keeps spinning forever) so I'll check later.

Infinite scroll (the technique, not critiquing the component) is a necessary evil for ensuring good DOM performance. 100 seemed like a well-balanced number after profiling several page sizes but I always knew, it's not going to be an ideal match for every use case.

On the other hand, rendering it optionally changes the DOM structure which then introduces additional burden on those using custom styles. 

Other than exposing `pageSize` as a prop, I'd love to hear ideas on finding a good solution for this.

**Comment by jenovs** [comment]
Looks like initializing `currentPage` to `1` in `constructor` and removing it from here
https://github.com/dowjones/react-dropdown-tree-select/blob/a21bd119702c3e86fee83bff320ebc5649c7d340/src/tree/index.js#L72
solves the issue for me both in Chrome and Firefox.

I guess because I'm recreating data array on each change with updated values the component rerenders together with infinite scroll component.

Thoughts?

**Comment by ellinge** [comment]
![bild](https://user-images.githubusercontent.com/17863113/58288940-4fa0c680-7db5-11e9-88d3-65e9982e572c.png)
Confirmed it works

**Comment by mrchief** [comment]
What works? Initializing `currentPage` to 1?

**Comment by ellinge** [comment]
Moving https://github.com/dowjones/react-dropdown-tree-select/blob/5ec2fdc2823c341db0ca84a6d7a10b531e5b0a5b/src/tree/index.js#L74
to here
https://github.com/dowjones/react-dropdown-tree-select/blob/5ec2fdc2823c341db0ca84a6d7a10b531e5b0a5b/src/tree/index.js#L41

When receiving new props (when checking values) the currentPage field is reset. I guess this causes the scrollHeight to change just for a moment causing the scroll position to change.

I’ve also added the same ”only if active descendant changes”/only keyboard nav for recalculating the current page for the next item.
