### ISSUE TITLE
Select tree permanently outside choose box (not pop out arrow)

### ISSUE THREAD

**Issue by Michael-Hayes-01** [dowjones/react-dropdown-tree-select#26]
Hi
I'd like some help to understand why my choose box isn't behaving as expected please.
I'm using the bootstrap demo and the select tree is working fine but there is no arrow (or inverted arrow) for the choose box and the select tree values do not populate the choose box.
In short the choose box has no functionality.
![slect_drop_tree](https://user-images.githubusercontent.com/13921967/32699593-26c76fa0-c7b0-11e7-867c-9b1565ea8f06.PNG)
Thanks

**Comment by mrchief** [comment]
It seems like you're not importing the default styles. Based on your needs, you need to one of these:

 - Import base styles (the control will do it for you but you'll need to allow it via your webpack configuration like below) and then provide the necessary overrides through your app css. 

```js
{
  module: {
    rules: [
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [{
            loader: 'css-loader'
          }]
        }),
        include: /node_modules[/\\]react-dropdown-tree-select/
      }
   ]
}
```
 - Ignore base styles completely and provide your own - see [FAQ](https://github.com/dowjones/react-dropdown-tree-select#i-do-not-want-the-default-styles-do-i-need-to-fork-the-project)

**Comment by mrchief** [comment]
@Michael-Hayes-01 Is your issue resolved?

**Comment by mrchief** [comment]
Closing this for lack of any further concerns. If you're still facing concerns, feel free to comment.
