### ISSUE TITLE
Development error

### ISSUE THREAD

**Issue by LeleCao** [dowjones/react-dropdown-tree-select#260]
node  v8.16.0
npm 6.9.0
yarn 1.16.0 

git clone 
yarn init 
yarn run demo   ..error

`yarn run v1.16.0
$ rimraf ./docs/bundle.js && webpack-serve --content ./docs --port 3000 --open --config docs/webpack.config.js
ℹ ｢hot｣: webpack: Compiling...
ℹ ｢hot｣: WebSocket Server Listening at localhost:8081
ℹ ｢serve｣: Project is running at http://localhost:35119
ℹ ｢wdm｣: wait until bundle finished: 
ℹ ｢wdm｣: wait until bundle finished: /bundle.js
ℹ ｢hot｣: webpack: Compiling Done
✖ ｢wdm｣: Hash: cccbe8d4b03f435f3926
Version: webpack 4.31.0
Time: 14825ms
Built at: 2019-05-24 12:50:10
    Asset     Size  Chunks             Chunk Names
bundle.js  4.4 MiB    main  [emitted]  main
Entrypoint main = bundle.js
[1] multi webpack-hot-client/client?5dadcaa1-992c-4d20-992f-7664c61b7780 ./docs/src 40 bytes {main} [built]
[./docs/src/App.js] 2.22 KiB {main} [built]
[./docs/src/CodeSandbox.js] 579 bytes {main} [built]
[./docs/src/index.css] 1.2 KiB {main} [built]
[./docs/src/index.js] 191 bytes {main} [built]
[./docs/src/stories/BigData/index.js] 954 bytes {main} [built]
[./docs/src/stories/DefaultValues/index.js] 1.05 KiB {main} [built]
[./docs/src/stories/HOCReadme.js] 2.45 KiB {main} [built]
[./docs/src/stories/Options/index.js] 6.71 KiB {main} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[./node_modules/react/index.js] 190 bytes {main} [built]
[./node_modules/webpack-hot-client/client/hot.js] (webpack)-hot-client/client/hot.js 4.91 KiB {main} [built]
[./node_modules/webpack-hot-client/client/index.js?5dadcaa1-992c-4d20-992f-7664c61b7780] (webpack)-hot-client/client?5dadcaa1-992c-4d20-992f-7664c61b7780 2.47 KiB {main} [built]
[./node_modules/webpack-hot-client/client/log.js] (webpack)-hot-client/client/log.js 2.4 KiB {main} [built]
[./node_modules/webpack-hot-client/client/socket.js] (webpack)-hot-client/client/socket.js 1.39 KiB {main} [built]
    + 165 hidden modules

ERROR in ./docs/src/stories/DefaultValues/index.js
Module not found: Error: Can't resolve '../../../../dist/styles.css' in '/home/udesk/Desktop/react-dropdown-tree-select/docs/src/stories/DefaultValues'
 @ ./docs/src/stories/DefaultValues/index.js 4:0-37
 @ ./docs/src/App.js
 @ ./docs/src/index.js
 @ multi ./docs/src
ℹ ｢wdm｣: Failed to compile.
ℹ ｢hot｣: WebSocket Client Connected
ℹ ｢hot｣: WebSocket Client Connected
^C
ℹ ｢serve｣: Process Ended via SIGINT  `

**Comment by LeleCao** [comment]
I am a novice，Please help me.

**Comment by ellinge** [comment]
You have to do a build first to output the missing dist/styles.css file unfortunentely.
Then you can run the demo.

**Comment by LeleCao** [comment]
Thank you very much.　happy..happy

**Comment by LeleCao** [comment]
node v8.16.0
npm 6.9.0
yarn 1.16.0

git clone
yarn init
yarn run build
yarn run demo
