### ISSUE TITLE
Customize rendering using render props or component props

### ISSUE THREAD

**Issue by Sureiya** [dowjones/react-dropdown-tree-select#261]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to provide a better overall integration with [@material-ui](https://material-ui.com/) or any other UI component library.

**Describe the solution you'd like**
I'd like to be be able to pass as props to DropDownTreeSelect either the sub-components used to render the labels, inputs, and checkboxes, or render props so I can customize the rendering completely.

**Describe alternatives you've considered**
Just using plain CSS, but I'm trying to keep UX architecture simple, and the rest of my app is using theming.

**Additional context**

Currently working on a PR to this effect.

**Comment by mrchief** [comment]
@Sureiya Take a look at #162. It attempted using custom renderers but docs and tests were lacking. The code is slightly outdated now but may help.
