### ISSUE TITLE
feature: Support for ReadOnly tags

### ISSUE THREAD

**Issue by dpkm95** [dowjones/react-dropdown-tree-select#262]
**Is your feature request related to a problem? Please describe.**
We have support for readOnly dropdown which is great, I need similar feature but for few tags in the dropdown.

Although, I can hide the 'x' button using tagClassName for readOnly concepts, checkmark in dropdown can't be controlled by css. Hence, I wish there was support for readOnly at tag level in data.

**Comment by mrchief** [comment]
@dpkm95 Help me understand - what effect are you looking for? Few tags are readonly but rest are not? What's the use case?
