### ISSUE TITLE
Menu reopening after select issue

### ISSUE THREAD

**Issue by silveur** [dowjones/react-dropdown-tree-select#268]
Issue is that the menu keeps focus after I select an element and the next click on the page will reopen the menu which is definitely a bug to me.
I feel like it only happens when there are no children elements (simple select) and is easily reproducible on the 'Simple Select' demo on your site.

**Comment by ellinge** [comment]
Which version do you use?

Do you use showDropdow='initial'? I think it may be related to the same line which caused #265 

Can you specify the steps to reproduce it on the demo site.

**Comment by ellinge** [comment]
Ok I can confirm it's reproducable on https://dowjones.github.io/react-dropdown-tree-select/#/story/simple-select
That version is 1.6.0 though. Could not reproduce on https://dowjones.github.io/react-dropdown-tree-select/#/story/options which uses the latest version.

**Comment by ellinge** [comment]
Here is an updated demo which uses the latest version:
https://codesandbox.io/s/simple-select-using-react-dropdown-tree-select-mrlyg?fontsize=14

**Comment by silveur** [comment]
Oh yeah thanks @ellinge  I've updated to latest and it seems fixed now.

**Comment by mrchief** [comment]
I've updated the [CodeSandbox](dowjones.github.io/react-dropdown-tree-select/#/story/simple-select) to use the latest version as well.
