### ISSUE TITLE
Clearing/ deselecting all checked boxes

### ISSUE THREAD

**Issue by m2jobe** [dowjones/react-dropdown-tree-select#27]
Is it possible to clear / deselect the check boxes?

**Comment by Charlie91** [comment]
@m2jobe 
i also faced with this problem. in sum, i had created my own component and inserted it in DOM by ReactDOM.render function.
something like that:
`        let dropdown = document.getElementsByClassName('dropdown-content')[0];

        let div  = document.createElement('div');
        div.classList.add('button_container');
        dropdown.insertBefore(div,dropdown.children[1]);

        ReactDOM.render(
            <Buttons
                checkAll={this.checkAllOptions.bind(this)}
                clearAll={this.clearAllOptions.bind(this)}
            />,
            document.getElementsByClassName('button_container')[0]
        );`

**Comment by mrchief** [comment]
@m2jobe I assume you're asking about doing it programmatically? If so, you need to set the data with parent node's `checked` property set to `false`. This will re-render the tree with all child/descendant nodes unchecked.

When you explicitly set a parent's checked property, it overrides child's checked property. If the parent property is not set, child's `checked` property determines its check state.

E.g.

```
const data = [{"label":"VP Accounting", "checked":true, "children":[...]}]

<DropdownTreeSelect data={data}  />
```

[![Edit n348v2qox0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n348v2qox0)

**Comment by mrchief** [comment]
@m2jobe @Charlie91 Can this issue be closed? Or do you have any further questions/inputs?

**Comment by nithyasri123vns** [comment]
> @m2jobe @Charlie91 Can this issue be closed? Or do you have any further questions/inputs?

i am trying to implement functionality where user can select only 5 child values per parrent in drop down. when user checks 6th value i am showing pop up. But once done with pop up i am trying to uncheck the checkbox using checked=false. But its not working .

Here is my code

public onChange = (currentNode, selectedOpt) => {
        try {
            var a = currentNode
            if (a.grandparent == "Brand") {
                if (a.checked == true && (Brandcollection.length < 5)) {
                    Brandcollection.push(a.value)
                    console.log(Brandcollection, "while pushing checked Brandcollection")
                }
                
                //max 5 only
               else if ((a.checked != false)) {
                    Swal.fire({
                        title: 'You can select only 5',
                        icon: 'error',
                        position: 'top'
                    });
                    a.checked = false
                }
}


But Using this i can uncheck box only once. if again user select the same value, he can see pop up but checkbox is not unchecked? why? please suggest

**Comment by mrchief** [comment]
@nithyasri123vns please open a new thread under "Discussions". Please avoid re-using closed issues.
