### ISSUE TITLE
searchPredicate not effecting search results

### ISSUE THREAD

**Issue by fatihsenel** [dowjones/react-dropdown-tree-select#273]
**Describe the bug**
searchPredicate function not effecting searching.

**To Reproduce**
Set searchPredicate function which is mentioned at documents

**Expected behavior**
Search a node without case sensitive and find that node

**Screenshots**

**Environment (please complete the following information):**
 - Browser [e.g. chrome v60.12.0, safari 10.1]
 - OS: [e.g. iOS, Windows x64] (if applicable)
 - node version (if applicable)
 - yarn or npm version (if applicable)

**Additional context**

**Comment by ellinge** [comment]
#270 is unfortunentely not released yet even if the documentation tells you so

**Comment by mrchief** [comment]
@ellinge is correct. I was waiting on #272 but if this is needed urgently, I can release it before we finish #272.

**Comment by mrchief** [comment]
This is now available in [v2.1.0](https://www.npmjs.com/package/react-dropdown-tree-select/v/2.1.0)
