### ISSUE TITLE
Add custom name for label and value

### ISSUE THREAD

**Issue by SergeyWebDeveloper** [dowjones/react-dropdown-tree-select#276]
Hello!
Is it possible to add the ability to set a custom name for the label and the value from the props?

**Comment by mrchief** [comment]
@SergeyWebDeveloper Not sure I follow. All the label/value props are passed in as part of `data`. What are you looking to customize?

**Comment by SergeyWebDeveloper** [comment]
From the back-end, I receive data that is different in properties that the package needs. as a result, it is not very convenient to customize fields such as label and value. It is much more convenient to specify the keys through the props and already your package will render.
I would also very much like you to add the possibility of replacing your components with your own ones, for example, <Option />

**Comment by mrchief** [comment]
>  It is much more convenient to specify the keys through the props and already your package will render.

Isn't this the same level of effort whether you do it through `data` prop or some other `xyz` prop? Can you show me an example? Maybe a Codesandbox?

> I would also very much like you to add the possibility of replacing your components with your own ones, for example,

There has been discussion around this in the past and if you look at some old issues, you'll find some old PRs that were work in progress. If you'd like to contribute on this, I'd gladly accept a PR!
