### ISSUE TITLE
Search doesn't work with upper-case

### ISSUE THREAD

**Issue by Charlie91** [dowjones/react-dropdown-tree-select#28]
You can see this even in the example.
https://dowjones.github.io/react-dropdown-tree-select/
If you type in on search field something in uppercase the field will write "No matches found".
I think it is not supposed to be that way

**Comment by mrchief** [comment]
Actually search _is_ case sensitive. But I can see how one might want it to be case insensitive. Maybe an option to make it case insensitive? I might be able to get to it later this week or I would love to have a PR on this.

**Comment by Charlie91** [comment]
No, check this gif 
http://dropmefiles.com/GFb2T 
For example, if i have an option like "RSVP" and "RSVP" is typed in search - it isn't appear in results.
It only appears if i typed "rsvp" in lowercase

**Comment by mrchief** [comment]
Ahh, that seems like a bug. I'll check this and get back to you. Thanks for the GIF!

**Comment by mrchief** [comment]
If you want to take a shot at a PR, please feel free. The offending lines are: [here](https://github.com/dowjones/react-dropdown-tree-select/blob/master/src/tree-manager/index.js#L37) and [here](https://github.com/dowjones/react-dropdown-tree-select/blob/master/src/tree-manager/index.js#L43)

**Comment by mrchief** [comment]
Try with v1.0.4. Should be fixed now.
