### ISSUE TITLE
Values are reset when the window changes

### ISSUE THREAD

**Issue by SergeyWebDeveloper** [dowjones/react-dropdown-tree-select#280]
If you select multiple values (or one), and resize the window, the values are reset.
This occurs in the componentWillReceiveProps in the DropdownTreeSelect class. Is this how it should work?
Thanks!

**Comment by mrchief** [comment]
No, it's not. This seems like a bug.

**Comment by mrchief** [comment]
Reproducible in demo pages.

**Comment by ellinge** [comment]
It's only reproducable within react-story.
Opening https://codesandbox.io/s/select-all-unselect-all-with-react-dropdown-tree-select-cfqei (2.1) works just fine with window resizing. React-story probably rerender the component on resize, a.k.a resets the state.

**Comment by ellinge** [comment]
```
react-story@^0.0.10:
  version "0.0.10"
...
  dependencies:
...
    javascript-detect-element-resize "^0.5.3"
```
Probably the use of this library

**Comment by mrchief** [comment]
@ellinge Good catch. Now that you mentioned it, I remember seeing this before. This was another reason I wanted to build a more pure docs site (Storybook also suffers from the same).

**Comment by ellinge** [comment]
The latest react-story (1.4.7) works better but causes a lot of design changes:
![image](https://user-images.githubusercontent.com/17863113/61830331-26f78480-ae6b-11e9-8e33-3c2b6e09f630.png)

Has not happened a lot with the library since then.

**Comment by mrchief** [comment]
About that, last time I checked it was a WIP and according to its author, even though v1 was released, it was not meant to be used. The recommended upgrade path was to use react-static but react-static was in its nascency at that time.

**Comment by mrchief** [comment]
AFAIK, react-story is no longer being actively developed or maintained. react-static was the way to go.

**Comment by mrchief** [comment]
If you're going to put the effort, I'd suggest doing #222 might be a better idea.

**Comment by ellinge** [comment]
Just tried the easy path to ensure it was the culprit.

**Comment by SergeyWebDeveloper** [comment]
@ellinge You are absolutely right. Apparently the problem lies in the indicated dependency.

**Comment by asaadawey** [comment]
i got the same error , even when my state changes the value dissapper

**Comment by Anubiso** [comment]
Second that, if the component re-renders because of a state change around the component it loses its state.

**Comment by mrchief** [comment]
> Second that, if the component re-renders because of a state change around the component it loses its state.

This is how React works. You may want to use [prevent-re-render-on-parent-render-hoc](https://dowjones.github.io/react-dropdown-tree-select/#/story/prevent-re-render-on-parent-render-hoc) to prevent that. 

This bug seems similar in it's effect but your issue is caused by how React's state and rendering work in general. Unless I'm missing details... I'd suggest opening a new issue with a CodeSandbox if that's the case.
