### ISSUE TITLE
Shift Click to show popout  

### ISSUE THREAD

**Issue by joseph-vedadi** [dowjones/react-dropdown-tree-select#281]
How I am supposed to check if user clicked or Shift Clicked .. 
what are the list of actions .. (click, shift click .... )
what are keyboard shortcuts ?
I want to how a popout for the user to show more info of the item . 

Thanks..

**Comment by mrchief** [comment]
There's no event for shift-click. You can find the list of events (e.g. [onChange](https://github.com/dowjones/react-dropdown-tree-select#onchange), [keyboard navigation](https://github.com/dowjones/react-dropdown-tree-select#keyboard-navigation) can be found in the documentation.

> I want to how a popout for the user to show more info of the item .

Assuming you meant how to show a popout, you can use `actions` (see details [here](https://github.com/dowjones/react-dropdown-tree-select#data). You can see an example Code Sandbox here: [Custom Actions with React Dropdown Tree Select](https://codesandbox.io/s/5vy246kzlk)
