### ISSUE TITLE
Two clicks are required to close the dropbox if showDropdown='initial'

### ISSUE THREAD

**Issue by mhoichman** [dowjones/react-dropdown-tree-select#282]
If showDropdown='initial', two clicks are required on the "arrow" to close the dropbox.

Also (probably related) - if showDropdown='initial' and select mode is multiple (i.e. not simpleSelect):
the dropbox does not close on blur even if some items had been already selected. One must click first in the input field or on the arrow - only then 'on blur' works.

**Comment by mrchief** [comment]
> If showDropdown='initial', two clicks are required on the "arrow" to close the dropbox.

Confirmed. This does seem like a bug. I can't think of any good reason to keep this; @ellinge thoughts?

> Also (probably related) - if showDropdown='initial' and select mode is multiple (i.e. not simpleSelect)...

When `mode` is not `simpleSelect` or `radioSelect`, the dropdown will stay open to allow multiple selections. This is by design. 

> ...One must click first in the input field or on the arrow - only then 'on blur' works.
I think fixing the `initial` bug should alleviate this.

**Comment by mhoichman** [comment]
> When mode is not simpleSelect or radioSelect, the dropdown will stay open to allow multiple selections. This is by design.

Of course! But I think "on blur" should still work, i.e. clicking outside of the dropbox should close it. And indeed it works, but weirdly enough it requires first to click inside of the search box or on the arrow.

**Comment by ellinge** [comment]
https://github.com/dowjones/react-dropdown-tree-select/blob/a84ec743e801ec77cce27dd8d32aa4b0f995f634/src/index.js#L119

The event listener is only added on clicks and on a state change (of show dropdown). It needs to be registered on initNewProps if props is initial.

**Comment by mrchief** [comment]
> But I think "on blur" should still work

For `onBlur` to happen, the input or dropdown needs to get focus first. Maybe we can force that when the component initializes but it feels like a slippery slope.

**Comment by mhoichman** [comment]
> For onBlur to happen, the input or dropdown needs to get focus first. Maybe we can force that when the component initializes but it feels like a slippery slope.

BTW, trying to find a workaround I attempted to set focus in componentDidMount on the input. But it did not help. The only way that worked for me was with two 'clicks':

```
export default class DropdownTreeSelectContainer extends Component {
    // ...

    componentDidMount() {
        if (this.props.showDropdown === 'initial') {
            // for some reason the clicks must be wrapped in a timeout,
            // otherwise the following scenario does not work properly:
            // 1. DropdownTreeSelect is inside of a modal dialog.
            // 2. This modal dialog is opened by a menu.
            // Result: the menu stays open.
            setTimeout(() => {
                let input = ReactDOM.findDOMNode(this).querySelector("input")
                input.click()
                input.click()
            }, 100)
        }
    }

    render() {
        return <DropdownTreeSelect {...this.props} />
    }
}
```

**Comment by mrchief** [comment]
Can you try doing it here (and without the `setTimeout`)? https://github.com/dowjones/react-dropdown-tree-select/blob/a84ec743e801ec77cce27dd8d32aa4b0f995f634/src/index.js#L78

Also, I'd suggest testing it outside of any other components. If it works outside as per expectations then you know the other component is causing issues.
