### ISSUE TITLE
Max number of nodes at the root level

### ISSUE THREAD

**Issue by WeiXiao2016** [dowjones/react-dropdown-tree-select#285]
I would like to use this component to display a tree of all countries, their states/provinces, and cities.

At the top level, there are 122 countries (passed to the component as the array of 122 elements). However, it seems only the first 100 countries are displayed. I am wonder if there is the max number of nodes allowed? If so, can I customize the max value?

**Comment by mrchief** [comment]
It displays the top 100 and then loads the rest as you scroll. There is no max limit on the nodes.
