### ISSUE TITLE
Search problem : Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Nabi1** [dowjones/react-dropdown-tree-select#288]
I'm facing an issue concerning the search input.

I get an `Uncaught TypeError: Cannot read property 'toLowerCase' of undefined` when I start typing in input search.

![image](https://user-images.githubusercontent.com/33934059/64192368-ce100880-ce7a-11e9-8069-d9499ba691dc.png)

It seems `e.label` is undefined but the tree is shaped as follow : 

`   tree: {
        label: 'All values'
        value: 'All values',
        children: [{
          label: 'value_level_1',
          value: 'value_level_1',
            children: [{
              label: 'value_level_2',
              value: 'value_level_2',
            }],
        }]),
      }
`
Any idea about what is causing this issue ?

**Comment by mrchief** [comment]
Data structure looks OK. Can you create a reproducible sample using Codesandbox?

**Comment by Nabi1** [comment]
Problem solved

I was building a reproducible sample using Codesanbox then I found out that key `value` (which is required) was missing in one of numerous children. 

Thanks @mrchief
