### ISSUE TITLE
How to limit displayed tags to one line

### ISSUE THREAD

**Issue by AndreasEK** [dowjones/react-dropdown-tree-select#289]
**Is your feature request related to a problem? Please describe.**
With many nodes selected, the component can get really big.

**Describe the solution you'd like**
It'd be nice to restict the display to a single line. The selected nodes can either scroll out to the left, or there's some "+x" for all of them, that are not shown.

**Describe alternatives you've considered**
I tried to achieve the scrolling solution with css on my own, but failed to do so.

**Additional context**

**Comment by AndreasEK** [comment]
![image](https://user-images.githubusercontent.com/1392994/64351474-a9429f00-cffa-11e9-8210-06cc6c29d2a2.png)

**Comment by mrchief** [comment]
Scrollbars are generally a frowned upon experience. E.g., see this:

*horz scrollbar on tag list*
![kZnyOBPFll](https://user-images.githubusercontent.com/781818/64388608-95ecff00-d00d-11e9-9d72-3fcf353b90ed.gif)

*horz scrollbar on tag list container*
![pSfPHyu42F](https://user-images.githubusercontent.com/781818/64388733-fed47700-d00d-11e9-8546-19f0236b6d50.gif)

The dropdown adjusts to container's width, so the items will wrap. That lets you scroll vertically if you override the max height on `.react-dropdown-tree-select .dropdown .dropdown-trigger` like this (I've set it to `32px`):

![hMEalkLZrM](https://user-images.githubusercontent.com/781818/64388881-8de18f00-d00e-11e9-9984-4341e9231f87.gif)

Another suggestion would be to lower the font sizes or use an ellipsis for truncating text:

![image](https://user-images.githubusercontent.com/781818/64389659-92f40d80-d011-11e9-875d-8ad75a0f530c.png)

Anything beyond this would probably need restructuring the HTML. I would prefer to keep things backward compatible but I'm open to hearing other ideas.

**Comment by bjonen** [comment]
I have raised the same issue on [stackoverflow](https://stackoverflow.com/questions/65036707/react-dropdown-tree-component-use-ellipsis-to-prevent-line-break). It would be a great feature to have a similar visual as [here](https://codesandbox.io/s/v638kx67w7?file=/index.js:1219-1231). It is nice to have the selection count and overall ellipsis in case the selections to do not fit into one line. 

In case you prefer not to make such additions to the library itself: Do you see a (potentially hacky) way to overload the HTML by the user of the library?

**Comment by mrchief** [comment]
> In case you prefer not to make such additions to the library itself: Do you see a (potentially hacky) way to overload the HTML by the user of the library?

So the initial hope was that we'd have finished the hooks version of it by now so that hacks wouldn't be needed in the first place. That's taking longer due to lack of time. 

What ideas do you have?

**Comment by bjonen** [comment]
Optimally I would like to have a comma separated text (instead of tags) which expands to a fixed number of pixels after which the text is abbreviated with ellipsis. Nice to have would be to have the total number of selected end nodes in parenthesis. 

I played around with it a bit: 
1) Replace tags in favor of plain text ({label})
```
const getTags = (tags = [], onDelete, readOnly, disabled, labelRemove) =>
tags.map(tag => {
    const { _id, label, tagClassName, dataset, tagLabel } = tag
    return (
      <li
        className={['tag-item', tagClassName].filter(Boolean).join(' ')}
        key={`tag-item-${_id}`}
        {...getDataset(dataset)}
      >
        {label}
      </li>
    )
  })
```
2) Adding CSS to several classes to prevent text from scrolling
```
  max-width: 400px;
  width: 400px;
  display: inline-block;
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
```
This implementation is not working correctly (yet) because when you open the dropdown for a second time the box is scrolled to the right (empty text) instead of maintaining the position to the left. Not sure how to overcome this but I guess it could work. 

![Dec-06-2020 13-51-42](https://user-images.githubusercontent.com/832380/101280575-378f6d00-37ca-11eb-8888-3c05ff025cd2.gif)

**Comment by mrchief** [comment]
Nice! I guess we can have a prop called `renderers` which can be the bag for custom renderers. 

```
renderers {
  tagList,
  ...others in future
}
```

This would allow for a stop gap solution while hooks comes around.
