### ISSUE TITLE
Replace character for removing a tag and expanding/closing the tree with actual icons

### ISSUE THREAD

**Issue by AndreasEK** [dowjones/react-dropdown-tree-select#290]
**Is your feature request related to a problem? Please describe.**
the button to remove a tag has 'x' as it's content
the css class to expand / collapse the tree also uses an unicode character

**Describe the solution you'd like**
Offer the possibility to use actual icons instead of characters. for example:

close: https://fontawesome.com/icons/times-circle?style=regular
expand: https://fontawesome.com/icons/chevron-down?style=solid
collapse: https://fontawesome.com/icons/chevron-up?style=solid

**Describe alternatives you've considered**

**Additional context**

**Comment by AndreasEK** [comment]
In case you're wondering, it can be done like this:

```

  span.tag button.tag-remove {
    visibility: hidden;
  }

  span.tag button.tag-remove::after {
    visibility: visible;
    content: '\f00d';
    font-family:'FontAwesome';
    color: #212f4d;
  }

  .react-dropdown-tree-select .dropdown .dropdown-trigger.arrow.bottom:after {
    content: '\f078';
    font-family:'FontAwesome';
    color: #212f4d;
  }

  .react-dropdown-tree-select .dropdown .dropdown-trigger.arrow.top:after {
    content: '\f077';
    font-family:'FontAwesome';
    color: #212f4d;
  }
```

**Comment by mrchief** [comment]
Yep. This is the same technique used in Bootstrap/Material UI styles demos.
