### ISSUE TITLE
Is it possible to render a custom node?

### ISSUE THREAD

**Issue by Ptolol** [dowjones/react-dropdown-tree-select#293]
Hi, I'd like to render a custom node with own svg icons(from svg components that I already use in my app) and switch places of checkbox and icon.

Is it possible to do that, e.g. passing `renderNode` function to the dropdown?

**Comment by mrchief** [comment]
Not at the moment. There has been discussions in the past around this but as of today, there is no custom rendering.

**Comment by Ptolol** [comment]
ok, I've forked the project and modified some components

**Comment by blerner** [comment]
Could you say a bit more about the discussion or any future plans for this?  At a very very quick glance, it seems that replacing [the `i` tag](https://github.com/dowjones/react-dropdown-tree-select/blob/f90e9f84e0226d9364ec7ab13b3fc3bab3c50d17/src/tree-node/toggle.js#L31), [the `Checkbox` call](https://github.com/dowjones/react-dropdown-tree-select/blob/f90e9f84e0226d9364ec7ab13b3fc3bab3c50d17/src/tree-node/node-label.js#L60) and [the `button` call](https://github.com/dowjones/react-dropdown-tree-select/blob/f90e9f84e0226d9364ec7ab13b3fc3bab3c50d17/src/tag/index.js#L50) with optionally-passed-in functional components (that default to `i`, `Checkbox` and `button` respectively) would suffice.  While the CSS is very nicely customizable, the `.toggle.collapsed::after`/`.toggle.expanded::after` pseudoselector isn't as versatile as e.g. using an image frm from react-icons.

**Comment by mrchief** [comment]
True. Without adding byzantine branching and plethora of properties, I started moving towards headless UI components with the [hooks branch](https://github.com/dowjones/react-dropdown-tree-select/tree/hooks). No tbeen able to find time for it though. 

There might be a middle ground where we can modify the HTML skeleton to allow for better CSS targeting without going all out via the headless UI route.

**Comment by m4theushw** [comment]
@mrchief The hooks branch is very behind develop. Do you have plans to sync it so we can help? 

For now, is not the solution proposed by @blerner acceptable? Besides https://github.com/dowjones/react-dropdown-tree-select/issues/402 I don't see other use cases where optionally-passed components would not be sufficient.

**Comment by mrchief** [comment]
@m4theushw There weren't a lot of changes in the hooks branch so it's easy to bring it up to date. I haven't gotten time unfortunately for it and could use some help. 

The solution proposed by @blerner is a slippery slope as it would increase the API are vastly and thus make it more likely that either the complexity will go up and maintenance, stability will become harder. This has been brought up in the past but if you and @blerner are up to it, we can give it shot. Personally, I think it'll be easier to do the hooks version.
