### ISSUE TITLE
White border around div.dropdown-content, ul.root

### ISSUE THREAD

**Issue by s-amaral** [dowjones/react-dropdown-tree-select#296]
I am trying to customize the style of react-dropdown-tree-select and I cannot adjust the white border around the div.dropdown-content or ul.root. To reproduce this white border inquiry, in the bootstrap example (https://dowjones.github.io/react-dropdown-tree-select/#/story/with-bootstrap-styles) I simply applied the following 

.bootstrap-demo .root {
  background-color: red;
  padding: 0px;
  margin: 0px;
}

to the end of index.css. Thanks in advance for any assistance.

**Comment by mrchief** [comment]
Those styles can be overridden with this CSS:

```
.react-dropdown-tree-select .dropdown .dropdown-content {
  border: none;
  background: transparent;
  box-shadow: none;
}
```

If it doesn't work, then try increasing the specificity of the selectors. One way is to add the class name of its ancestor element like this:

```
// html
<div class="rdtWrapper">
  <DropdownTreeSelect data={data} />
</div>

// css
.rdtWrapper .react-dropdown-tree-select .dropdown .dropdown-content {
	...
}
```

Or you can pass a `className` prop and use that in your CSS to increase the specificity of your styles.
