### ISSUE TITLE
padding 问题 

### ISSUE THREAD

**Issue by chenxiangdashen** [dowjones/react-dropdown-tree-select#297]
![image](https://user-images.githubusercontent.com/9529742/66693720-bbd98380-ecde-11e9-9659-df0c4f375204.png)
当我使用 material-ui 风格样式时，展开到第三层时  paddingLeft 距离 不够，看上去 就像是同一层级的 ， 希望 padding  能自定义

**Comment by mrchief** [comment]
@chenxiangdashen I think it's a question with `padding-left` but I'm afarid don't understand the script. Would you be able to provide an English translation?

**Comment by simon-sb** [comment]
Thank you @mrchief , for your answer. 
Looking forward to the version with hooks :-D
