### ISSUE TITLE
actions?: NodeAction[] - usage

### ISSUE THREAD

**Issue by AshInBelgium** [dowjones/react-dropdown-tree-select#300]
The d.ts describes the following in the TreeNode interface

/** An array of extra action on the node (such as displaying an info icon or any custom icons/elements) */
        actions?: NodeAction[];

This having the structure:
/** CSS class for the node. e.g. `fa fa-info` */
        className: string;
        /** HTML tooltip text */
        title?: string;
        /** Any text to be displayed. This is helpful to pass ligatures if you're using ligature fonts */
        text?: string;
        /** Any extra properties that you'd like to receive during `onChange` event */
        [property: string]: any;

All the elements expect string values, so how in fact can one 'display an info icon or any custom icons/elements' using this?

**Comment by mrchief** [comment]
`fa fa-info` comes from [FontAwesome](https://fontawesome.com/icons?d=gallery). So you can pick a different icon by specifying a different classname. E.g. `fa fa-times` will show the "X" icon. Does this help?

**Comment by AshInBelgium** [comment]
Yes that goes a long way to achieving what I need, thanks.
