### ISSUE TITLE
Cannot uncheck the last item

### ISSUE THREAD

**Issue by bill-zhongjie-li** [dowjones/react-dropdown-tree-select#301]
In the case there's only one item checked, if you try uncheck the item, the item will show unchecked in the dropdown tree, but it is actually still checked. 

It should either allow uncheck of the last checked item, or display it as checked if it is cannot be unchecked.

**Comment by mrchief** [comment]
That shouldn't happen unless you have default values set. Does it happen in the examples? Can you provide a Codesandbox reproducing the problem?

**Comment by bill-zhongjie-li** [comment]
Ya it is the default value. Can we fix the dropdown list so that it shows the item as checked? It looks weird when the item shows uncheck in the dropdown list but still show up in the selected items list.

Thanks!

**Comment by mrchief** [comment]
Are you using the latest version? It doesn't happen in the examples

![screencast 2019-10-24 20-11-13](https://user-images.githubusercontent.com/781818/67534133-aed37180-f69a-11e9-81af-b0cc1fc8f21d.gif)

**Comment by bill-zhongjie-li** [comment]
It does not work properly in the case when the last uncheck item is the only default value.

**Comment by mrchief** [comment]
I tried with only one item in a sandbox but I still can't reproduce it.


![single default value](https://user-images.githubusercontent.com/781818/67623112-89a44780-f7ef-11e9-83bd-56772c714c4f.gif)
