### ISSUE TITLE
Placeholder texts props is not working

### ISSUE THREAD

**Issue by ioannisth** [dowjones/react-dropdown-tree-select#305]
**Describe the bug**
I cannot make the dropdown placeholder to be something else than "choose..." by setting the "placeholder" prop. This is only happening on v2.x , while on v1.x it was working by setting the "placeholderText" prop

**To Reproduce**
Visit
https://codesandbox.io/s/react-dropdown-tree-select-ftjfc 
Add a "placeholder" prop to the component. Nothing changes. 

**Expected behavior**
I would expect the placeholder of the dropdown to reflect the "placeholder" prop

**Screenshots**

**Environment (please complete the following information):**
 - Browser [e.g. chrome v60.12.0, safari 10.1]
 - OS: [e.g. iOS, Windows x64] (if applicable)
 - node version (if applicable)
 - yarn or npm version (if applicable)

**Additional context**

**Comment by mrchief** [comment]
With v2.x, all the texts are bundled into a single prop [`texts` ](https://github.com/dowjones/react-dropdown-tree-select#texts). 

For a complete list of breaking changes and their migration path, please refer to the [release notes](https://github.com/dowjones/react-dropdown-tree-select/releases/tag/v2.0.0).

I updated your CodeSandbox to verify and you can see it working again with the updated prop here https://codesandbox.io/s/react-dropdown-tree-select-55b33.

**Comment by ioannisth** [comment]
oh, didn't notice the structure change,I adjusted and it works very well now, thanks!
