### ISSUE TITLE
HI .. im trying to use hierarchical tree structure. i don"t  want multiple value to be selected .. i want a simple dropdown behaviour with hierarchical in it

### ISSUE THREAD

**Issue by gauthamdaze** [dowjones/react-dropdown-tree-select#307]

**Comment by gauthamdaze** [comment]
tag-item should be only one

**Comment by jp-albrecht** [comment]
I am also trying to use the hierarchical tree structure, but I only want the user to be allow to select one option. Is this possible?

**Comment by jp-albrecht** [comment]
> I am also trying to use the hierarchical tree structure, but I only want the user to be allow to select one option. Is this possible?

I figured out you can use mode="radioSelect" to accomplish the hierarchical tree with a single value
