### ISSUE TITLE
render the search input inside the dropdown. not on the toggle button

### ISSUE THREAD

**Issue by osmancode** [dowjones/react-dropdown-tree-select#308]
**Is your feature request related to a problem? Please describe.**
I need to render the search box inside the dropdown, not on the main button.

**Describe the solution you'd like**
a configuration option allows us to choose where to render the search button

**Describe alternatives you've considered**
Fork the repo!.

**Additional context**
This is the design i am trying to achieve.
![image](https://user-images.githubusercontent.com/1795294/69324793-667f8300-0c49-11ea-96dd-e3c72ca897bc.png)

**Comment by mrchief** [comment]
That seems like a useful thing to have. Would you like to send me a PR?

**Comment by mrchief** [comment]
Based on the screenshot, it seems like the design goals are:

 - inline search input (inline with content)
 - simple select, no tree
 - no tags either?
 - dropdown title needed next to the toggle button (`YTD... ^` in the screenshot)

Am I missing anything?

**Comment by osmancode** [comment]
No, i only need to render the search input inside the dropdown-content. everything else can be solved by styling on my side. thanks.
