### ISSUE TITLE
Use as subcomponent

### ISSUE THREAD

**Issue by h0rm** [dowjones/react-dropdown-tree-select#31]
When using the component as a subcomponent `componentWillReceiveProps` of DropdownTreeSelect will be called for every `setState`  in the parent component which rebuilds everything using `data` prop (even if  `data`  has not changed and even if it is a const variable). This means I have to update `data` otherwise all selections are cleared on every  `componentWillReceiveProps`. 

Since I don't want to manage the selections myself I changed `componentWillReceiveProps` to check if the `data` prop has changed and ignore it otherwise. This is however very ugly and more of a hack since the prop and the actual tree diverge this way -> I use `data` prop as the initial tree (see [fork](https://github.com/h0rm/react-dropdown-tree-select/commit/15fe836eeb1084d5d3b0b8e0ab82bf7106991fe4)).

My only idea to solve this would be to return the updated tree on `onChange ()`. This way the parent component can still decide to change the selections and the `data` prop and the actual selections are always in sync. However, this still means that on every `componentWillReceiveProps` everything is recreated (not sure what this means for the performance). 

Any thoughts on this? Did I miss something really obvious?

**Comment by mrchief** [comment]
@h0rm does [this](https://github.com/dowjones/react-dropdown-tree-select/issues/32#issuecomment-350024732) fix your problem?

**Comment by h0rm** [comment]
fix works thanks!
