### ISSUE TITLE
How to Open Upwards?

### ISSUE THREAD

**Issue by NAVEENND** [dowjones/react-dropdown-tree-select#310]
Hi,

dropdown height affects the page height, how to open upwards?

Thanks,
Naveen.N.D

**Comment by NAVEENND** [comment]
![image](https://user-images.githubusercontent.com/35757341/69525531-4bd14500-0f8e-11ea-92f2-2ddb255e0c91.png)

**Comment by mrchief** [comment]
You can do it with a bit of CSS:

```
.dropdown-content {
  bottom: 100%;
}
```

Here's a [CodeSandbox](https://codesandbox.io/s/issue-310-open-upward-react-dropdown-tree-select-4e2km) demo. 

Note:  I added a `top-margin: 90%` to the body to simulate your use-case.

**Comment by NAVEENND** [comment]
Its working. thank you very much mrchief .<3

**Comment by NAVEENND** [comment]
thank you very much, it's working.

**Comment by hungdev** [comment]
@mrchief How to make it automatically.  if it is close below the screen it will show up, otherwise it will show down.
thanks!

**Comment by mrchief** [comment]
Are you talking about doing so on a scrolling page? If you know the position beforehand, you can apply a fixed css class. If not, then I'm afraid you'd have to use JS that attaches that CSS class on scroll (detecting if the control is near the bottom viewport).
