### ISSUE TITLE
showDropdown false

### ISSUE THREAD

**Issue by mako10110** [dowjones/react-dropdown-tree-select#311]
**Is your feature request related to a problem? Please describe.**
ShowDropdown only receives two string as settings which is "Initial" and 'Always'
What about a false state where I want to close the dropdown.

**Describe the solution you'd like**
There should be a false position as well so that I can control its state using onFocus and onBlur function.

**Describe alternatives you've considered**
Apparently there is no way of controlling the state to a closed position using onFocus or onBlur.

**Additional context**
My case is where the user clicks outside of the dropdown and I want to keep it open until onFocus is triggered again.
I think there should also be a string called "false" where the dropdown should render a closed position.
This would be very helpful for my case maybe for others as well.
Thank you in advance.

**Comment by mrchief** [comment]
> My case is where the user clicks outside of the dropdown and I want to keep it open until onFocus is triggered again.

This is rather interesting and if understand correctly, you want something like:

`User clicks on down arrow > expand dropdown > user clicks outside > dropdown stays open > user clicks inside the search box again > dropdown closes`

correct?

This feels a bit of an odd behavior. How does the dropdown open again? 

While I'm certainly interested in learning more, I think you can do something like this currently yourself:

 - set `showDropdown=Always`
 - control visibility via css classes

Something like here [![Edit Using Bootstrap Styles with React Dropdown Tree Select](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/using-bootstrap-styles-with-react-dropdown-tree-select-cy6r0?fontsize=14&hidenavigation=1&theme=dark)
