### ISSUE TITLE
Enable creating new items when no match is found

### ISSUE THREAD

**Issue by Nogias9x** [dowjones/react-dropdown-tree-select#312]
**Describe the bug**
- **onAction** is not fired when search term's change, node's toggled (**onNodeToggle**), selected node is changed (**onChange**)

**To Reproduce**
- Visit [my CodeSandbox](https://codesandbox.io/s/react-dropdown-tree-select-l245i)
- Perform some actions like change term or toggle nodes

**Expected behavior**
- **onAction** callback is fired.

**Additional context**
- Actually, my story is "As an HR, I want to create new job position if no jobs match my search term", so I need **onAction** to be fired to captured the latest search term.
To work-around, I will using **document.querySelector** to get the latest search term then.
But I think this issue is worth to be concerned.

**Comment by mrchief** [comment]
`onAction` is not supposed to fire on search term change or any of the other events you describe. `onAction` fires when your **action** buttons are clicked.

**Comment by Nogias9x** [comment]
Thank you for your fast response @mrchief,

>onAction is not supposed to fire on search term change or any of the other events you describe. onAction fires when your action buttons are clicked.

Yeah, It was my fault. I got it now. Thank you.


After I applied my work-around for the case, I realized `onNoMatches` doesn't completely help the case. (But I cannot disagree that `onNoMatches` is a cool event to have)

For example, a HR want to add new job "Manager" to the list which already contains "Product manager", onNoMatches` won't be fired (because "Product manager" matches the term "Manager"), so the HR cannot create "Manager" position.

So, I think maybe `onCreateNew = (nodeName) => {}` may help. Having `onCreateNew` means "creatable" :)

I know this one is not a simple feature, so it may take time. Do you think we have any work-around for the case with the current version?

Thank you and have a nice day @mrchief

**Comment by mrchief** [comment]
> For example, a HR want to add new job "Manager" to the list which already contains "Product manager", onNoMatches` won't be fired (because "Product manager" matches the term "Manager"), so the HR cannot create "Manager" position.

Not sure how this would work or if it's a good idea to have this kind of workflow. Think about this from a UX perspective, how does one tell when to select vs. when to add new? 

A better UX might be to give the user a choice to add new items when nothing's found. That can be done by changing the message for no matches and adding a plus button outside of the component that takes the user through item creation flow. Once a new item is created, you then provide the updated tree data to the component.

**Comment by Nogias9x** [comment]
Thank you for the response  @mrchief ,
I'm glad that you are interested in this usecase. 

>Not sure how this would work or if it's a good idea to have this kind of workflow. Think about this from a UX perspective, how does one tell when to select vs. when to add new?

Here is the UI of Notion. There is always "Create" option. Some components place the "Create" option at the beginning of the list. Some have it at the end (like Notion).
![image](https://user-images.githubusercontent.com/11822492/70963105-1e257a80-20ba-11ea-8906-fad61a4efc70.png)

>A better UX might be to give the user a choice to add new items when nothing's found. That can be done by changing the message for no matches and adding a plus button outside of the component that takes the user through item creation flow. Once a new item is created, you then provide the updated tree data to the component.

I already did this, and encountered the case of partial matching :( . Besides, I had to custom `react-dropdown-tree-select` a lot with my stupid and redundant customization, such as:
- make search input auto focus when the selector is focused
- auto submit the creation when user hit ENTER in search input (because it is not a form)
- after user clicks "Create new value", perform click on the selector (emulation of selector toggle) to close the "Create new value"(used to be "No matches found") dropdown

**Comment by mrchief** [comment]
The screenshot makes things a lot clearer! I'm afraid there's no easy way to do this. This would be something that's possible with a planned feature in the next version but that's far from being done and I don't have a timeline for that release. 

I can think of a possible solution which relies on taking in a `CreateItemTemplate`, and updater function (I'm assuming the label auto updates as the user types in) but I'm hesitant as it'd add a lot of complexity for what seems like an edge case (in other words, not a frequently asked for feature).

A slightly less complex solution would be something like this:

 - expose a `onNoMatch` event
 - create on HoC that wraps the component, listens to no match even and then updates an item which is outside of the component. 
 - use css to make it appear seamless

Doesn't seem like an elegant solution if you ask me. I can't think of any other ideas at the moment but I'm open to suggestions.

**Comment by Nogias9x** [comment]
>This would be something that's possible with a planned feature in the next version but that's far from being done and I don't have a timeline for that release.

Yeah, I totally understand.

>A slightly less complex solution would be something like this:
- expose a onNoMatch event
- create on HoC that wraps the component, listens to no match even and then updates an item which is outside of the component.
- use css to make it appear seamless

That's cool, I think it would work.

I'm wonder if we can expose a prop like 
```js
const [searchTerm, setSearchTerm] = useState('');
.....
<DropdownTreeSelect
      onSearchTermChanged={(newTerm, oldTerm, data)=>{
        setSearchTerm(newTerm);
      }}
      floatingItem={{
        position: 'start', // in {'start', 'end'}
        element: (
          <button
            onClick={() => {
              alert(`Creating ${searchTerm}`)
            }}
          >
            Create "{searchTerm}"
          </button>
        )
      }}
/>
```

What do you think @mrchief ?

P/S: Sorry for my English and the props naming :)

**Comment by mrchief** [comment]
> I'm wonder if we can expose a prop like

We can certainly give it a try. We have to be very carefully not to cause tree re-renders :)

> P/S: Sorry for my English and the props naming :)

No worries!

**Comment by Nogias9x** [comment]
Thank you @mrchief .
Please keep me posted. I'm pretty interested in this case :)

**Comment by DryJhin** [comment]
Hello,

Any news about this feature ? I am also interested in this behavior, also I think other would benefit from it.

Thanks for your time

**Comment by mrchief** [comment]
@DryJhin are you interested in working in building this?
