### ISSUE TITLE
"x" buttons have same id in HTML DOM

### ISSUE THREAD

**Issue by Nogias9x** [dowjones/react-dropdown-tree-select#315]
**Describe the bug**
"x" buttons have same id in HTML DOM.
The problem happens when every node has **`id`** property, when nodes have .id, "x" buttons stop using DropdownTreeSelect.props.id.

**To Reproduce**
- Visit my [codesandbox](https://codesandbox.io/s/react-dropdown-tree-select-6ose6)
- Inspect the page, find for "button.tag-remove" (all buttons which's  CSS class = "tag-remove")
- **Actual behavior:** You will notice all found buttons have the same id="2_button"

**Expected behavior**
The buttons' ids should be different between different DropdownTreeSelects (like ${DropdownTreeSelect.props.id}_${node.id}_button).

![image](https://user-images.githubusercontent.com/11822492/70976132-f9db9500-20dd-11ea-9971-d7b3b1a27e3c.png)

![image](https://user-images.githubusercontent.com/11822492/70976033-b3863600-20dd-11ea-80ef-2c39edc98867.png)

**Comment by mrchief** [comment]
Yeah, this is a bug. In general, I think the id creation logic across all individual components will probably suffer from the same defect. A safer idea is to prefix with the root id itself. 

A PR would be welcome!

**Comment by Nogias9x** [comment]
Yeah, I'd love to contribute to your awesome lib :>

**Comment by mrchief** [comment]
@Nogias9x this is not a bug. If you check in your sandbox, you're assigning custom `id` to nodes in your data json. Since all instances are using the same demo data, they all get the same id. 

I removed `id` nodes from your data and as you can see, you get unique ids across instances

![image](https://user-images.githubusercontent.com/781818/72673052-c076ac00-3a32-11ea-9bd9-1912005d5461.png)

The same goes for `tag`s.

**Comment by Nogias9x** [comment]
Yes you are right @mrchief . But I think the `.id` should be reserved by the list items. For example, if the select is list of job positions, the `.id` should be position.id which is fetching from database.

**Comment by mrchief** [comment]
When you say it should be “xyz”, you’re unconsciously transitioning into business domain. To avoid being sandboxed into such decisions, the component lets you decide and shape that piece of information. E.g , you could assign the id to be that “xyz” that you need and the component will reflect that. 

Another person could then use “abc” to be the id and the same component can serve both. 

My PR is again a generic solution as we support the use case of having multiple instances and it makes sense semantically to have unique ids in the dom. 

If you’re using id field to store some data, then you don’t need to do so as you can very well pass any arbitrary prop to node and it’ll bubble it back on change events.
