### ISSUE TITLE
Maximum UI control for developers

### ISSUE THREAD

**Issue by Bulletninja** [dowjones/react-dropdown-tree-select#319]
This is a somewhat general idea sharing on my side rather than a prescription. 
I've been using some components in a project, mainly this one and [react-table](https://github.com/tannerlinsley/react-table), and what i've noticed is that this component (`DropdownTreeSelect` that is) is great out of the box... but, you can hit a limit, since it prescribes some ways of doing things, nothing wrong with that in itself, but some of those opinions make it less flexible than it could be.

What i mean with this is that i know i can add flags all day to the data tree, in fact that's what i've done to have some extra features locally. The problem is that it gets cumbersome and kind of slow if you want to do a lot of customization.

Now, the reason i mentioned react-table is it has the concept of "headless ui components" (see [this](https://medium.com/merrickchristensen/headless-user-interface-components-565b0c0f2e18) and [this](https://github.com/tannerlinsley/react-table/blob/master/docs/concepts.md)). The way i see it, it consists of decoupling behaviors from UI implementation, or as those links put it: 

> ... as a library honestly has no business being in charge of your UI

How to translate this for `DropdownTreeSelect`? I think one way is to have a tree with just 2 keys (or at least these 2): `component` and `children`. The component key would enable us to put a function that receives props in there, some of which could be the current ones (ex. label, value, expanded, etc...). And children would do what children does right now. That way we could be in charge of our own UI, and we'd have full control over it. This also doesn't prevent us from having a default ui if we want, but we can still overwrite it passing the `component` function.

**Comment by mrchief** [comment]
It's funny you mention react-table. I like Tanner's approach a lot (you can see the docs is based of react-story which was a precursor to react-static) and this lib has lot of influences from react-table's API. 

I fully agree about the hitting the UI limit and I was hoping to tackle this issue in the next iteration (which is based on hooks). I was experimenting in this [branch](https://github.com/dowjones/react-dropdown-tree-select/tree/hooks) but haven't had the time to finish it yet. 

> How to translate this for DropdownTreeSelect?

There are many ways to go about it but based on previous requests, I had this in mind:

 - DropdownTreeSelect = Tree Manager + Root + Individual child renderers (input/dropdown, node labels etc.)
 - Have default renderers that give you the same functionality as v1, out of the box. So if you're migrating from v2 to v3, there's an easy migration path.
 - Export individual renderers so you can re-layout them as needed. Need to figure out how to style things for this to work. CSS-in-JS is one approach but I'm not sold on the idea yet. 
 - See if hooks make things simpler and adapt as necessary. 

Another blocker is this issue: https://github.com/reactjs/reactjs.org/issues/2428

**Comment by mrchief** [comment]
Closing this issue for now. This will most likely be solved with the next major version with hooks.
