### ISSUE TITLE
how to appending children dynamically to the parent.

### ISSUE THREAD

**Issue by sathvik12345** [dowjones/react-dropdown-tree-select#321]
on toggle of the parent, we will call an API to get the children for that parent.. and append that child to a particular parent.

initially, we won't get any children from API.. if we don't have any children for a particular parent the toggle is not working...

**Comment by mrchief** [comment]
That is not possible natively within the component, however, you can create an HoC which can fetch and re-initialize the component with newly fetched data. Depending on your requirements, this may or may not be ideal.

> initially, we won't get any children from API.. if we don't have any children for a particular parent the toggle is not working...

You can probably add a dummy child that says "Loading..." or similar which will let you toggle, as well as let you listen to `onChange` for that - so you can do the fetch and re-init, if you wish.
