### ISSUE TITLE
Using a different hierarchy structure

### ISSUE THREAD

**Issue by jean182** [dowjones/react-dropdown-tree-select#326]
Hi I was wondering, how can you pass a different structure, one that has children, but is not using the same keys as the one used in the docs, I was not able to find related info on how to change the structure. for example

Structure in the docs: 
```
const data = [
  {
    label: "VP Accounting",
    checked: true,
    children: [
     // Children objects
    ]
  }
];
```
I have an structure like this:

```
const data = [
  {
    type: "node",
    id: "1"
    attributes: {
      displayName: "Name",
      children: [
         // Children objects
       ]
    },
  }
];
```

As you can see I have a similar structure but the `label` key which in my case is called `displayName` and the `children` key are inside the `attributes` key, how can I use that structure with this? Is there a way to do it without having to modify the structure?

**Comment by mrchief** [comment]
I think you can use the HoC approach where you transform data from your format to one that the component understands. You can also store refs to your original data node (e.g. 

```
node = { 
  label: ... 
  // other props
  ref: 'data[0].attributes[0]'
```

Every event will pass you the node and any extra props you send, so you can use the ref to locate the source record and update it easily (maybe?). Something like this [tree-node-paths-hoc](https://dowjones.github.io/react-dropdown-tree-select/#/story/tree-node-paths-hoc)
