### ISSUE TITLE
not able get the child entires of the parent when parent is selected from the dropdown 

### ISSUE THREAD

**Issue by gauthamdaze** [dowjones/react-dropdown-tree-select#327]
not able get the child entires of the parent is selected from the dropdown .

**Comment by mrchief** [comment]
Your ask is similar to [this](https://github.com/dowjones/react-dropdown-tree-select/issues/168#issuecomment-421505076). You can try the solution posted [here](https://github.com/dowjones/react-dropdown-tree-select/issues/108#issuecomment-391836044).

**Comment by gauthamdaze** [comment]
Thanks a lot

**Comment by PlopTheReal** [comment]
It feels strange that there isn't a simpler way to get the selected nodes from the onchange event.
