### ISSUE TITLE
Deprecated lifecycle methods

### ISSUE THREAD

**Issue by TheHaymaker** [dowjones/react-dropdown-tree-select#328]
ComponentWillMount and ComponentWillRecieveProps are still being used in the latest version (need to be migrated to ComponentedDidMount and ComponentDidUpdate ). I'm flagging because I couldn't find any open issues to address this yet and want it at least added to the backlog.

Open and willing to make this contribution if it isn't already in the backlog / taken up by someone else.

**To Reproduce**
Install package in a project that uses React v16.8.x or higher.

**Expected behavior**
Should not see console errors if using React v16.8.x

**Screenshots**
![errors](https://user-images.githubusercontent.com/11251616/73399211-78fee400-42ac-11ea-87d5-399c65836c9f.png)

**Environment (please complete the following information):**
- Browser: Chromiom (Electron / Openfin app)

**Comment by mrchief** [comment]
There was an issue before but I haven't been able to make much headway with the hooks version. For now, I think renaming it to `UNSAFE_...` and bumping the semver requirement in package.json should do the trick. 

You're more than welcome to contribute to the hooks branch as well.
