### ISSUE TITLE
Focus is lost when switching between keyboard and mouse selection

### ISSUE THREAD

**Issue by TheHaymaker** [dowjones/react-dropdown-tree-select#329]
Focus on dropdown item is set programmatically on key events. When switching between mouse and keyboard, the focused item is not updated when selected via mouse.

**To Reproduce**
Tab to highlight selectbox -> keydown to open dropdown ->keydown to move focus through dropdown items. Switch from keyboard only to mouse and click a different item. Focus doesn't change.

**Expected behavior**
Focus should follow keyboard AND mouse events in dropdown.

![focus-select-tree](https://user-images.githubusercontent.com/11251616/73462901-1526fa80-4342-11ea-9e4b-41038eec0dbb.gif)

**Environment (please complete the following information):**
 - Chromium (electron / openfin)

**Comment by mrchief** [comment]
Thanks for reporting this. I haven't had the chance to look into this but let me ping our resident accessibility expert here: @ellinge :)
