### ISSUE TITLE
Increase Page Size or how to load more then 100 elements in dropdown

### ISSUE THREAD

**Issue by rajivranjanpandey** [dowjones/react-dropdown-tree-select#330]
I want to load more then 100 elements in dropdown?
But there is no props availaible for this , so kindly provide some props to increase the number of elements shown currenlty in the dropdown

**Comment by mrchief** [comment]
Keeping it to reasonable number was a conscious decision. Can you please tell me why you want this to be more or configurable?

**Comment by rajivranjanpandey** [comment]
Because i am using this library
And data i am providing this library contains 600 elements which is needed
since we need to select after seeing..search is not possible in every
scenario
So kindly provide some props to modify it

**Comment by mrchief** [comment]
> And data i am providing this library contains 600 elements which is needed
since we need to select after seeing..search is not possible in every
scenario

You can see all the elements when you scroll up or down.

**Comment by rajivranjanpandey** [comment]
No on scroll its not loading
Only shows 100 elements

**Comment by mrchief** [comment]
Can you create a CodeSandbox to reproduce it?

**Comment by rajivranjanpandey** [comment]
Codebox is unable to process 600 elements
So kindly on your side you take 600 elements and check it .. on scroll its
limited to 100 elements only

**Comment by mrchief** [comment]
> Codebox is unable to process 600 elements

That doesn't sound correct. Some of the old issues did have more elements. 

> So kindly on your side you take 600 elements and check it .. on scroll its
limited to 100 elements only

Have you check the `Large Tree` story on the docs page? https://dowjones.github.io/react-dropdown-tree-select/#/story/large-tree

This still works.

**Comment by rajivranjanpandey** [comment]
Yaa i checked those but still it doesn't solve my issue all i want some
props to change the page size or option to show all posts instead of only
100 elements

**Comment by mrchief** [comment]
There are performance issues when you try to load a lot of elements in the DOM. Plus, in most uses cases, the user cannot see all 100 elements or more at a time in their viewport, so rendering them when the user can't see them doesn't make sense. This is why infinite scroll exists so we only render what the user sees.

**Comment by rajivranjanpandey** [comment]
How to activate the infinite scroll property

**Comment by mrchief** [comment]
There is no activation. You scroll and the list loads next 100 elements when needed. Same thing happens when you scroll up.

**Comment by rajivranjanpandey** [comment]
It's not that is what i am trying to make u understand

**Comment by mrchief** [comment]
Without a reproducible code example, there is nothing more I can do here.

**Comment by rajivranjanpandey** [comment]
okay i am trying once again with sandbox

**Comment by NishaBhat** [comment]
Hi,
This is what I tried. I have 1000 children under 1 parent node but only 100 are displayed. The UI looks strange probably missing dependencies
https://codesandbox.io/s/dazzling-allen-wrbx0?fontsize=14&hidenavigation=1&theme=dark

**Comment by NishaBhat** [comment]
Do you have the code in a sandbox for https://dowjones.github.io/react-dropdown-tree-select/#/story/large-tree?  When I try to load that data I get an empty dropdown

**Comment by mrchief** [comment]
@NishaBhat It was missing stylesheet (the default one) as well as one custom style to limit the dropdown height. I updated it and now you can see it loading elements as you scroll through.

https://codesandbox.io/s/optimistic-lewin-1tyh3

```
.dropdown-content {
  max-height: 400px;
  overflow-y: auto;
}
```

**Comment by NishaBhat** [comment]
That's great!!! Thank you
