### ISSUE TITLE
Disabling an item in the dropdown still gets altered if the default value is 'true' and its pillbox's 'x' is clicked.

### ISSUE THREAD

**Issue by TheHaymaker** [dowjones/react-dropdown-tree-select#332]
A disabled item is prevented from being checked in the dropdown, but if the 'x' on the pill is clicked, the item's checkbox state is altered.

**To Reproduce**
Disable all items. Them close them from the active pills. They will be 'unchecked'. This is unintended behavior.

**Expected behavior**
If an item is disabled, a user should not be allowed to remove it. Currenlty, there's no way for me as a developer to override this behavior.

**Comment by mrchief** [comment]
This sounds like a bug as I’m pretty sure we have logic to prevent this from happening. Maybe “all” is somehow escaping that or maybe that code is broken entirely. Need to look into this.
