### ISSUE TITLE
How can I setState inside onChange function?

### ISSUE THREAD

**Issue by abhinav2331** [dowjones/react-dropdown-tree-select#333]
Please have a look on the code I need to setState for selected values from dropdown list.
https://codesandbox.io/s/react-select-ik40g

**Comment by mrchief** [comment]
@abhinav2331 It seems like you want to setState on your app when something in the tree changes but in doing so, you don't want the tree to re-render, correct? If that's the case, you can use this approach https://dowjones.github.io/react-dropdown-tree-select/#/story/prevent-re-render-on-parent-render-hoc
