### ISSUE TITLE
Loading 50k - 500k nodes in the tree

### ISSUE THREAD

**Issue by NishaBhat** [dowjones/react-dropdown-tree-select#334]
Create a tree with one parent and 50k child nodes. Start scrolling till you hit the 20k child. Try to close the parent node. The performance of the tree goes down. I have updated the sandbox for this examplr

https://codesandbox.io/s/hopeful-glitter-7md82

**Comment by mrchief** [comment]
Thanks for the sandbox!

Curious, is this a real use case? I couldn't continue scrolling beyond 2K and I can't imagine anyone scrolling to 20K elements (that's 200 scroll events). I'd rather use search at this point.

But I'm curious as to how you'd close the parent after the 20kth element? You'd need to scroll up again (200 times) to get to the parent, right?

**Comment by NishaBhat** [comment]
Thanks for your prompt replies :)

I agree, this is not a typical use case and I totally get your point. Most users would use search to find the node. But the acceptance criteria for me(in my company) is that it works in this scenario. 
Yes, to close the parent you would need to scroll up.  

I did some digging and found https://github.com/bvaughn/react-window . Brian Vaughn - the same author of react virtualize created react window. We could potentially have data with millions of nodes, so this could do the trick.
I really like the search feature and check-boxes you provide. A merger of both is what I need :)

**Comment by mrchief** [comment]
I looked into react-window when I was searching for virtualization options. We use react-infinite-scroll-component for the same. Conceptually, they are the same. The infinite-scroll component is bit more flexible as it allows for items with dynamic height.

If you think react-window offers better performance and can meet existing use-cases, then I will be happy to see a PR!
