### ISSUE TITLE
Animating expanding and collapsing could be a UX necessity

### ISSUE THREAD

**Issue by deniskabana** [dowjones/react-dropdown-tree-select#337]
**Is your feature request related to a problem? Please describe.**
For `react-dropdown-tree-select` everything is rendered as a single unordered list with padding added on `node.style` (for tree list with expanded children). I suppose this is due to CSS hiding when filtering (which is quite clever and fast) but kills hierarchy (elements are not wrapped). Makes it very very difficult to implement sliding animation for reveal (close animation is not as necessary for our use-case and from a UX standpoint could be omitted or just very quick).

**TL;DR:** Expanding children in a tree results in mounting and dismounting list items to the top-level row. Very hard to add animation to this type of usage.

![ezgif-6-513831ddc4f8](https://user-images.githubusercontent.com/8308865/75254274-6a8ae600-57e0-11ea-9db3-dd49732d31d7.gif)
Sandbox of the setup in GIF:
https://codesandbox.io/s/cool-noether-p3f41?fontsize=14&hidenavigation=1&theme=dark

**Describe the solution you'd like**

1. Wrap every list item content in a div, like `<li class="node tree"><div class="list-item-container">...</div></li>` and wrap nested children in a `ul > li` structure as well. I feel like I am missing something here, though.
2. Add an option to delay unmounting by any config / prop (e.g. `delayUnmount?: number = 0`) and **create new callbacks** -> `nestedChildrenDidMount(nestedChildren: TreeNode[] | string[])` and `nestedChildrenWillUnmount(timeUntilUnmount: number)`. _Doesn't solve revealing animations however._
3. Consider adding callback specifically to let the users decide whether they can live with performance penalty on manipulating huge lists manually. That could be something like just revealing list of DOM nodes in a specific callback.

**Describe alternatives you've considered**
Right now, to achieve the desired result, I am using a hack - linear transition and style/className manipulation. Easing could have severe impact on performance and I don't think adding custom JS easing for multiple elements is worth the added overhead to the code. See https://codesandbox.io/s/cool-noether-p3f41?fontsize=14&hidenavigation=1&theme=dark for code.

**Additional context**
I'd be happy for any suggestions or ideas in this matter.

**Comment by deniskabana** [comment]
## Update 
For anyone interested, I have been working on another solution. This is a drop-in solution, that wraps the `react-dropdown-tree-select` in another component that intercepts `onNodeToggle(currentNode)` callback. This is what it looks like:
![ezgif-3-ba76a4899f4b](https://user-images.githubusercontent.com/8308865/75449064-a3f05c80-596c-11ea-8ebc-bcb91d9f241c.gif)

The code is commented and tested and working for tree lists. If anyone wants to use it, copy `AnimatedDropdown.js` and use that as a direct replacement for `react-dropdown-tree-select` for now.

Working code sandbox with demo: https://codesandbox.io/s/xenodochial-meitner-v1950

**NOTE: My demo works only if all list items have equal height !!**
_I've used very fast but naive implementation. Feel free to re-write it. Just change created css to do `visibility: hidden` instead of `height: 0` and measure height of each before starting._

**Comment by mrchief** [comment]
@deniskabana This looks amazing! I'm going to dig deeper and see if we can integrate it somehow. I'm thinking either as an HOC example or as part of the dist bundle (in a way that it is tree shakable). If you have ideas, please send them along.

**Comment by deniskabana** [comment]
@mrchief Thank you! I'd be glad to help integrate it with some help from any of the contributors :) I have some pointers and ideas about how we could make it even better were I to change the code that handles tree nodes.

**Comment by mrchief** [comment]
@deniskabana Please send them along. We can discuss the ideas here or if you want to send any PRs, feel free to do so.

As a pointer, when I said tree shakable, I meant something like this:

```
//// current situation
// only imports the core
import DropdownTreeSelect from 'react-dropdown-tree-select' 

//// future
// only imports the core
import DropdownTreeSelect from 'react-dropdown-tree-select' 

// imports animated hoc 
import { AnimatedDropdownTreeSelect } from 'react-dropdown-tree-select' 
```

As long as the core import doesn't bring the whole bundle (core + HoCs), this should be OK; in fact better than OK as we're now enhancing the developer's experience without imposing any extra bundling cost. Does that make sense?

**Comment by deniskabana** [comment]
@mrchief Sure thing! First of all let's review all issues with my current solutions:
## Issues
1. It naively expects every single tree node to be of equal height; Does not work any other way without a major rewrite - I would need to create a data structure that holds information about children in one place and traverses these to get proper values about it.
2. I do not provide any `requestAnimationFrame` loop cancellation. Nodes are unmounted as soon as I close it and there's failsafe to let it finish gracefully in the background. Could be stopped as well and provide the loop ID for manual cancellation in case it's needed.
3. It only works with expanding, not with collapsing. Would require more work in core components, albeit a tiny conditional modification - only if animated, execute this 1 extra thing.
4. I use dynamically created string for matching elements without having any other external reference to them. It's not bad but could be done better inside the library by refs or access to the full data structure.

## Propositions
1. Hiding tree nodes by default on mount with `HTMLElement.style.visibility`, measuring their heights and animating from there - animator would be responsible for unhiding and starting the animation. Right now I'm adding a `<style />` notation to the `document.head` with height: 0 for each ID.
2. Postponing unmounting of components if animating (unmount in timeout). Haven't checked yet, might be a bit harder than a one-liner I expect to work.

**Comment by mrchief** [comment]
Hey @deniskabana, not sure what happened here. Were you expecting something from me?
