### ISSUE TITLE
option to Hide checkboxes for root nodes

### ISSUE THREAD

**Issue by rbadapanda** [dowjones/react-dropdown-tree-select#343]
**Is your feature request related to a problem? Please describe.**
I want some of the tree nodes not to be select-able. for ex: if I show a hierarchy of folders I don't want users to select the network folders - only their children can be selected.

**Describe the solution you'd like**
If I have a way to hide the checkbox for certain nodes that would help
user can provide a lambda - disableANodeIf - passed as a parameter to the react-dropdown-tree-select component which will be applied on each node to determine if a "disabled" or "hide" class should be applied on a node

**Describe alternatives you've considered**
hiding the checkbox is best IMHO,
a disabled checkbox also would work

**Additional context**

**Comment by mrchief** [comment]
> If I have a way to hide the checkbox for certain nodes that would help

You can hide the checkboxes with css. You could emit custom css classes for whatever node you want to hide and then add css to hide the nodes.

```
// data
data = [{
	  label: 'hide me',         
	  className: 'hideMe'
	  ...
	}
]

// custom css
.hideMe .checkbox-item { display: none; }
````

**Comment by rbadapanda** [comment]
> > If I have a way to hide the checkbox for certain nodes that would help
> 
> You can hide the checkboxes with css. You could emit custom css classes for whatever node you want to hide and then add css to hide the nodes.
> 
> ```
> // data
> data = [{
> 	  label: 'hide me',         
> 	  className: 'hideMe'
> 	  ...
> 	}
> ]
> 
> // custom css
> .hideMe .checkbox-item { display: none; }
> ```

This already works. - Thanks!

Wondering how difficult it will be to support the following experience:
Keep the checkbox showing. but don't let user click on it. (kind of in readonly mode)

**Comment by mrchief** [comment]
> Keep the checkbox showing. but don't let user click on it. (kind of in readonly mode)

You can set `"disabled": true` on each node which will disable the checkbox.

**Comment by rbadapanda** [comment]
> > Keep the checkbox showing. but don't let user click on it. (kind of in readonly mode)
> 
> You can set `"disabled": true` on each node which will disable the checkbox.

this does not work - the checkbox is no more clickable

**Comment by mrchief** [comment]
Checkboxes don't have a readonly mode - they are not like text input.
