### ISSUE TITLE
Is there any way we can read/control the expanded keys? 

### ISSUE THREAD

**Issue by osmancode** [dowjones/react-dropdown-tree-select#344]
I am looking for an API similar to the one in https://www.npmjs.com/package/rc-tree-select ( treeExpandedKeys, onTreeExpand)?

is it implemented somehow or is there a way to have it?

**Comment by mrchief** [comment]
For tree expand/collapse you have `onNodeToggle`. We don't have `treeExpandedKeys` customization currently. We bind them to arrow keys as per accessibility guidelines.

**Comment by osmancode** [comment]
Thank you. that helped me achieve what I want: https://codesandbox.io/s/lively-microservice-g2h32
I needed to force only one open first-level node.
