### ISSUE TITLE
React 16.13.0 warnings

### ISSUE THREAD

**Issue by giacomoronconiobda** [dowjones/react-dropdown-tree-select#345]
**Describe the bug**
Since `componentWillMount` and `componentWillReceiveProps` are deprecated in react 16.13.0 if you modify the tree data the component mess up with items

**To Reproduce**
[link](https://codesandbox.io/s/react-dropdown-tree-select-11nty)

**Expected behavior**
No warning in the console

**Screenshots**

**Environment (please complete the following information):**
 - npm 6.7.0

**Comment by mrchief** [comment]
Duplicate of https://github.com/dowjones/react-dropdown-tree-select/issues/292
