### ISSUE TITLE
findIndex method can't support on IE browser

### ISSUE THREAD

**Issue by smurfs2549** [dowjones/react-dropdown-tree-select#347]
**Describe the bug**
findIndex() method issue can't support on internet explorer, I fixed it, but I can't push it to origin. How to create a new PR to fix it?

**To Reproduce**
key down 'Arrow down' key throw an findIndex issue

**Environment (please complete the following information):**
 - Browser [e.g. ie11]

**Comment by mrchief** [comment]
@smurfs2549 You can fork the project, create a branch, add your changes and then send a Pull Request. You can find more details here https://help.github.com/en/github/collaborating-with-issues-and-pull-requests

**Comment by mrchief** [comment]
Fixed by #348
