### ISSUE TITLE
Need showPartiallySelected tree with only one child to report the selected child not the parent

### ISSUE THREAD

**Issue by rbadapanda** [dowjones/react-dropdown-tree-select#349]
**Is your feature request related to a problem? Please describe.**
Sometimes it is required that the tree reports the leaf node rather than the parent node; need some dynamic mechanism to support this scenario.

**Describe the solution you'd like**

*Req#1:*
```
parent
└── child-lvl1
    └── child-lvl2
        └── child-lvl3
```

Parent uses order of magnitude more resources to process - think of it as a folder with lots of files - than child-lvl3; which is a sub-sub-sub folder with only a few files.

I am using showPartiallySelected flag; so when user selects the child-lvl3; the parent is automatically selected - as *all* its children are 'selected'

*Req#2*
When parent is selected we want the tree to show all its children checked/selected.

**Describe alternatives you've considered**
I thought of using the hierarchical=true but it breaks *Req#2* above.

**Additional context**

**Comment by mrchief** [comment]
> Sometimes it is required that the tree reports the leaf node rather than the parent node; need some dynamic mechanism to support this scenario.

Not sure I follow what your ask is here.

> I am using showPartiallySelected flag; so when user selects the child-lvl3; the parent is automatically selected - as all its children selected

With partial selection, parent is only partially selected. Due to [browser inconsistencies](https://css-tricks.com/indeterminate-checkboxes/), you may or may not see the partial state. 

> When parent is selected we want the tree to show all its children checked/selected.

This is the default behavior - when you click parent, all children get checked automatically.

**Comment by rbadapanda** [comment]
Thanks for your response.

Noticed that the markdown preview screwed up the indentation. Hence the question was not clear

I have updated the question. Can you please review the question?

**Comment by mrchief** [comment]
Still not a 100% sure but I think what you're looking for is `keepTreeOnSearch`. That would preserve the hierarchy while filtering so users can just select `parent` when needed instead of them selecting `child-xxx` and that cascading upwards. This will also not violate your 2nd requirement.
