### ISSUE TITLE
Is that possible to init search filter?

### ISSUE THREAD

**Issue by smurfs2549** [dowjones/react-dropdown-tree-select#351]
reproduce step: 
1. set a filter to tree
2. click a child node, set the data and re-render the tree
3. UX still filter mode, but the matched mode be cleared.
how to init the filter to make tree re-rendered the marched node?

**Comment by smurfs2549** [comment]
set a filter to tree
set parent state will change tree data and re-render the tree(this parent state is related with the tree, so I must re-render) the tree.
UX still filter mode, but the matched mode be cleared.
how to init the filter to make tree re-rendered the marched node?

**Comment by mrchief** [comment]
> set parent state will change tree data and re-render the tree(this parent state is related with the tree, so I must re-render) the tree.

Did you try the prevent-re-render-on-parent-render-hoc?

**Comment by smurfs2549** [comment]
I tried but not success.

**Comment by mrchief** [comment]
Can you create a codesandbox so I can take a look?

**Comment by smurfs2549** [comment]
I'll create a codesandbox to reproduce my request. But a bit complicated. I have use this package in our project. It's not easy to simulate existing situation.
