### ISSUE TITLE
Expand/Collapse not visible with default options and no stylesheet

### ISSUE THREAD

**Issue by aiyer-commits** [dowjones/react-dropdown-tree-select#353]
<img width="156" alt="Screen Shot 2020-04-01 at 11 08 54 AM" src="https://user-images.githubusercontent.com/56838551/78153598-3a4eec80-7409-11ea-9053-e1bcf78f2fb2.png">

Please see above image 

I am using the component with default values, but I cannot see the +/- expansion buttons. I am not including a style sheet. Is my node data malformed?

Thanks

**Comment by mrchief** [comment]
Are you bringing in the default stylesheet of the component?

**Comment by aiyer-commits** [comment]
No I am not, is that the index.css file? or is there another higher level file?

**Comment by mrchief** [comment]
Please read the docs! https://github.com/dowjones/react-dropdown-tree-select#styling-and-customization

**Comment by aiyer-commits** [comment]
<img width="304" alt="Screen Shot 2020-04-01 at 1 07 17 PM" src="https://user-images.githubusercontent.com/56838551/78165723-c2d58900-7419-11ea-9f5e-6c7740c38baa.png">
Awesome thanks for the guidance, I used the CDN link!

<img width="837" alt="Screen Shot 2020-04-01 at 1 08 07 PM" src="https://user-images.githubusercontent.com/56838551/78165831-e567a200-7419-11ea-855d-bacd176b9b85.png">
