### ISSUE TITLE
keep placeholder on focus on IE11

### ISSUE THREAD

**Issue by smurfs2549** [dowjones/react-dropdown-tree-select#354]
**search input placeholder disappear when focus on IE11**
Under WebKit and Firefox, the text in  input's placeholder sticks around on focus—it doesn't disappear until input.val actually has something in it.

Is there a good way to force IE11 to do the same thing?

**Comment by mrchief** [comment]
> Is there a good way to force IE11 to do the same thing?

Maybe ask IE 11 team? :)

Your research is as good as mine... :)

**Comment by smurfs2549** [comment]
https://stackoverflow.com/questions/14445891/keep-placeholder-on-focus-in-ie10
Many people be confused by this question. I'll try to ask them.
