### ISSUE TITLE
issue with useState

### ISSUE THREAD

**Issue by mrtornado** [dowjones/react-dropdown-tree-select#356]
So I have a regular DropdownTreeSelect and when I try to use the onChange prop with useState in it, the selectedNodes don't show as they should. 
 
 here is my onChange: 
 
```
 const onChange = (currentNode, selectedNodes) => {
		const loc = selectedNodes.map((x) => x.value).join(',');
                setLocations(loc)
		console.log(loc)
	};
```
  This is setting me only 1 location every time in the state, also the console.log shows only one value a time.  If I remove the `setLocations(loc)` everything is working as expected. 

 I've also tried with async await function: 

```
const onChange = async (currentNode, selectedNodes) => {
		const loc = await selectedNodes.map((x) => x.value).join(',');
		await setLocations(loc);
	};
```

 But this is messing up with the select menu, even it returns the right values sometimes :) 
 Please, help a noob out :) Thanks

**Comment by mrchief** [comment]
You're probably having the same issue as this [thread](https://github.com/dowjones/react-dropdown-tree-select/issues/313). If you can create a reproducible codesandbox, we cna look further.

**Comment by mrtornado** [comment]
The select is working properly as you can see in the next picture. It's adding all the values need for me to send to the database. 
<img width="1620" alt="Screen Shot 2020-04-13 at 23 40 42" src="https://user-images.githubusercontent.com/9127007/79159344-8eca7280-7de0-11ea-955b-89308163f460.png">

But once you uncomment the line setLocations() so I can have it in the state to send it to the database, it registering only the last select node. 
 
Don't know if it is the same issue, but I've created a codesandbox: 
https://codesandbox.io/s/ecstatic-turing-jjgrw?file=/src/App.js

**Comment by mrchief** [comment]
You have everything in one giant function and setLocation is setting state which would rerender everything. It's the same problem as the referenced thread. You can implement the same solution as mentioned in the thread (to prevent tree rerender) or break your app so that your whole doesn't get rerendered with every state change.

**Comment by mrtornado** [comment]
Manage to fix it by adding a Container as in this example https://dowjones.github.io/react-dropdown-tree-select/#/story/prevent-re-render-on-parent-render-hoc

 Thanks a lot for taking the time to answer. This HOC technique is good to know in the future :) I've learned something too 👍

**Comment by mrchief** [comment]
Glad to be of help!

**Comment by berdyshev** [comment]
Solution, suggested by mrtornado seems like a workaround but not a proper solution. Because, there is no way to use the component in a real form which handles its own state...

**Comment by RaedMou** [comment]
@mrtornado  How did use that solution in one big component and with react hooks , did you use useEffect ?

**Comment by mohdabbas** [comment]
@mrtornado Please kindly explain, how you solved this issue?? If you can share some code please!
