### ISSUE TITLE
Unable to select dropdown options when we  pass dynamic data coming from api  to DropdownTreeSelect . Where as if i call the same data from a json file functionality is working. 

### ISSUE THREAD

**Issue by ajaykiran123** [dowjones/react-dropdown-tree-select#357]
If you have a general query about the usage of react-dropdown-tree-select, or if you're not sure how to accomplish a particular task using the component; please raise a question on [stackoverflow.com](https://stackoverflow.com) with [react-dropdown-tree-select](https://stackoverflow.com/questions/tagged/react-dropdown-tree-select) tag.

If you think you found a bug or have a feature request, please use the `Bug Report`/`Feature request` template respectively.

**Comment by mrchief** [comment]
Please fill the issue template properly. If this is your first time creating an issue, you can refer to these guidelines to create a proper issue https://guides.github.com/features/issues/#intro

**Comment by berdyshev** [comment]
I guess this is duplicate of #356
