### ISSUE TITLE
Hello? Is there a way to remove search feature and the placeholder too?

### ISSUE THREAD

**Issue by SwikarBhattarai** [dowjones/react-dropdown-tree-select#359]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mrchief** [comment]
Search is needed because trees are inherently used for displaying lots of data. But if you don't want it, you can simply turn it off via css

```
.search {
  visibility: hidden;
}
```

Placeholder will get hidden if you hide the search but you can set it to blank or anything if you don't want to see it while search is visible.

**Comment by mrchief** [comment]
Gonna close this since this is not an issue. Happy to reopen if there's a real issue.
