### ISSUE TITLE
Is there a way to shorten checked labels? For eg. I have checked 1.1 Chemical Reaction, then i want to show only 1.1 as checked.

### ISSUE THREAD

**Issue by SwikarBhattarai** [dowjones/react-dropdown-tree-select#361]
If you have a general query about the usage of react-dropdown-tree-select, or if you're not sure how to accomplish a particular task using the component; please raise a question on [stackoverflow.com](https://stackoverflow.com) with [react-dropdown-tree-select](https://stackoverflow.com/questions/tagged/react-dropdown-tree-select) tag.

If you think you found a bug or have a feature request, please use the `Bug Report`/`Feature request` template respectively.

**Comment by mrchief** [comment]
Please don't put the issue description in the title. And please take time to fill up the issue template properly. 

You can refer to these guidelines to create a proper issue guides.github.com/features/issues/#intro
