### ISSUE TITLE
How do I remove selected value which appear as a tag and make it instead input value

### ISSUE THREAD

**Issue by habeebahmed** [dowjones/react-dropdown-tree-select#362]
**Is your feature request related to a problem? Please describe.**
When I select any node in a tree it should be like the second drop down is there any option to make it work like that..?
I want to remove tag from 1st drop down...
Thanks!
![image](https://user-images.githubusercontent.com/36078669/79716932-c57b1e00-82f5-11ea-8576-f9d61714a537.png)

**Comment by mrchief** [comment]
What happens if the user selects 2 values? Or if you're using it as a single select, then you can set `mode="simpleSelect"` and use CSS to remove the border and background color.

![image](https://user-images.githubusercontent.com/781818/79778249-72f62d80-8306-11ea-891a-c99bbf7c2e5d.png)

**Comment by habeebahmed** [comment]
If I go with simple search then I wont have tree structure
I want the functionality similar to [this](https://ant.design/components/tree-select/#header) the basic usage works
Thanks!

**Comment by mrchief** [comment]
I see. In that case, use `mode="radioSelect"` and rest is CSS.

**Comment by habeebahmed** [comment]
okay thanks!

**Comment by mrchief** [comment]
Closing this issue for now but happy to continue the discussion.
