### ISSUE TITLE
Sticky tree parent as long as childs are visible

### ISSUE THREAD

**Issue by moragamir** [dowjones/react-dropdown-tree-select#364]
Hello All,

Did anyone had a chance to build something similar to:
Whenever I expand a node I want him to stay sticky on scroll while its child elements are visible.
When childs are not visible anymore the parent will leave the view.

Here is a video example for one level of nesting:
https://streamable.com/pbshbv

I would like to preform this task in a tree with a max depth of 5.
Also should work on all browsers including IE 11 so sticky css attribute is not an option.
Any solution, suggestion will be welcome.

Thanks in advance.

**Comment by mrchief** [comment]
Pretty cool! To my knowledge, I don't think anyone has done it. Would be cool if this can be managed entirely via CSS though.
