### ISSUE TITLE
Filter lost onChange

### ISSUE THREAD

**Issue by aiyer-commits** [dowjones/react-dropdown-tree-select#365]
I am managing the state of a tree-select, so that I can send the selected options to a server.
When using a filter on the tree-select, the tree-select loses that filter when a selection is made.
What am I doing wrong?

**Comment by aiyer-commits** [comment]
further elaboration: I am using setState in onChange, on a tree structure that is used as the data prop of the tree-select. If this is the wrong way to keep track of selected nodes, please let me know

**Comment by aiyer-commits** [comment]
I managed a workaround for this issue by adding a searchValue variable to the tree-select's state, which is updated in onInputChange.  searchValue is checked in render, and if it is not the empty string, then data is set to treeManager.filterTree(...).tree, please let me know if this is a bad way to do this

**Comment by mrchief** [comment]
> I am using setState in onChange,

This is probably one of React's biggest pitfalls - this will re-render the whole thing again - which will reinitialize all your components. Use the https://dowjones.github.io/react-dropdown-tree-select/#/story/prevent-re-render-on-parent-render-hoc approach.

If you search closed issues, there's one example using react hooks too.
