### ISSUE TITLE
How to skip keyboard navigation for hide node of tree?

### ISSUE THREAD

**Issue by smurfs2549** [dowjones/react-dropdown-tree-select#366]
Is there a way can skip navigation for hide node of tree? Thanks!

https://codesandbox.io/s/naughty-pine-014m1

**Comment by mrchief** [comment]
Not possible currently. What's your use case?

**Comment by smurfs2549** [comment]
Now I need showPartiallySelected parent mark UI, But the parent and children value selecte is saparate, So I add a hide fake item.

**Comment by mrchief** [comment]
Sounds like you need `mode='hierarchical'` 

https://github.com/dowjones/react-dropdown-tree-select#hierarchical

**Comment by smurfs2549** [comment]
Thank you, but it can't usefull for my requirement.
Could you please merge PR [#367](https://github.com/dowjones/react-dropdown-tree-select/pull/367), This is very useful for me.
