### ISSUE TITLE
how to expand instead of select parent node when click on node title

### ISSUE THREAD

**Issue by lamvananh** [dowjones/react-dropdown-tree-select#369]
i'm using radioSelect mode to allow select only 1 node.
but i found no option to expand a parent node when click on it's title. Currently, it's always select node when click on.

**Comment by mrchief** [comment]
You can click on the plus icon to expand without selecting.

**Comment by johannesleander** [comment]
I was trying to achieve the same behavior, which sparked [this discussion](https://github.com/dowjones/react-dropdown-tree-select/issues/368). We're still trying to find a clean solution to this problem.

**Comment by mrchief** [comment]
> As a consideration for a UX improvement, being able to click the label of a node to expand it could make the interaction feel less "finicky" as the user doesn't have to click the small plus arrow.

@johannesleander, I hear you. However, the label is performing a different UI action - i.e. checking the checkbox. This is required for accessibility.

The plus/minus icon on the hand are purely for node expansion/collapse. 

Your use case is slightly different - this component is not a dropdown within dropdown solution, it is for showing complex tree data in a dropdown and letting users filter through those.

Introducing another "type" of node which acts as a toggle only node is going to introduce a lot of complexity and inconsistency in the behavior - something I don't see is a good idea.

I feel like this is something the hooks based version can achieve though, where you can bring your own UI to various parts of the component. Unfortunately, I haven't been able to spend much time on that so far.

**Comment by johannesleander** [comment]
Those are all fair points. Thanks for the swift response.

**Comment by lamvananh** [comment]
If it take too much time, can you create an option for preventing select parent node wen click on it's label?

**Comment by mrchief** [comment]
> If it take too much time, can you create an option for prevent selecting parent node wen click on it's label?

That's standard browser behavior.

**Comment by mcanet** [comment]
I am looking same. Basically I need to be able to open tree, but not select it (should be setup a property for this feature). For me seems quite standard feature.

**Comment by mcanet** [comment]
I think could be solve like this. Lets called that if gets a new property name { "expandOnly": true } then onclick not select and only expand,  and hide radio button or checkbox. 

I think could be done quite easy (src/tree-node/index.js , line 131):

`onCheckboxChange={!expandOnly ? onCheckboxChange : onNodeToggle}`

Then (src/tree-node/node-label.js , line 57 )

```
{!expandOnly ? (
          <span>
            {mode === 'radioSelect' ? (
              <RadioButton
                name={clientId}
                className="radio-item"
                onChange={this.handleCheckboxChange}
                {...sharedProps}
              />
            ) : (
              <Checkbox
                name={id}
                className={className}
                indeterminate={showPartiallySelected && partial}
                onChange={this.handleCheckboxChange}
                {...sharedProps}
              />
            )}
          </span>
        ) : null}
```

**Comment by mrchief** [comment]
I'm not convinced this is a good solution. It adds unwarranted complexity where none should exist, violates accessibility guidelines and in general is a misleading UX. Clicking on the toggle icon is not a big deal IMHO and keyboard navigation makes it easy to expand without clicking the labels. 

If you really want this behavior then I'd suggest to fork this project and make those changes.

**Comment by mcanet** [comment]
Thanks for your replay. My point is that I think it will be good to have an option that an item is not possible to select but not disable the hole branch of children. Even if the label will not work in these cases and only possible to expand with toggle icon,  in your suggestion parent node is still has a radio or checkbox and it is possible to be selected.  I think suggesting forking, in the long run, it is not a good idea.

**Comment by mrchief** [comment]
@mcanet I get your point. Thing is, if there wasn't a checkbox, this would have not been a debate at all. And creating another branched behavior imposes a cost - from many perspectives like I've already said. I'm trying to keep things simple and follow the web standards rather than have all these several permutations which allow non-standard behavior and increase the complexity of using the component as well as maintaining it. 

I suggested forking since these compromises may be acceptable to certain folks given their use case and their situation. It's not ideal for sure but this is a trade-off I'm willing to make.

**Comment by mcanet** [comment]
@mrchief For my current development project, i already forked and I modified the library code with all my needs and all it is working. Actually it has been very clear to understand the code and to modify it. You and all collaborators made a great job.

**Comment by mrchief** [comment]
I'm going to look more into this. There seems to be lot of interest on this feature. 

@lamvananh @mcanet @johannesleander in your use case, when you talk about `label click = node toggle`, do you also require the check/radio boxes to be present or are talking about purely a label only node?

**Comment by mcanet** [comment]
In my case the idea of "expandOnly" (or another name for this feature) was the only label and hide check/radio boxes.  Means one item/category that is purely organizational in the tree but that it cannot be selected.

**Comment by mrchief** [comment]
Ok, so seems like what it we want is a new node type - call it `nodeHeader` (probably a terrible name so please suggest alternatives). 

A `nodeHeader`:

 - Renders only a label (no check/radio)
 - Can be part of single select and multi select
 - Doesn't participate in any node/tree logic
 - Supports keyboard navigation - can be navigated to as all well responds to expand/collapse actions
 - Accessibility wise, let's screen reader know that this is not a selectable node.
 - `data.header: true` to mark it as such. Default `false`.

Thoughts?

**Comment by lamvananh** [comment]
In my use case, the requirement is only leaf node can be selected, all
parent node should only expand or collapse its children when click on, So i
think it will be the best if we can set an option in tree component. It's
name maybe preventSelectParent. All your description about node header is
correct except place option on each node instead of place it on tree
component.

Vào 4:49, Th 5, 28 thg 5, 2020 Hrusikesh Panda <notifications@github.com>
đã viết:

**Comment by mrchief** [comment]
@lamvananh A high level option works for **your** use case. There might be other use cases where it calls for different behavior. Having a property at the node level allows room for such flexibility. Maybe something like `node.labelOnly`? This would allow users to fully control which ones can be selected vs which ones are purely for display.

**Comment by kirit-ayya** [comment]
Has there been any progress on this feature?

**Comment by jjr52** [comment]
I came here because I was looking for a similar solution and found this question and another similar one. Both seem to offer either complex solutions or responses saying why would you do this.

My use case: I want to use the radioSelect mode to drill down through a hierarchy and allow selection of only one element. I assume the op had a similar requirement.

Simple Solution I found using current functionality: you can basically build what you want using:
1- mark the nodes you don't want as disabled (as you build the dropdown)
2- use css to make the <i> tag of disabled nodes as "position:absolute and width:100%". This results in clicking the title activating just the listener on the <i> tag.
3- you also need to hide the radio button with css.

my css for reference:
`.react-dropdown-tree-select li.node.disabled i {
	position: absolute;
    width: 100%;
    text-align: left;
}
.react-dropdown-tree-select li.node.disabled input[type="radio"] {
	visibility: hidden;
}`

**Comment by kevalbhatt** [comment]
This is my solution, while creating data send the disabled: true only for parent and add the class as well and change the color so it will not look disabled. 

Hope this will help others ✌️

```
const data = [{
        isParent,
        tagLabel,
        expanded,
        label: name,
        children: [] as any[],
        disabled: !!isParent,
        className: !!isParent ? "parent-node" : "child-node",
        fullPath: path
      }];

<DropdownTreeSelect data={data}  />
```

```
.react-dropdown-tree-select .node.disabled.parent-node > label {
  color: #5a5a5a;
}
```

**Comment by mrchief** [comment]
@kevalbhatt that's perfectly fine solution!

**Comment by danhhuynh** [comment]
.react-dropdown-tree-select .tree label{
    pointer-events: none;
}
this is my solution, try it if you're still stuck.
