### ISSUE TITLE
TypeError: n.props.onAction is not a function

### ISSUE THREAD

**Issue by kYem** [dowjones/react-dropdown-tree-select#380]
**Describe the bug**
onAction property is optional based on PropTypes and typescript types, however it's being called in the onClick handler, that assume onAction property is a function.

**To Reproduce**

Create data with nodes, that have actions array populated, 
click on the node with action.

Note it was working fine on original fork version of sandbox (lib v1.13.0)
CodeSandbox Link: https://codesandbox.io/s/react-dropdown-tree-select-bvlff?file=/index.js

**Expected behavior**
Clicking on the node, should not throw an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/3390897/84382386-70b39f80-abe2-11ea-8f29-7983d2849ea6.png)

**Environment*
 - Browser Chrome 83
 - OS: Linux

**Comment by mrchief** [comment]
Yes, it seems we're missing a `defaultProp` entry for `onAction`. Seems like a regression. I'll put out a fix or you can send a PR if you wish. 

Thanks for reporting this bug.

cc @all-contributors
