### ISSUE TITLE
Disabled node children visible on search  

### ISSUE THREAD

**Issue by SahilChaudhary25** [dowjones/react-dropdown-tree-select#381]
**Describe the bug**
Disabled node children visible on search  

**To Reproduce**
Please include steps to reproduce the behavior;
1. Create a  node with one children(say name="child") with disabled property.
2. Search with ch
3. Even though it is disabled it is being searched

**Expected behavior**
Disable node children should not be visible on search

**Comment by mrchief** [comment]
> Disable node children should not be visible on search

Well, that's business logic. This component stays away from making those decisions. Instead, it tries to enable you to make those decisions and act accordingly with ease. In this case, if that's what you want, you can easily hide them using CSS.

Closing this issue as this is not a bug but happy to continue the discussion.
