### ISSUE TITLE
Support for different texts for the dropdown and inline search input?

### ISSUE THREAD

**Issue by ldeveber** [dowjones/react-dropdown-tree-select#388]
**Is your feature request related to a problem? Please describe.**

Support for different texts for the dropdown and inline search input.

Wanted UX:
<img width="345" alt="Screen Shot 2020-06-30 at 9 40 45 AM" src="https://user-images.githubusercontent.com/4457752/86133094-d72b2f80-bab5-11ea-9ddc-4a44a188c5ff.png">

Implementation:
<img width="723" alt="Screen Shot 2020-06-30 at 9 40 36 AM" src="https://user-images.githubusercontent.com/4457752/86133123-e3af8800-bab5-11ea-9b21-7602ab4cba6b.png">

**Describe the solution you'd like**

```
const texts = {
      placeholder: 'Select...',  // optional: The text to display as placeholder on the dropdown box. Defaults to `Choose...`
      placeholderInlineSearch: 'Search...',  // optional: The text to display as placeholder on the inline search box. Only applies to `inlineSearchInput`. Defaults to `Search...`
      noMatches: 'nope',    // optional: The text to display when the search does not find results in the content list. Defaults to `No matches found`
      label: '',        // optional: Adds `aria-labelledby` to search input when input starts with `#`, adds `aria-label` to search input when label has value (not containing '#')
      labelRemove: '',  // optional: The text to display for `aria-label` on tag delete buttons which is combined with `aria-labelledby` pointing to the node label. Defaults to `Remove`
    }
```

**Describe alternatives you've considered**

**Additional context**

**Comment by mrchief** [comment]
I've been hesitant to let options explode and this feels like one of those cases. I can see your use case and I think it may help others in future. Would you like to send a PR?

**Comment by ldeveber** [comment]
> I've been hesitant to let options explode and this feels like one of those cases. I can see your use case and I think it may help others in future. Would you like to send a PR?

Hi! I didn't see this because I get thousands of github notifications a day. I can try!

**Comment by mrchief** [comment]
@ldeveber sounds great! Look forward to it.

**Comment by ldeveber** [comment]
> @ldeveber sounds great! Look forward to it.

whenever you are ready :)

**Comment by ldeveber** [comment]
> @ldeveber sounds great! Look forward to it.

https://github.com/dowjones/react-dropdown-tree-select/pull/404 is ready
