### ISSUE TITLE
Disable Automatic Scrolling on Selection

### ISSUE THREAD

**Issue by aigyptios** [dowjones/react-dropdown-tree-select#391]
I apologize in advance if this question has already been asked/request has already been made--I searched the issue tracker for anything like this and I was not able to find anything specifically targeting this issue, though it's related to #259 and #257 

**Is your feature request related to a problem? Please describe.**
I'm working on a project and we'd like to be able to disable the automatic centering of the most recently selected node. Right now, whenever we select a node, the scrollTop is set due to:
https://github.com/dowjones/react-dropdown-tree-select/blob/060a05acabd2f5598980b2c4b1ac73aab43202c3/src/tree/index.js#L59
and this makes it jump a bit, which we want to avoid.

**Describe the solution you'd like**
I'm not sure whether it's already possible, but is there a way to disable this? Perhaps by exposing a prop, if it doesn't clutter the API?

Thank you!

**Comment by mrchief** [comment]
Are you re-rendering on every selection?

**Comment by aigyptios** [comment]
Nope; we're not re-rendering the `<DropdownTreeSelect>` component from its parent.

**Comment by mrchief** [comment]
The line you referenced is from CWRP which means it's a re-render, so I was curious. I've not seen this jump behavior so was trying to see how to repro this. Will it be possible for you to create a sandbox or a gif with the issue?

**Comment by aigyptios** [comment]
I'm unable to create a sandbox or gif, but we noticed that it's happening here too: https://dowjones.github.io/react-dropdown-tree-select/#/story/large-tree

(We're also using a large number of nodes, though not as many as in the example there.)

**Comment by mrchief** [comment]
Yeah I see it. It's just there to optimistically load more items without having the user to scroll more. Also helps center the item to make it center of the attention sort of. But I also can see your point. I think it should be OK to not let it move. The tweaks would be around the lines you mentioned. 

I'm swamped at the moment so it could take a while to get the fix in. Or feel free to send a PR.

**Comment by aarce-uncharted** [comment]
Hi, we have similar issues and since it had been open for awhile, I put up a pr to address the issue.
