### ISSUE TITLE
Remove hidden toggle buttons

### ISSUE THREAD

**Issue by aigyptios** [dowjones/react-dropdown-tree-select#392]
**Is your feature request related to a problem? Please describe.**
We put rules for padding in our CSS in order to align the checkboxes and toggles between levels. However, the latest release has added invisible HTML elements which push the node labels too far to the right, based on the fix for #389.

**Describe the solution you'd like**
Ideally, padding and spacing ought to be set just with CSS (even programmatically as already is the case). I don't think it makes sense to clutter the DOM with invisible elements that are added JUST for the purpose of alignment. It seems like a hack. 

Would it be possible to revert that change? Unless I'm mistaken, I don't see any functional or semantic purpose in the invisible toggles. Perhaps the padding can be calculated from the visible functional toggle elements.

**Describe alternatives you've considered**
Right now, I'm thinking of adding the following rule to our CSS in order to remove the impact of the invisible elements.
```
.toggle[style="visibility: hidden;"] {
    display: none;
}
```

Thank you!

**Comment by mrchief** [comment]
> Ideally, padding and spacing ought to be set just with CSS (even programmatically as already is the case). I don't think it makes sense to clutter the DOM with invisible elements that are added JUST for the purpose of alignment. It seems like a hack.

It was done due to the fact that overriding inline styles is harder with just CSS. 

Can you share your CSS based solution?
