### ISSUE TITLE
`semantic-release` as dependency on NPM

### ISSUE THREAD

**Issue by mobilutz** [dowjones/react-dropdown-tree-select#396]
**Describe the bug**
An update from `2.3.3` to `2.3.5` brought again a huge increase of dependencies, which lead me to this:

On [NPM](https://www.npmjs.com/package/react-dropdown-tree-select?activeTab=dependencies) there is one additional dependency `semantic-release` which is [not part of the `package.json`](https://github.com/dowjones/react-dropdown-tree-select/blob/develop/package.json#L45-L48)

Could this please re resolved.

**To Reproduce**
1. Go to NPM https://www.npmjs.com/package/react-dropdown-tree-select?activeTab=dependencies
1. see `semantic-release` as dependency

**Expected behavior**
No `semantic-release` dependency

**Comment by mobilutz** [comment]
Ah, is it maybe related to this release github-action:
https://github.com/dowjones/react-dropdown-tree-select/blob/develop/.github/workflows/release.yml#L24-L26

And I stumbled over this:
https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-use-semantic-release-with-yarn

**Comment by mrchief** [comment]
You're right. `yarn add` adds it to `package.json` so `yarn add global` or `yarn add -D` should fix that. The convenience of `yarn add` biting us back here :)

**Comment by mrchief** [comment]
@mobilutz I went to https://www.npmjs.com/package/react-dropdown-tree-select?activeTab=dependencies and I don't know what you're talking about 😜 

![image](https://user-images.githubusercontent.com/781818/87478148-49902980-c5f7-11ea-8889-e1a1c614b9f5.png)

**Comment by mobilutz** [comment]
Our dependency PR diff also looks better now 😉 
<img width="1638" alt="Screenshot 2020-07-14 at 23 30 48" src="https://user-images.githubusercontent.com/491877/87478495-25017500-c62a-11ea-9e30-584d41308e6e.png">

Thanks again for the quick fix.
