### ISSUE TITLE
Radio button only for parent

### ISSUE THREAD

**Issue by SwethaSubra** [dowjones/react-dropdown-tree-select#399]
Is there a way to have radio button only for the parent nodes and checkbox for multiple selection in the child nodes? Currently when is mode is radioSelect, all the options become as radio button options.

**Comment by SwethaSubra** [comment]
Basically, the requirement is select only one parent option but within that selection can be multiple.

**Comment by mrchief** [comment]
Not possible currently. No one has had that requirement up until now :)

**Comment by SwethaSubra** [comment]
Thanks for the quick reply. Any workarounds which you can suggest? Like unselecting one parent and its children if another parent is selected.... on those lines. We really like all the features given of this control, this one requirement is posing us a challenge to implement :-)

**Comment by mrchief** [comment]
Yes, I can think of few ways to do this. Not sure if you use a state manager like redux or mobx but if you do, this becomes somewhat easier. The idea is to manage the business logic yourselves when selections change. E.g., 

say user user clicks on parent1 - you receive the nodeChange event and you update state
then the use selects parent2 - when you receive the nodeChange event, you can check if a parent is selected already. if so, unselect/remove that parent and select this one. Now, if you re-assign data to the component, it'll re-render with the new parent select selected and old one unselected.

The same logic can be extended to children selection. You can wrap this logic in a HoC and use that in your app.

**Comment by SwethaSubra** [comment]
Thanks a lot for the quick response. I will try this approach.

**Comment by SwethaSubra** [comment]
I was trying this approach today. Handled condition checks in the onChange method whenever a node is selected/unselected. Apart from unselecting other parents if one parent is selected, i also had to cover all the other scenarios as well. When a parent is selected, select all the children nodes, when one of the child node is unselected, unselect the parent node, when all children nodes are unselected, unselect the parent node etc etc. Basically i had to handle all scenarios of the  the select/unselect logic. Is this expected? In my data, i have checked property for each node.

**Comment by mrchief** [comment]
> When a parent is selected, select all the children nodes, when one of the child node is unselected, unselect the parent node, when all children nodes are unselected, unselect the parent node

These are scenarios that are handled by the component. E.g., if you assign data with parent node checked:true, the component will render with all children selected. However, since you're now juggling the radio button logic, you probably had to do more work.

It's not an optimal scenario and your edge case is a unique one. Trees are always tricky especially when you go few levels down. I don't have a better solution purely from the component side but if it's possible, maybe you can solve this via a different UX?

**Comment by SwethaSubra** [comment]
Sure. I will have a look at it again. Thanks for all the suggestions and help.
