### ISSUE TITLE
proptype issue

### ISSUE THREAD

**Issue by MajidDehnamaki** [dowjones/react-dropdown-tree-select#40]
hi
at the first better u know I'm new at the react
I use this but see this error 
`Calling PropTypes validators directly is not supported by the `prop-types` package.
Use PropTypes.checkPropTypes() to call them.`

**Comment by mrchief** [comment]
@MajidDehnamaki Where do you see the error? Are you sure its not coming from one of your own code? Can you provide some code (or a small repo that reproduces this error)?

**Comment by mrchief** [comment]
@MajidDehnamaki I would need a repo which reproduces this. 

I don't see that warning on my side when I run the tests or builds or any codesandbox examples.

**Comment by toofff** [comment]
Hello @mrchief,

I have the same problem with 'React' 16 and typescript.

**Comment by mrchief** [comment]
Can I see a repo to reproduce this?

**Comment by mrchief** [comment]
@MajidDehnamaki @toofff Is this what you're seeing?

![image](https://user-images.githubusercontent.com/781818/36037268-46918a76-0d8a-11e8-99b5-96abc072d666.png)

If so, this is not an issue coming from this component. It's emitted by `react-simple-dropdown` which this package depends on. That package hasn't been updated to use React 16 yet. However, this warning shouldn't affect anything runtime.

I do have a [branch](https://github.com/dowjones/react-dropdown-tree-select/tree/dropdown-replace) which eliminates this dependency but I haven't been able to test it thoroughly yet. If this warning bothers you, I would love to get some help on getting this branch tested and released.

**Comment by Gregcop1** [comment]
Oh nice. We were stucked with this @mrchief . Thanks for your hard work.
