### ISSUE TITLE
Hide the selected values on top of the dropdown

### ISSUE THREAD

**Issue by vjr12** [dowjones/react-dropdown-tree-select#400]
Is there a way we could hide the selected items on top of the dropdown once we select them? The one with selected item along with cross mark

**Comment by mrchief** [comment]
Hey, you can hide them using CSS. Closing this as it's not an issue but happy to continue the discussion.

**Comment by vjr12** [comment]
@mrchief thanks! Also wanted to ask , if I want to pass a custom to a particular item, How do I achieve that? From your docs it says using `actions`, Could you give an example?

**Comment by mrchief** [comment]
Do you mean the node items? There are examples of showing country flags, custom material ui/bootstrap icons in the docs. Actions are different - they show up to the right of node label and allow you to add custom logic to your node.

**Comment by vjr12** [comment]
@mrchief thanks again. In case I wanted to pass a font awesome  could I use like this `className: <FontAwesome name="rocket" />`?

**Comment by mrchief** [comment]
That's not a valid CSS class name. You're trying to pass a React element instead. Check out the bootstrap styles demo for FontAwesome usage:

```
.bootstrap-demo .toggle {
  font: normal normal normal 12px/1 FontAwesome;
  color: #555;
}

.bootstrap-demo .toggle.collapsed::after {
  content: "\f067";
}
```

**Comment by vjr12** [comment]
@mrchief thanks much man!

**Comment by TatianaRG** [comment]
@mrchief I need to add a Material UI Icon inside the .search and .toggle . How can I do this?
