### ISSUE TITLE
Unable to change the tagname

### ISSUE THREAD

**Issue by SwethaSubra** [dowjones/react-dropdown-tree-select#401]
I would like the change the display names of the tag(chips which display the nodes that are selected). We do not want to show all the child nodes selected and expand the dropdown's width, instead show like "Parent-3selected", "Parent-4selected" etc. Is there a way to achieve this? 
I saw couple of threads asking for such feature but not clear if it is implemented and available already.

**Comment by mrchief** [comment]
https://github.com/dowjones/react-dropdown-tree-select/pull/412 should be able to fix it.

**Comment by SwethaSubra** [comment]
Thanks a lot !
