### ISSUE TITLE
Dropdown arrow just like react-select

### ISSUE THREAD

**Issue by MisooB** [dowjones/react-dropdown-tree-select#403]
I am trying to change dropdown arrow to look exactly like react-select's component - https://react-select.com/ (exact same arrow with same divider) 
Does anyone know if it's possible? React-select sandbox: https://codesandbox.io/s/8qw3p?module=/example.js

In this image, on the left is **react-dropdown-tree-select** and on the right is **react-select**
![image](https://user-images.githubusercontent.com/24417984/88555306-ea370e00-d027-11ea-8833-d538e5a1c4d3.png)

Thanks in advance.

**Comment by mrchief** [comment]
I was able to tweak the material-ui [demo](https://dowjones.github.io/react-dropdown-tree-select/#/story/with-material-design-styles) a bit to get this 

![image](https://user-images.githubusercontent.com/781818/88581752-a3dbb200-d01b-11ea-95d7-442fc18297f5.png)

**Comment by mrchief** [comment]
Relevant CSS bits:

```
.react-dropdown-tree-select .dropdown .dropdown-trigger {
    font: normal normal normal 18px/1 "Material Icons";
    ...
}

.react-dropdown-tree-select .dropdown .dropdown-trigger.arrow.top:after {
    content: "\E5CF";
    border-left: solid 1px lightgray;
    padding-left: 4px;
    ...
```

**Comment by MisooB** [comment]
Thank you so much, kind sir. Your solution works. I am closing the issue now.
