### ISSUE TITLE
Why can't I change state inside function onChange?

### ISSUE THREAD

**Issue by herediasamuel** [dowjones/react-dropdown-tree-select#406]
I have this code:

 ```
const [ selectedTree, setSelectedTree] = useState([]);
  const onChangeSelectTree = (currentNode, selectedNodes) => {
   setSelectedTree(selectedNodes.map(function(item) {return item.label;}))

  }
```

below

```
return (
    <div>
       <div >
              <DropdownTreeSelect texts={{ placeholder: 'Seleccionar' }} data={treeSectors} onChange={onChangeSelectTree} onNodeToggle={onNodeToggle} onAction={onAction} className="mdl-demo" />
        </div> ...);
```

but when i call the function `setSelectedTree` my DropdownTreeSelect stop working

![image](https://user-images.githubusercontent.com/25045878/89106689-e6293880-d3f9-11ea-9cfb-0e62c93f24dc.png)

they are not selected when I click, please help me, thanks

**Comment by mrchief** [comment]
The tree maintains it's own selection, you don't have to do that work.

**Comment by parwiz-soluso** [comment]
Is it possible to keep the state of selectedNodes outside of the component?

**Comment by mrchief** [comment]
> Is it possible to keep the state of selectedNodes outside of the component?

Yes, absolutely. Let's say you have an app where redux manages the app state. You'd listen to `onNodeChange` and keep track of selected nodes. Now when you do that, you'd need to make sure that the component doesn't re-render when parent state changes (it's an unfortunate casualty of global state + React combo 😄 ). One way to do so would be to use [prevent-re-render-on-parent-render-hoc](https://dowjones.github.io/react-dropdown-tree-select/#/story/prevent-re-render-on-parent-render-hoc) approach.
