### ISSUE TITLE
Search input is not cleared on selection

### ISSUE THREAD

**Issue by berdyshev** [dowjones/react-dropdown-tree-select#409]
When using both `clearSearchOnChange` and `inlineSearchInput` options, the search input it not cleared inside the opened dropdown upon selecting one of the search results. This is a weird UX — I think the input should be cleared on selection too.

I found [this piece of code](https://github.com/dowjones/react-dropdown-tree-select/blob/develop/src/index.js#L93) which is not clear for me..

https://www.loom.com/share/ae3bef73fd7345b78468dd853955973c

**Comment by mrchief** [comment]
@berdyshev Thanks for the details! I agree about the UX expectation here. The line you pointed is a defensive check - inline search is part of the dropdown div, so unless the dropdown is visible, that ref will be null.
