### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by maaaaagda** [dowjones/react-dropdown-tree-select#419]
![image](https://user-images.githubusercontent.com/17687646/91024088-b8e63980-e5f7-11ea-9310-e01a9692e1ca.png)
This happens when results are filtered.  Looks that sometimes `this.state.tree` is undefined when passing it to <Tree .../> component as a `data` prop. It can be a bug in <TreeManager />.

**Comment by mrchief** [comment]
Are you able to reproduce this at will? If so, a codesandbox would be helpful. Also, could this be a browser specific issue?

**Comment by maaaaagda** [comment]
I am able to reproduce it every time. I also found workaround for it: passing prop clearSearchOnChange={true}. It happens in Chrome and in Firefox. I'll try to prepare codesandbox for it.

**Comment by maaaaagda** [comment]
Here you have it: https://codesandbox.io/s/priceless-boyd-xtjl3?file=/src/App.js. Steps to reproduce a bug in a fiddle.

**Comment by hyewon92cho** [comment]
I experienced a similar issue and happened mostly in Chrome. Is it possible to reopen and fix this issue?
Below is the stack trace of it.

StackTrace:
forEach (webpack://.../node_modules/react-dropdown-tree-select/dist/react-dropdown-tree-select.js:12:40275)
Le (webpack://.../node_modules/react-dropdown-tree-select/dist/react-dropdown-tree-select.js:12:40401)
Be (webpack://.../node_modules/react-dropdown-tree-select/dist/react-dropdown-tree-select.js:12:42474)
getNextFocus (webpack://.../node_modules/react-dropdown-tree-select/dist/react-dropdown-tree-select.js:12:42882)
handleFocusNavigationkey (webpack://.../node_modules/react-dropdown-tree-select/dist/react-dropdown-tree-select.js:12:47304)
handleNavigationKey (webpack://.../node_modules/react-dropdown-tree-select/dist/react-dropdown-tree-select.js:21:3209)
apply (webpack://.../node_modules/react-dom/cjs/react-dom.production.min.js:14:427)
apply (webpack://.../node_modules/react-dom/cjs/react-dom.production.min.js:15:117)
apply (webpack://.../node_modules/react-dom/cjs/react-dom.production.min.js:15:171)
d (webpack://.../node_modules/react-dom/cjs/react-dom.production.min.js:17:212)'
NotificationMessage: 'TypeError: Cannot read property 'forEach' of undefined'
Error: {}
