### ISSUE TITLE
Styles are missing for the component

### ISSUE THREAD

**Issue by sarada-Cheukupalli** [dowjones/react-dropdown-tree-select#42]
Hi 

I just installed this component and tried to run and noticed that it's missing a few styles. I don't see the arrow in select input and the expander symbols for opening and closing the data items. Also, only if I search for a keyword, it would expand the data items as shown in the screen-shots. Please advise!

Thanks!

![image](https://user-images.githubusercontent.com/10716099/35939765-fb4b4cde-0c01-11e8-935b-d35f554deb88.png)
![image](https://user-images.githubusercontent.com/10716099/35939901-5c3f7f92-0c02-11e8-9a65-4b4aa1703e64.png)

**Comment by aseroj** [comment]
what are you using for the templating ? (e.g. bootstrap, reactstrap, material)

**Comment by sarada-Cheukupalli** [comment]
I'm using the Vanilla (no framework)

**Comment by aseroj** [comment]
I'd suggest following the original [documentation](https://github.com/dowjones/react-dropdown-tree-select#i-do-not-want-the-default-styles-do-i-need-to-fork-the-project) for styling guides.
Also checkout the [examples](https://github.com/dowjones/react-dropdown-tree-select/tree/master/docs/examples) provided, although there aren't any for vanilla, but you'll get the gist of it.

**Comment by mrchief** [comment]
@sarada-Cheukupalli When you do

```js
import DropdownTreeSelect from 'react-dropdown-tree-select'
```

a bundler like webpack will also import the styles, provided you _allow_ for it:

```js
// allow webpack to import/bundle styles from node_modules for this component
module: {
  rules: [
    {
      test: /\.css$/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [{
          loader: 'css-loader'
        }]
      }),
      include: /node_modules[/\\]react-dropdown-tree-select/
    }
  ]
}
```
This will suffice to include vanilla/default styles.

If you want to use it with frameworks like Bootstrap/material, you'll also need to provide (in addition to allowing the default styles) some framework specific overrides with your own CSS. E.g. checkout the examples for [bootstrap](https://github.com/dowjones/react-dropdown-tree-select/blob/master/docs/examples/bootstrap/index.css#L29) and [material-design](https://github.com/dowjones/react-dropdown-tree-select/blob/master/docs/examples/material/index.css#L31).

The 3rd option, as pointed out by @aseroj, is to completely come up with your own style - and the documentation provides the CSS skeleton that you need to implement to do so.
