### ISSUE TITLE
Can you force the user to only select one element in the dropdown?

### ISSUE THREAD

**Issue by Jowen81** [dowjones/react-dropdown-tree-select#420]
I am trying to use the tree select to select a category. I only want to allow the user to select one element in the dropdown, but still want to show the hierarchy of the categories in the dropdown.

**Comment by mrchief** [comment]
Are you looking for radio select? It allows you select only one element while showing the hierarchy 

![image](https://user-images.githubusercontent.com/781818/91577967-7edaa780-e917-11ea-83dc-c16329212bb2.png)

**Comment by Jowen81** [comment]
awesome, that worked thanks. One more question, is there a way to disable parent categories from being selected?

**Comment by mrchief** [comment]
You can set the parent nodes to be readonly or hide the radio box altogether using css.
