### ISSUE TITLE
Show selected element in the field after it is selected?

### ISSUE THREAD

**Issue by Jowen81** [dowjones/react-dropdown-tree-select#422]
I used this tree select to select a category when adding a new asset. The categories are stored in separate table and is tied to the asset via a asset_category_id. I have it so that when I select a category or parent category then it assigns that category_id to the asset_category_id which is what I want. But it doesn't show the category selected so the user won't know that it has been selected.
This is my onChange method and how I am building my data to pass to the element and how I am passing it to it. Anyone have an idea on what I may be doing wrong and any suggestions to what I can try. Any help is appreciated, thanks.
![Capture](https://user-images.githubusercontent.com/9890069/92509680-de626e00-f1c7-11ea-851f-789fc6483c6d.PNG)
![Capture2](https://user-images.githubusercontent.com/9890069/92509690-e28e8b80-f1c7-11ea-8b9f-c693804ff39f.PNG)
![Capture3](https://user-images.githubusercontent.com/9890069/92509695-e4f0e580-f1c7-11ea-8c6a-c0ab93d54404.PNG)

**Comment by mrchief** [comment]
You're probably looking for https://dowjones.github.io/react-dropdown-tree-select/#/story/prevent-re-render-on-parent-render-hoc
