### ISSUE TITLE
How to enable checkbox selection only at the leaf nodes ?

### ISSUE THREAD

**Issue by sanjeeviraj** [dowjones/react-dropdown-tree-select#423]
I have a requirement to select only the leaf nodes of a expansion category, can it be achieved in react-dropdown-tree-select ? the docs have checkbox selection event at the top - level.

**Comment by mrchief** [comment]
You can do this by disabling the nodes that you don't want selected. It has been discussed multiple times and if you search through old issues, you can find several examples. Closing this as it is not an issue but happy to continue the discussion.
