### ISSUE TITLE
How can I implement lazy loading on item selection?

### ISSUE THREAD

**Issue by devspectre** [dowjones/react-dropdown-tree-select#426]
**How can I implement lazy loading on item selection?**
Literally, I'd like to load child items when the parent item is expanded, not from the beginning.
When we deal with huge amount of data and want to use react-dropdown-tree-select, lazy loading can improve performance.
Thus it might be very useful.

**Comment by mrchief** [comment]
Have you looked at https://github.com/dowjones/react-dropdown-tree-select/issues/36?

**Comment by devspectre** [comment]
Let me check it
