### ISSUE TITLE
Selected values disappear after the state change The values should remain selected

### ISSUE THREAD

**Issue by sangpal** [dowjones/react-dropdown-tree-select#428]
When i select node from dropdown api gets called and in the success state change occurs after state change selected values in tree select disappear The values should remain selected

**Comment by mrchief** [comment]
You're probably re-rendering the component on state change which is the most common React pitfall. If not, please open a CodeSandbox and we can dig deeper.

**Comment by sangpal** [comment]
How can we set the values to tree programatically?

**Comment by mrchief** [comment]
Yes, please look at the readme for `data` prop and it's structure. Closing this as it's not an issue.
