### ISSUE TITLE
In most of the demo examples, outline of the expand and collapse icon is not properly styled.

### ISSUE THREAD

**Issue by PranjaliPatil14** [dowjones/react-dropdown-tree-select#430]
**Describe the bug**
In the demo examples, given in the documentation, on focus of  + or - or ^ icon outline is added to it. This outline is added very close to icon that sometimes the icon is not properly visible. In **Using Material Design with React Dropdown Tree Select** example the icon is almost outside of the outline. i.e the icon is not positioned properly inside it's parent.

**To Reproduce**
1. Go to: https://dowjones.github.io/react-dropdown-tree-select/#/story/with-material-design-styles
click of expand icon. Refer to first image.
2. Go to: https://dowjones.github.io/react-dropdown-tree-select/#/story/with-country-flags. The outline is very close to the + and - icon. Refer 2nd image.

**Expected behavior**
There should be proper padding to icons. In material example the icon position should be positioned outside i tag.

**Screenshots**
![image](https://user-images.githubusercontent.com/31987627/94763177-38211700-03c7-11eb-9d3f-5d2c538488fd.png)

![image](https://user-images.githubusercontent.com/31987627/94763302-83d3c080-03c7-11eb-8c8a-c3fc831e68e9.png)

**Environment (please complete the following information):**
 - Browser, Chrome: 85.0
 - OS: macOs

**Comment by mrchief** [comment]
@PranjaliPatil14 those examples are supposed to be a pointer - not production ready code. I'll gladly accept a PR fixing those CSS issues in the examples.
