### ISSUE TITLE
showPartiallySelected is failing in 4 level

### ISSUE THREAD

**Issue by erikradisch** [dowjones/react-dropdown-tree-select#436]
If a tree is deeper then 3 levels, a drop-down-tree-select-nodule with showPartiallySelected stops to work correctly. If the item of the 4. level or deeper is selected, the item of the two or three levels above is selected. 
![grafik](https://user-images.githubusercontent.com/34335811/96178231-5e9a9280-0f2f-11eb-8abe-af41628af3bb.png)

I am not entirely shure, but I think the problem is here:
https://github.com/dowjones/react-dropdown-tree-select/blob/3db87c975f40107160c44b7bc5808bc72d648e89/src/tree-manager/index.js#L255

It might be enogh to include a check if tree is showPartiallySelected?

**Comment by mrchief** [comment]
> It might be enogh to include a check if tree is showPartiallySelected?

I think the `hierarchical` check is supposed to do just that but it seems like you found a corner case where the parent only has one item.
