### ISSUE TITLE
Pass "id" of DropDownTreeSelect component to onChange event

### ISSUE THREAD

**Issue by mfrey777** [dowjones/react-dropdown-tree-select#438]
I am using multiple DropDownTreeSelect components on a page to perform different selections for a database query.

I woiuld like then to use one single onChange method (instead of one onChange per tree component) to store the selection in my state.

For that to work, I would need to have one extra parameter in the onChange method that would pass the "id" of the component like in the following example:

onChange = (currentNode: any, selectedNodes: any, id: string): void => {
    const selection = this.state.selection;
    selection[id] = currentNode['id'];
    this.setState({ selection: selection });

**Comment by mrchief** [comment]
Hi! You can do that with composition currently. Say you have `dd1`, `dd2`, `dd3` dropdowns. Then you can register your handlers like this:

```
<DropdownTreeSelect id=dd1 onChange=onChange1 />
<DropdownTreeSelect id=dd2 onChange=onChange2 />
<DropdownTreeSelect id=dd3 onChange=onChange3 />

const onChange1 = (currentNode, selectedNodes) => globalOnChange(currentNode, selectedNodes, 1)
const onChange2 = (currentNode, selectedNodes) => globalOnChange(currentNode, selectedNodes, 2)
const onChange3 = (currentNode, selectedNodes) => globalOnChange(currentNode, selectedNodes, 3)

const globalOnChange = (currentNode, selectedNodes, id) => {...}
```

You can of course optimize this in many ways like loops or maps to create and register those handlers or even create an HoC that takes the global handler and then bubbles up component onChange plus id.
