### ISSUE TITLE
onChange event not firing when click on a filtered list item

### ISSUE THREAD

**Issue by m-escott** [dowjones/react-dropdown-tree-select#442]
I have a DropdownTreeSelect component defined in the following manner:

<DropdownTreeSelect
    data={menuData} //an array of objects with properties index and name
    onChange={this.onChange}
    mode="simpleSelect"
/>

After typing characters in the component to cause a filtered list of items to appear, clicking on a filtered item from the resulting list does not fire the component's onChange event if the item is past the 100th position in the menuData array.

The menuData array contains over 1500 items but the behavior is the same even when I populate the menuData array with slightly over 100 items.

If I directly scroll to the same item when I don't type in any characters to result in a filtered list then clicking on the item does fire the onChange event.

There are instances where I have used DropdownTreeSelect with way over 100 items and the issue does not occur.

Any thoughts on why this is happening and how I might remedy the problem so that onChange will get always fired when clicking a list item?

**Comment by mrchief** [comment]
Seems like a bug. Can you please put together a CodeSandbox reproducing this issue?

**Comment by m-escott** [comment]
For starters, I was trying to see whether anyone else has seen this behavior.  I appreciate that it will be harder for you to investigate without seeing a CodeSandbox example.   I don't have the availability to put that together now but will let you know if I do.
