### ISSUE TITLE
Any logic in handleChange is 

### ISSUE THREAD

**Issue by RaedMou** [dowjones/react-dropdown-tree-select#445]
**Describe the bug**
I just want to save the selected nodes in a new state using hook component : 

`
  const handleChange = ({ value, checked, type }, selectedNodes) => {
    if (value === "selectAll") {
      if (checked) setSelectedBooks(["All"]) 
      else setSelectedBooks([]) 
      toggleAll(checked);
    } 

    if (type === "book" && checked) setSelectedBooks(state => [...state, value])
    if (type === "book" && !checked) setSelectedBooks(selectedBooks.filter(item => item !== value))

    console.log("Selected : ", selectedNodes)

  };`

**To Reproduce**

Now the "selectedNodes" is only one value and doesn't save other selections , only stores the last one.

Is there a way to add my logic in handleChange ?

**Comment by RaedMou** [comment]
Is there a way to implement this : https://dowjones.github.io/react-dropdown-tree-select/#/story/prevent-re-render-on-parent-render-hoc

using hooks and useEffect ? (all the code in one component)

**Comment by RaedMou** [comment]
Same problem here : https://github.com/dowjones/react-dropdown-tree-select/issues/356

**Comment by mrchief** [comment]
> Is there a way to implement this : dowjones.github.io/react-dropdown-tree-select/#/story/prevent-re-render-on-parent-render-hoc

> using hooks and useEffect ? (all the code in one component)

Yeah, see this [CodeSandbox](https://codesandbox.io/s/aged-field-uxkrf?fontsize=14&hidenavigation=1&theme=dark). There's an [open issue](https://github.com/dowjones/react-dropdown-tree-select/issues/320) to add this to docs. PRs welcome!

**Comment by dustinmoore** [comment]
@mrchief Looking at the [CodeSandbox](https://codesandbox.io/s/aged-field-uxkrf?fontsize=14&hidenavigation=1&theme=dark) you linked it doesn't appear to work the way I would expect. I noticed that in data that label: "VP Accounting", has checked: true but when the dropdown renders it is not checked. I'm having this same issue and I'm not sure what would correct that issue.

**Comment by mrchief** [comment]
That's a special case so shouldn't be used as a general guide. There's logic in `data.adapter.js` that overrides the data 
![image](https://user-images.githubusercontent.com/781818/149564401-c38bc629-8d1b-4b0b-b2a0-4162bef01888.png)
