### ISSUE TITLE
Dropdown not always closing as expected

### ISSUE THREAD

**Issue by bjonen** [dowjones/react-dropdown-tree-select#449]
**Describe the bug**
There are two scenarios where the dropdown is not closing as expected: 
1) Mouse click to the right of the input (same level). All other areas work. 
2) Hitting Esc after selecting an element in the tree. When cursor is in the search bar Esc works. 

**To Reproduce**
Tested on both chrome and firefox for the following URL
https://dowjones.github.io/react-dropdown-tree-select/#/story/basic-no-extra-styles

**Expected behavior**
The dropdown should close. 

**Environment (please complete the following information):**
 - Version 86.0.4240.198 (Official Build) (x86_64)
 - OSX

**Comment by mrchief** [comment]
Hey, thanks for reporting this.

Regarding the first, the current logic is to close the dropdown when an outside click is detected. The basic example has a wide control as you can see here 

![image](https://user-images.githubusercontent.com/781818/101294608-94008580-37e6-11eb-8abd-55d4fa4e8b59.png)

If you're to override this using your own css, then same level would work

![image](https://user-images.githubusercontent.com/781818/101294636-cad69b80-37e6-11eb-9830-766bfd29e8fb.png)

> Hitting Esc after selecting an element in the tree. When cursor is in the search bar Esc works.

I guess we need to add keyboard logic for this. Care to send a PR?

**Comment by bjonen** [comment]
Thanks for the fast reply! 

Ah yes, 1) is indeed simply a CSS issue and can be fixed by reducing the width of #rdts1. 
Regarding 2) let's see if I find some time during the holidays.
