### ISSUE TITLE
Move Search input to Dropdown

### ISSUE THREAD

**Issue by vova42matters** [dowjones/react-dropdown-tree-select#457]
**Is your feature request related to a problem? Please describe.**
I need a bit different design implemented

**Describe the solution you'd like**
 It would be much better if `react-dropdown-tree-select` could add a prop where you set the input location to dropdown
 
**Describe alternatives you've considered**
For now I'm setting styles so input would be inside dropdown, it would be much easier if input was already in dropdown

**Additional context**
[Example](https://github.com/harshzalavadiya/react-multi-select-component/blob/HEAD/preview.gif)

**Comment by mrchief** [comment]
It's already supported https://github.com/dowjones/react-dropdown-tree-select#inlinesearchinput
