### ISSUE TITLE
how do i pass data in the component with children?

### ISSUE THREAD

**Issue by Nike682631** [dowjones/react-dropdown-tree-select#465]
When I am passing data to the dropdown component it is rendering it but without child nodes.
```javascript
const data = {
        label: 'search me',
        value: 'searchme',
        children:[
          {
            label: 'search me too',
            value: 'searchmetoo',
            children: [
              {
                label: 'No one can get me',
                value: 'anonymous',
              },
            ],
          },{
            label: 'search me too',
            value: 'searchmetoo',
            children: [
              {
                label: 'No one can get me',
                value: 'anonymous',
              },
            ],
          },
        ],
      }
      const onChange = (currentNode, selectedNodes) => {
        console.log('onChange::', currentNode, selectedNodes)
      }
      const onAction = (node, action) => {
        console.log('onAction::', action, node)
      }
      const onNodeToggle = currentNode => {
        console.log('onNodeToggle::', currentNode)
      }
      
    return (
        <div className="container">
            <div className="row justify-content-center">
                <div className="col-md-8">
                    
                    <DropdownTreeSelect data={data} onChange={onChange} onAction={onAction} onNodeToggle={onNodeToggle} />
                  
                </div>
            </div>
        </div>
    );
```

**Comment by Nike682631** [comment]
Would be happy to screenshare if someone is interested

**Comment by mrchief** [comment]
Would you be able to create a reproducible example? Something on https://codesandbox.io/ or similar?

**Comment by Nike682631** [comment]
> Would you be able to create a reproducible example? Something on https://codesandbox.io/ or similar?

I am doing this in a project so it might not be possible to do that quickly. Would it be possible for you to participate in a screenshare?

**Comment by Nike682631** [comment]
Also if that helps what is happening is that i have children array in the data that i am passing to the component but in onchange i get children : undefined and _children : array(some number) so i don't know what is converting children to _children in my data.

**Comment by mrchief** [comment]
`onChange` gives you `current` and `selectedNodes` 

```
function onChange(currentNode, selectedNodes) {
  // currentNode: { label, value, children, expanded, checked, className, ...extraProps }
  // selectedNodes: [{ label, value, children, expanded, checked, className, ...extraProps }]
}
```

> so i don't know what is converting children to _children in my data.

The component flattens hierarchical data and that's what you have in `_children`. It's an internal structure and you shouldn't be relying on it.

If you need to keep track of changes on your end (say in a global state), then you'd need to:

 - listen to events
 - update you own state based on received node info

**Comment by Nike682631** [comment]
> `onChange` gives you `current` and `selectedNodes`
> 
> ```
> function onChange(currentNode, selectedNodes) {
>   // currentNode: { label, value, children, expanded, checked, className, ...extraProps }
>   // selectedNodes: [{ label, value, children, expanded, checked, className, ...extraProps }]
> }
> ```
> 
> > so i don't know what is converting children to _children in my data.
> 
> The component flattens hierarchical data and that's what you have in `_children`. It's an internal structure and you shouldn't be relying on it.
> 
> If you need to keep track of changes on your end (say in a global state), then you'd need to:
> 
> * listen to events
> * update you own state based on received node info

yes i understand the keeping track of changes on my end part. But what i am saying is that in my project the component is receiving hierarchical data but it is not rendering it in that manner. Instead it is only rendering the topmost layer and i am not seeing an option to expand the nodes using +.

**Comment by mrchief** [comment]
@Nike682631 seems like something on the page is interfering. Without a reproducible example, it's hard to debug further. Some general tips would be to remove all css/JS on the page and have only the dropdown - see if that works. If so, you know that the stuff you removed is the culprit. Start adding them back one by one to see which one breaks it.

Closing this as it is not an issue on the component side but happy to keep the discussion going.
