### ISSUE TITLE
Issues with saving and viewing the selected nodes

### ISSUE THREAD

**Issue by aishwarya2392** [dowjones/react-dropdown-tree-select#468]
I'm trying to use the dropdown tree select in my application for displaying single select tree dropdown, so im using "radioSelect" mode. Im trying to save the selected node in my parent state and display it during edit. I m able to select and display it without any issues, but while clearing out the selected value, I get issues like "Cannot set property checked of undefined".
If i remove my onChange, there is no issue with select/remove but it does not save in my parent state, thats an issue for me because i want it to display it in my form during edit.

**Comment by mrchief** [comment]
Closing this in favor of https://github.com/dowjones/react-dropdown-tree-select/discussions/452#discussioncomment-466694
