### ISSUE TITLE
question: exclude level from available selection

### ISSUE THREAD

**Issue by Gregcop1** [dowjones/react-dropdown-tree-select#47]
Hi, for our project, we need to disallow selection on specific level. I think I can to this by wrapping `DropdownTreeSelect` with a custom component which will catch selection and do the job. I don't know if you want to enable this kind of behaviour in your plugin. If so, I can make a pull request to build this natively instead of using an wrapping component.

**Comment by mrchief** [comment]
That's an interesting use case. 

On one hand, I think it'd be nice to have a node level prop that disables the node (and may be its children too? I'm thinking similar to `node.checked`...). On the other hand, I'd like to keep the core plugin simple and light. 

Would you mind sharing some further details about how you plan to implement this (HOC and/or natively)?

**Comment by Gregcop1** [comment]
Our needs is to disable selection for specific level. For example, it's not possible to select first and second level.
With a HOC, I think I can use `onChange` event to catch selection and stop propagation or revert the change (I have watch yet if you fire event before or after change)
Natively, it could be more powerful cause we can remove checkbox for those levels and not firing the `onChange` event at all.
I start dev on our project (with a HOC), keep me inform if you want me to include this in the lib.

**Comment by Gregcop1** [comment]
I tried with an HOC, I can prevent tag creation and revert the click for the selected level but not for it's children :/

**Comment by mrchief** [comment]
Yeah it gets messy with an HOC. 

Looking at your PR, and this discussion, I think the interface should be like this:

 - Introduce a new property at the node level - say `disabled`?
 - If a node is `disabled`, disable the checkbox and emit `disabled` classname.

This has the following benefits:

 - Keeps it generic enough for single root and multi root trees.
 - Allows you to have greater flexibility in disabling nodes (goes beyond levels).
 - Emitting the class lets you customize the presentational aspect - one can choose to hide or show differently based on their specific business needs.

Thoughts?

**Comment by mrchief** [comment]
You're welcome to take a stab at it (your PR is close enough already) or else I can get to it in few days.

**Comment by Gregcop1** [comment]
Ok, I will work on it soon.

**Comment by benwiggins** [comment]
I've been using some pretty hacky CSS child selectors to achieve something similar by setting `pointer-events: none` on labels and `display:none` on checkboxes. Looking forward to an 'official' disabled class :)

**Comment by Gregcop1** [comment]
You can check progress on #50

**Comment by mrchief** [comment]
This is available with v1.4.0
