### ISSUE TITLE
when searching a tree, only the parent of child results show (only when app is hosted)

### ISSUE THREAD

**Issue by yarinsn** [dowjones/react-dropdown-tree-select#472]
**Describe the bug**
when using the search feature, only the parent of the matching node appears (the 'HainesAttract' node has a child called 'Technology', see next screenshot)
![image](https://user-images.githubusercontent.com/5437072/111717032-258a9380-88bc-11eb-95d3-c0acdc296dd8.png)

However, when the app is running locally on my machine, everything works as expected - I type 'tech' and the relevant child node 'Technology' (and it's children) appear.
![image](https://user-images.githubusercontent.com/5437072/111716912-dfcdcb00-88bb-11eb-8893-bb9fc2954f19.png)

**To Reproduce**
the issue occurs only on a hosted environment. 

**Expected behavior**
see above.

**Screenshots**
see above.

**Environment (please complete the following information):**
 - Browser: 89.0.4389.82 (Official Build) (64-bit)
 - OS: Local: Windows x64, Hosted: Azure Hosted App (Unix 4.15.0.112)
 - node version: 12.16

**Additional context**
using react-dropdown-tree-select version 2.5.1.
It might be that the info I provided is not enough, but I'm not quite sure what to look into at this point, so any questions/requests for further into are welcome.

**Comment by mrchief** [comment]
Something tells me the issue is with the hosted environment :) 

Happy to continue the discussion but I don't think this is a bug with the component.

**Comment by yarinsn** [comment]
Hey, thanks for the reply. How can we continue the discussion?
