### ISSUE TITLE
Parent node selection should only select filtered/shown children

### ISSUE THREAD

**Issue by jamescanady** [dowjones/react-dropdown-tree-select#476]
**Describe the bug**
Searching the tree while using the keepTreeOnSearch option set to true allows the user to select a parent node, while in this state the filtered nodes are selected as expected however the hidden children which didn't match the predicate are also selected.

**To Reproduce**
With a hierarchical tree of Sites/Groups/Users,
Filter by a predicate, example "B" shows all users where "B" is present.
Click on the Parent node.
Observe that the UI reflects the filtered children as being selected.

**Expected behavior**
Only filtered users should be selected.

**Actual behavior**
All items under the parent are selected regardless of the filter predicated if they are shown/hidden.

**Screenshots**

**Environment (please complete the following information):**
 - Browser [e.g. chrome v60.12.0, safari 10.1] chome/firefox
 - OS: [e.g. iOS, Windows x64] (if applicable) n/a
 - node version (if applicable)
 - yarn or npm version (if applicable)

**Comment by mrchief** [comment]
Yeah so parent selection always selects all children but you want only those visible to be selected. I've mixed feelings about this. On one hand I can see the use case for it and on the other hand I see the complexity this would add. Also, if we introduce this behavior, it'd be a deviation from current behavior so to keep backward complexity, we'd need to gate it behind a prop which then brings up the "too many props" problem. 

I'll think on it but would love to hear any ideas you may have to solve this without increasing the complexity too much.
