### ISSUE TITLE
searchPredicate does not update searchTerm when there is no matching element

### ISSUE THREAD

**Issue by DryJhin** [dowjones/react-dropdown-tree-select#477]
**Describe the bug**
When using **searchPredicate** the **searchTerm** does **not get updated** after there are **no more matches in the tree**. Note write the word, wait few seconds, and write more than 2 letters. Sometimes is adding the first letter after you are writing the first word. If you delete letters the searchPredicate is triggered as expected. **The problem is just at adding letters after there are no more matches.** You can see in screenshots in the console.

**To Reproduce**
https://codesandbox.io/s/react-dropdown-tree-select-searchpredicate-issue-2hwh4?file=/index.js

**Expected behavior**
If I fill up the search with any word that does not matches any option in tree to trigger searchPredicate for all searchTerms.

**Screenshots**
![image](https://user-images.githubusercontent.com/47484584/112547567-96054900-8dc3-11eb-893b-77356aacfc34.png)
![image](https://user-images.githubusercontent.com/47484584/112547781-e381b600-8dc3-11eb-8f83-6da219a90546.png)

**Environment (please complete the following information):**
 - Any browser
 - All versions

**Additional context**
I need the search term updated at any time in order to allow user to add it in the list if he wants so with a custom button The add function would be an improvement that you might consider in the future, so we will not need to create custom logic for this.

**Comment by mrchief** [comment]
Apologies for the delay but I wanted to ensure I fully understand your issue. Thanks for the detailed report.

To summarize, you're talking about 3 issues:

 - search string is always lowercased
 - when no matching terms, search predicate should something else than what it's doing currently
 - add an ability to create an item if a match is not found

Correct? 

If so, here's my responses in order:

 - The default search is case insensitive so it is lowercased - both the term and the node label. If you do not want this behavior, you can pass your own predicate that respects case sensitivity. Here's an [example](https://github.com/dowjones/react-dropdown-tree-select/blob/develop/src/tree-manager/tests/index.test.js#L487)
 - I'm not a 100% sure I follow what you're asking here. The search is always linear an contiguous - so if you search for "VP Accounting" and not select the entry and keep typing, then it'll continue searching. What do you think is missing here and how should it behave instead?
 - There was a similar request for this in the past and I noted my response in there if you don't mind looking for that issue.

**Comment by DryJhin** [comment]
I just copied the example from someone else. The problem is just with matching terms.

I'm not a 100% sure I follow what you're asking here. The search is always linear an contiguous - so if you search for "VP Accounting" and not select the entry and keep typing, then it'll continue searching. What do you think is missing here and how should it behave instead? -> Maybe is searching I do not say it does not, but the callback is not happening on searchPredicate till a new match is found so you do not have access to the new search term. 

Meanwhile I found another solution to get the searchinput with DOM manipulation without searchPredicate so for me this is not longer needed, but asking if this was just an improvment to not make so many callbacks.

**Comment by mrchief** [comment]
@DryJhin I'm not sure I follow. Your statements seem to contradict each other. Are you saying it should call searchPredicate if a match is not found?

**Comment by DryJhin** [comment]
Sorry for the late reply @mrchief ,

I even forget the whole context, but for sure the idea was that searchPredicate is not called all the time, just when a match is found... And if you wanted to add a new value in the tree then you would not be able with the searchPredicate which should be the logic implementation based on the callbacks provided.

The best solution is to be added as a future in the upcoming releases...
