### ISSUE TITLE
When all children node is selected. Show only the parent's tag

### ISSUE THREAD

**Issue by HHuuxx** [dowjones/react-dropdown-tree-select#481]
Hi, I have a general inquiry about the functionality of the component.

There is a way where when you select the node that has children and it will automatically select all children node of that node that you have selected and it will show the parent node value as a tag on tag-list and if you unselect a children node then it will unselect the parent node  and that leaves the remaining children nodes excluding the children node that you have unselected. This will show all selected children node on the tag list. 

What i am trying to do is when all children node is selected on by one, the tags of each children node's value will be changed to the parent's node value. Is there a way to do that?

**Comment by mrchief** [comment]
If you select parent -> parent shows
If you select all children -> all children shows

This was a deliberate design decision to allow for maximum flexibility for different use cases. Depending on requirements, you may want to store one (parent) or all (children) values and this design allows for both cases. In cases where you may want to display one thing when another happens, that can be accomplished with an HoC where the HoC, upon seeing that all children are selected, replaces the `data` with `parent.selected = true` and `foreach(children) -> selected = false`. Bit inconvenient but business decisions like this are better left to user land than component land.

**Comment by HHuuxx** [comment]
Thank you for the reply,  You have helped me achieved the thing i've been trying to figure out for days now. Kudos to the awesome plugin and to the contributors of this plugin.

**Comment by bimix** [comment]
I need to do exactly the opposite. When the parent node is checked, I want all children tags to appear (not the parent tag).
