### ISSUE TITLE
React 17 support 

### ISSUE THREAD

**Issue by paycorchauhan** [dowjones/react-dropdown-tree-select#486]
Hello All ,

Thanks for your work. Wanted to check due to [breaking changes in peerdependencies with npm7 ](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies) are there any plans to support React 17 .

Thank you.

**Comment by mrchief** [comment]
@paycorchauhan absolutely! Would you care to send a PR?

**Comment by paycorchauhan** [comment]
@mrchief  I opened the PR, please review when can. For some reason am unable to add you as a reviewer on the PR.
