### ISSUE TITLE
Not able to scroll down far enough - continued

### ISSUE THREAD

**Issue by ttomaszewski** [dowjones/react-dropdown-tree-select#493]
**Describe the bug**
New issue for https://github.com/dowjones/react-dropdown-tree-select/issues/207
Adding `overflow-y: auto;` to the CSS did not resolve our issue. Still not able to see all options with scroll. User is forced to search to display the hidden options. 

**Expected behavior**
All options are visible with scroll.

**Comment by mrchief** [comment]
Can you create a reproducible codesandbox? The main demo pages uses overflow so it's most likely some other css interfering with yours.
