### ISSUE TITLE
max tags allowed

### ISSUE THREAD

**Issue by hagay-kassa-finiti** [dowjones/react-dropdown-tree-select#497]
I search and didnt found an option to limit number of tags allowed(for example only 3 tags will be displayed and then will be +n for n other chosen tags)

**Comment by mrchief** [comment]
You can limit the number of visible tags via CSS.

**Comment by hagay-kassa-finiti** [comment]
thanks, done with css

**Comment by RivkindLeon** [comment]
@hagay-kassa-finiti can you share your solution with css? thx
