### ISSUE TITLE
Version 1.0.0 installation through yarn is broken

### ISSUE THREAD

**Issue by dhirendrarathod2000** [dowjones/react-dropdown-tree-select#5]
Installing Version 1.0.0 with command

yarn add react-dropdown-tree-select

It does not have anything in it other then Readme, package.json and Licence file.

**Comment by mrchief** [comment]
Can you share a reproducible repo? Along with error details?

**Comment by dhirendrarathod2000** [comment]
with yarn i installed from this URL
https://registry.yarnpkg.com/react-dropdown-tree-select/-/react-dropdown-tree-select-1.0.0.tgz#423527fb05495497d9b509f71b53536af2066d3c
@mrchief 

also i tried on the previous version and styles.css does not get loaded by default when i render the drop down
please look in to that too.

**Comment by dhirendrarathod2000** [comment]
This are the files i get from that package
@mrchief 
[Archive.zip](https://github.com/dowjones/react-dropdown-tree-select/files/1303135/Archive.zip)

**Comment by mrchief** [comment]
@dhirendrarathod2000 This is fixed in v1.0.2. Thanks for raising this up! Let me know if you still run into issues.
