### ISSUE TITLE
How to show different text on pills of selected items?

### ISSUE THREAD

**Issue by TaymoorAk** [dowjones/react-dropdown-tree-select#510]
If you have a general query about the usage of react-dropdown-tree-select, or if you're not sure how to accomplish a particular task using the component; please raise a question on [stackoverflow.com](https://stackoverflow.com) with [react-dropdown-tree-select](https://stackoverflow.com/questions/tagged/react-dropdown-tree-select) tag.

If you think you found a bug or have a feature request, please use the `Bug Report`/`Feature request` template respectively.

**Comment by mrchief** [comment]
Please use the respective templates while creating issues.
