### ISSUE TITLE
the chilrdren in selectedNodes and Nodes  in functionn onchange is undefiend

### ISSUE THREAD

**Issue by saltovo** [dowjones/react-dropdown-tree-select#515]
**Describe the bug**
the chilrdren in selectedNodes and Nodes  in functionn onchange is undefiend

**To Reproduce**
https://codesandbox.io/s/react-dropdown-tree-select-forked-wkt69?file=/index.js

**Expected behavior**
the children should be the treeData this node contains 

**Screenshots**
![image](https://user-images.githubusercontent.com/46911969/131956568-5196b376-728b-4f91-8024-3585989f5459.png)

**Environment (please complete the following information):**
react-dropdown-tree-select@^2.5.1

**Comment by mrchief** [comment]
This is not a bug. You shouldn't be looking at `children` prop after initialization. `_children` is sort of an escape hatch (hence the underscore). I guess the component could simply delete the prop to avoid this confusion.
