### ISSUE TITLE
`disabled` makes all children nodes also `disabled`

### ISSUE THREAD

**Issue by sahuguet** [dowjones/react-dropdown-tree-select#520]
**Describe the bug**
I have a tree structure, e.g. US > states > counties.
I want to only select counties.
I am adding `disabled=true` to all the parent nodes.
Now all nodes are disabled.

**To Reproduce**
https://codesandbox.io/s/react-dropdown-tree-select-forked-5109i?file=/demo-data.json

**Expected behavior**
I would expect only nodes marked as `disabled` to be disabled, not nodes and all their descendants.

**Screenshots**
N/A

**Environment (please complete the following information):**
 

**Additional context**
N/A

**Comment by mrchief** [comment]
That's by design. You have 2 options:

1. make the the tree `hierarchical` [docs](https://github.com/dowjones/react-dropdown-tree-select#hierarchical)
2. override `disabled` on children by explicitly passing `disabled=false` for each child node.
