### ISSUE TITLE
Modified checked value of an object is not reflected in the dropdown.

### ISSUE THREAD

**Issue by nvijay1999** [dowjones/react-dropdown-tree-select#525]
Hi there. I'm using react-dropdown-tree-select to enable multi-value selection. Instead of showing the selected value inside the dropdown container, I'm making use of the onChange prop to get the selected nodes. To remove the selected nodes from outside the dropdown container, I'm using checked property of the selected node. After modifying the checked property of the selected node, the data is set using setState. But the changes are not reflected in the checkboxes inside the dropdown menu.

https://user-images.githubusercontent.com/51317884/137710472-fffb5dd3-31af-462c-a014-8dd04ab4b0bd.mov

**Comment by mrchief** [comment]
Do you have a Codesandbox to reproduce this?
