### ISSUE TITLE
Getting parent value on selection

### ISSUE THREAD

**Issue by alprbykn** [dowjones/react-dropdown-tree-select#533]
Is it possible to get value or label of selected node's parent. Not like ui-id such as  "rdts10-0-0", I want it's value as i.e U.K.
I also wonder how can access the selectednodes from outside.

**Comment by mrchief** [comment]
You get the id of the parent so you'd need to traverse but you can also pass in an extra property (or multiple) that you'd like to see `onChange` https://github.com/dowjones/react-dropdown-tree-select#data

![image](https://user-images.githubusercontent.com/781818/144147742-82546dec-e57a-4daf-8c10-299681d39fab.png)

**Comment by mrchief** [comment]
I created a Codesandbox for this https://codesandbox.io/s/breadcrumbs-with-react-dropdown-tree-select-id6ik?file=/index.js

![image](https://user-images.githubusercontent.com/781818/144267892-4ef9351c-268c-4e5a-a0fa-0549ba0ba828.png)
