### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by tlarsonlgdor** [dowjones/react-dropdown-tree-select#534]
I keep getting this error. I think I've tracked it to react-dropdown-tree-select in my react.js project. To get rid of the error, I'm assuming the nodes in the tree need a unique key prop. I tried adding a key prop to node object, but it still complains. The key prop I added to the object is in the data, but when I inspect the tree, the key property I added does not transfer to the `<li class="node label" id= ...>` items. Only the id.

**Comment by mrchief** [comment]
Each node, tag etc. gets assigned a unique key 

 - https://github.com/dowjones/react-dropdown-tree-select/blob/develop/src/tree/index.js#L96
 - https://github.com/dowjones/react-dropdown-tree-select/blob/develop/src/tags/index.js#L14
 - https://github.com/dowjones/react-dropdown-tree-select/blob/develop/src/tree-node/actions.js#L20

So it shouldn't be happening in the first place. Can you create a CodeSandbox?

**Comment by tlarsonlgdor** [comment]
Thanks for the feedback. I was calling the react-dropdown-tree-select multiple times in dynamic fashion. Each call needs a key at the top level. Apparently, key props don't show in html after build so its hard to track down. You can close this issue. Thanks for a great component.

**Comment by mrchief** [comment]
> Apparently, key props don't show in html after build so its hard to track down

If it's a dev build, they will show up in react dev tools 
![image](https://user-images.githubusercontent.com/781818/144638719-2abbef95-967f-4e5f-a46b-5c0b7440508c.png)
