### ISSUE TITLE
Feature request: Optionally disable popping of items on backspace keydown

### ISSUE THREAD

**Issue by r-zane-spalding** [dowjones/react-dropdown-tree-select#550]
**Is your feature request related to a problem? Please describe.**
Users are getting confused when trying to clear search filters with backspace and accidentally deselecting items. Using backspace on an empty search bar to deselect items doesn't seem to be expected behavior for most people. 

**Describe the solution you'd like**
Add a prop disablePoppingOnBackspace that defaults to false but is able to turn off this behavior.

**Describe alternatives you've considered**
Alternative could be disable by default and enable optionally but this would change existing behavior and likely wouldn't be ideal.

**Additional context**
```ts
//index.js

static propTypes = {
  //...
  tabIndex: PropTypes.number,
  disablePoppingOnBackspace: PropTypes.bool,
}

onKeyboardKeyDown = e => {
  //...
  } else if (!disablePoppingOnBackspace && e.key === 'Backspace' && tags.length && this.searchInput.value.length === 0) {
    const lastTag = tags.pop()
    this.onCheckboxChange(lastTag._id, false)
  } else {
    return
  }
  e.preventDefault()
}

//index.test.js
test('cannot delete tags on empty search input with backspace on keyboardNavigation with disablePoppingOnBackspace enabled', t => {
  const data = [{ ...node('a', 'a'), checked: true }, { ...node('b', 'b'), checked: true }]
  const wrapper = mount(<DropdownTreeSelect data={data} disablePoppingOnBackspace={true}/>)
  wrapper.instance().searchInput.value = 'x'
  triggerOnKeyboardKeyDown(wrapper, 'Backspace')
  t.deepEqual(wrapper.state().tags.length, 2)

  wrapper.instance().searchInput.value = ''
  triggerOnKeyboardKeyDown(wrapper, 'Backspace')
  t.deepEqual(wrapper.state().tags.length, 2)
  triggerOnKeyboardKeyDown(wrapper, 'Backspace')
  t.deepEqual(wrapper.state().tags.length, 2)
})
```

**Comment by mrchief** [comment]
@r-zane-spalding thanks for the suggestion and filling out the details. This is a good idea, and your code looks sound. Would you mind sending a PR? We'd also need to add this to the docs.

**Comment by r-zane-spalding** [comment]
Sure, I'll have that in shortly. Thanks for the response!
