### ISSUE TITLE
Webpack loaders throw an error

### ISSUE THREAD

**Issue by JoseSNubimetrics** [dowjones/react-dropdown-tree-select#558]
Hello! I'm having problems with webpack loaders for the styles

Here it is:
![image](https://user-images.githubusercontent.com/94978267/160876886-02894f0d-f434-44e7-b2bf-07e6bfee0d95.png)

I have the newest version of the library and react too. What could be the cause of the problem?? Thanks

**Comment by mrchief** [comment]
Your webpack is trying to build/compile node modules which you shouldn't do. There's also a webpack [config](https://github.com/dowjones/react-dropdown-tree-select#using-webpack) for loading styles, if you're using them. This was also mentioned in old issues so please search them to find solutions to common problems.
