### ISSUE TITLE
Error: The above error occure in the <t> component

### ISSUE THREAD

**Issue by JoseSNubimetrics** [dowjones/react-dropdown-tree-select#559]
Hi there!! I'm having problems when React tries to renderize the component and comes up with this error, that begins I think, inside the library. I have used it in a repository without webpack itself, but in this new project I have webpack with loaders and the error occurs.
Any help?? Thanks

![image](https://user-images.githubusercontent.com/94978267/162763410-0941c8a6-57de-425c-bc04-eb179bbb8908.png)
![image](https://user-images.githubusercontent.com/94978267/162763552-50c12ff5-d26b-41f1-abfc-76b9d9459c1d.png)

**Comment by JoseSNubimetrics** [comment]
@mrchief

**Comment by mrchief** [comment]
Most likely webpack is compiling node_modules again. Try excluding node_modules from your webpack.

**Comment by Josesan94** [comment]
Hello! @mrchief . Do you mean that exclude the node modules from the rule that I'm putting inside my webpack?

Here is a screenshot:
![image](https://user-images.githubusercontent.com/82479775/162964989-23f25c38-9282-4542-961c-e7cc9641ffbf.png)

**Comment by mrchief** [comment]
Something like this https://stackoverflow.com/a/35820388/244353
