### ISSUE TITLE
Feat: React 18 support?

### ISSUE THREAD

**Issue by vova42matters** [dowjones/react-dropdown-tree-select#560]
**Is your feature request related to a problem? Please describe.**
When using `react@18.0.0` and running `npm install`, an error gets thrown.

**Describe the solution you'd like**
Just update `peerDependencies` and test out dropdown

**Describe alternatives you've considered**
Running `npm config set legacy-peer-deps true` solves the problem.

**Additional context**
Logs:
```
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0 || ^17" from react-dropdown-tree-select@2.7.1
npm ERR! node_modules/react-dropdown-tree-select
npm ERR!   dev react-dropdown-tree-select@"2.7.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Using Node 16, npm 8.2.0

**Comment by mrchief** [comment]
not stale

**Comment by erikmoren** [comment]
Hi, any progress with this ...?

**Comment by ldeveber** [comment]
FWIW, we are using this with React 18 and have not seen any side effects (other than the usual warnings about `componentWillReceiveProps`)

**Comment by mrchief** [comment]
Does anyone care to send a PR? Should be a quick one

**Comment by apaschenko-amplify** [comment]
Probably something has to be done with enzyme tests as a part of this migration. As https://github.com/enzymejs/enzyme/issues/2524 suggests, enzyme is not going to support React 18 in the near future.

**Comment by moxxuk** [comment]
This is not completed

**Comment by pckilgore** [comment]
I believe `npx react-codemod rename-unsafe-lifecycles` should work to do this in the short term, but requires a dependency update to react 16.3+

**Comment by pckilgore** [comment]
I submitted a pr to fix this recently.
