### ISSUE TITLE
Styles.css library component

### ISSUE THREAD

**Issue by JoseSNubimetrics** [dowjones/react-dropdown-tree-select#563]
Hello, recently I have been struggling with this error that appears below in the picture:

![image](https://user-images.githubusercontent.com/94978267/166855071-8f8c354c-4e20-4bd1-b186-b1be36c77dcf.png)

It appears when I execute the npm run build command and start to compile de package. Do you know any solution I might use without the necessity of installing any other loader to the webpack??

Thanks!!

**Comment by mrchief** [comment]
You need to exclude node_modules from getting compiled again from your build processes. There have been similar issues/discussions in the past regarding this as well.
