### ISSUE TITLE
Disabled categories expand and collapse problems

### ISSUE THREAD

**Issue by JoseSNubimetrics** [dowjones/react-dropdown-tree-select#564]
**Describe the bug**
Disabled categories dissapear with its children after clicking in toggle 

**To Reproduce**
In my case, I have disabled parents ho has non-disabled childrens

**Expected behavior**
It has to act normally, as it would be an enabled categorie tree that shows up its children and can be collapsed or expanded normally

**Screenshots**
Here is what is happening:

https://user-images.githubusercontent.com/94978267/168902506-f5512041-e3fe-4184-94cc-8a9a87f04f05.mp4

This is the component of the tree made with reactMemo:

![image](https://user-images.githubusercontent.com/94978267/168902862-e05f75ed-0370-45dd-beb1-da69c13162a5.png)

**Environment (please complete the following information):**
 - Browser chrome v60.12.0
 - OS:  Windows x64] 
 - node version 6.0

**Additional context**

**Comment by mrchief** [comment]
Does it happen if you remove `React.Memo`?

**Comment by JoseSNubimetrics** [comment]
Yes, it's doing the same. Only with the disabled categories

**Comment by mrchief** [comment]
Can you provide a codesandbox to reproduce this?

**Comment by JoseSNubimetrics** [comment]
Yes! https://codesandbox.io/live/ed8f5eada88

**Comment by JoseSNubimetrics** [comment]
Hi there @mrchief ! Did you get the chance to see the sandbox??

**Comment by JoseSNubimetrics** [comment]
Hope to see some conversation here! thanks

**Comment by mrchief** [comment]
There's a lot going on in that sandbox. I created a basic sandbox https://codesandbox.io/s/react-dropdown-tree-select-forked-humt2 and tried to reproduce the error but I don't see it happening here. I'm inclined to think it is some combination of hooks and state refresh that you have is causing the issue. Take a look and see if you can reproduce the issue in my sandbox without all of your custom logic of course.

**Comment by JoseSNubimetrics** [comment]
Hello @mrchief . Certainly, in your sandbox the error its not happenning. I Think it might be caused because of the react.memo implementation. But if I don`t do it this way, a re-rendering problem appears and the checkboxs don`t work

**Comment by MarcosNASA** [comment]
> There's a lot going on in that sandbox. I created a basic sandbox https://codesandbox.io/s/react-dropdown-tree-select-forked-humt2 and tried to reproduce the error but I don't see it happening here. I'm inclined to think it is some combination of hooks and state refresh that you have is causing the issue. Take a look and see if you can reproduce the issue in my sandbox without all of your custom logic of course.

I've managed to reproduce it by simply setting a parent node as `expanded: false`, then its child (which also has children) set to `expanded: true`.

Sandbox: https://codesandbox.io/s/react-dropdown-tree-select-bug-9hz2rr?file=/demo-data.json
