### ISSUE TITLE
Customize rendering of tags list

### ISSUE THREAD

**Issue by arnaud-deprez** [dowjones/react-dropdown-tree-select#565]
## Is your feature request related to a problem? Please describe.
Currently we can customize tags list with css but it has some limitations.
In our use case, we can select a lot of items in the tree making the tags list big and the general look&feel is then impacted.

## Describe the solution you'd like
It would be nice to be able to customize the tags list rendering for example to add an ellipsis button (or +x buttons) after 3 items for example.
When you click on that button, it would expand the list somehow (defined by user).

## Describe alternatives you've considered
I'm considering rewriting my own components just because of this.
I don't see how I can achieve this with the current implementation.

I can also try to build that feature if you're interested, please let me know!

**Comment by mrchief** [comment]
@arnaud-deprez The original idea was that we could accept renderers for things like tag list, dropdowns etc. as props. That was to be done with the hooks based rewrite of this component which has fallen behind, primarily due to lack of time on my part. I'd love to accept a PR on this.

**Comment by arnaud-deprez** [comment]
Hi,

I also think this should be part of a bigger refactoring.

For example using this library with https://react-hook-form.com/ is tricky.
I had to build a HOC component with some `useRef` and `onChange`, `onFocus` and `onBlur` to have something workable and at the end, even if it is working, I'm not sure whether it covers all possible user clicks/actions.

I think this kind of integration should be more straightforward and easier.

I'm also working with my customer to have a more integrated design, so we will probably have to rewrite the component ourselves. 
I'm not sure I will have time for this at the end unfortunately.

**Comment by mrchief** [comment]
I understand. Thanks for your interest.
