### ISSUE TITLE
Maybe add checkbox to select all tree

### ISSUE THREAD

**Issue by congdinh** [dowjones/react-dropdown-tree-select#57]

**Comment by mrchief** [comment]
This is already supported. Your data just needs to have a single root node (call it `Select All`?).

**Comment by congdinh** [comment]
Same this image
![image](https://user-images.githubusercontent.com/13956091/37139360-2ebf5da4-22e0-11e8-8371-33045e28927d.png)

**Comment by mrchief** [comment]
Oh I see now. It seems more of an UI customization which can be done via an HOC. Checkout this sandbox:

[![Edit Select All Checkbox with React Dropdown Tree Select](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rjwqq86p1n)

**Comment by congdinh** [comment]
@mrchief thanks. Take it easy. My issue has been resolved :+1:
