### ISSUE TITLE
Single click to clear search field

### ISSUE THREAD

**Issue by bmm-brobbins** [dowjones/react-dropdown-tree-select#576]
**Is your feature request related to a problem? Please describe.**
After searching, must manually clear search field, via e.g. highlight+delete or backspacing.

**Describe the solution you'd like**
Proposal for an 'x' to appear at right of search field to enable single-click clearing of search contents.

**Describe alternatives you've considered**
Haven't found a solution here or the usual forums.

**Additional context**
Any pointers or code to accomplish this feature in the interim using lib's existing capabilities and/or an HOC would be great.
I'm using inlineSearchInput, btw.  
P.s. Great lib, thank you for publishing it.

**Comment by mrchief** [comment]
@bmm-brobbins I think it's a fair use case but implementing it is bit more than trivial. Apart from the likely UX confusion that extra `x` may create on smaller viewports, we also need to figure out accessibility aspect of it - that includes keyboard nav, tab focus order etc. 

There is something you can do though to mimic the functionality:
 - create your own wrapper control that puts the `x` in the input box (use CSS to position it)
 - on click of this button, you programmatically reset the data (in effect wiping out all selections)
