### ISSUE TITLE
openOnSelect after making search-based selection(s) in multiSelect default mode

### ISSUE THREAD

**Issue by bmm-brobbins** [dowjones/react-dropdown-tree-select#577]
**Is your feature request related to a problem? Please describe.**
After making selection(s) based on search, then clearing search term, newly selected nodes don't expand.  Parent displaying as partiallySelected is the only visible result.

**Describe the solution you'd like**
Proposal for an option to have tree automatically expand nodes that have been newly selected via search.

**Describe alternatives you've considered**
Tried setting .expanded=true on newly selected children and/or their parent node, but it doesn't seem to take.

**Additional context**
Any pointers or code to accomplish this feature in the interim using lib's existing capabilities and/or an HOC would be great.

P.s. Great lib, thank you for publishing it.

**Comment by mrchief** [comment]
Bit of an odd case but setting the expand should have done the trick. Do you mind creating a small reproducible example?
