### ISSUE TITLE
Still able to retrieve Tree Node Paths? 

### ISSUE THREAD

**Issue by codysmith-taulia** [dowjones/react-dropdown-tree-select#578]
I'm using version `2.5.1` of this plugin. I'm noticing the `currentNode` coming back from the `onChange` callback doesn't contain a 'path' property like it states in the docs. I noticed in the CodeSandbox [example](https://codesandbox.io/s/tree-node-paths-with-react-dropdown-tree-select-forked-kvpgqo?file=/index.js) here it's using version `2.0.2`. 

Did this feature get removed from later versions for simplicity, performance reasons?

**Comment by mrchief** [comment]
It gets added via the [HOC.js](https://codesandbox.io/s/tree-node-paths-with-react-dropdown-tree-select-forked-kvpgqo?file=/HOC.js) to the `data` object. It's not part of the core component.

**Comment by codysmith-taulia** [comment]
@mrchief Thanks for your response with the codesandbox.io link 🙏🏼🙌🏼💯!
