### ISSUE TITLE
How to get children values on selectedNodes on onChange method when parent is selected?

### ISSUE THREAD

**Issue by VSV6** [dowjones/react-dropdown-tree-select#596]
When the parent node is selected, I need the children values also on the onChange method.

How can I achieve this?

**Comment by mrchief** [comment]
You'd have to tease that out by keeping track of the data nodes yourself. One way would be to assign a node-path it each node and using that property, you can get to `node.children` in your data bag.

**Comment by VSV6** [comment]
OK but node.children is undefined in my case.

**Comment by mrchief** [comment]
Yeah, `node.children` in **your** data bag :)

**Comment by gokulgtrois** [comment]
node.children is undefined in my case.  How we can solve it?

**Comment by mrchief** [comment]
> node.children is undefined in my case. How we can solve it?

You're looking at the `node` argument - you should be looking at the corresponding node in your own separate state/data bag. It requires you to keep tracking data on your own but it can be abstracted into an HoC https://codesandbox.io/s/l765q6lmrq?file=/HOC.js

There are plenty of examples in old issues if you search for them.
