### ISSUE TITLE
All child nodes are showed in search input instead of showing only parent node when select parent node 

### ISSUE THREAD

**Issue by thanhvu233** [dowjones/react-dropdown-tree-select#605]
Hi everyone,
Is there any way to show all child nodes in search input instead of showing only parent node when we select parent node like this?
![image](https://user-images.githubusercontent.com/63567328/203691383-c0992de7-d740-4218-ae54-da4c5497cd3b.png)

Thanks a lot!

**Comment by matrixmandeep** [comment]
does it resolved?
