### ISSUE TITLE
Add CSS class for partial selected on parent node

### ISSUE THREAD

**Issue by toofff** [dowjones/react-dropdown-tree-select#61]
Hello,

Already a big thank you for your work :clap: 

I need a CSS class that is not present at the moment in your plugin.
Adding a CSS class on the parent node when children are partially selected.

In my example, below, the 'SKI DE FOND' node should have this CSS class because their second child is not selected.
![capture d ecran de 2018-03-15 16-51-18](https://user-images.githubusercontent.com/966550/37474738-5a381228-2871-11e8-8497-73bd29f6b702.png)

Does this feature seem interesting to you for your plugin?

**Comment by mrchief** [comment]
This is something I wanted to do since the beginning but never got the chance to do. I'll gladly accept a PR for this. Or I can get to it by this weekend if life permits. :)

**Comment by toofff** [comment]
I'm going to watch what I can do tonight. :)
