### ISSUE TITLE
Feature is not working as expected in "react": "^18.0.0", "react-dropdown-tree-select": "2.8.0"

### ISSUE THREAD

**Issue by ChaitraNarayanaSwamy** [dowjones/react-dropdown-tree-select#615]
**Describe the bug**
Feature is not working as expected where child nodes and drop down arrow are not displayed in "react": "^18.0.0", "react-dropdown-tree-select": "2.8.0", even the default selected value(only the root node), is displayed above the dropdown text field.

**To Reproduce**
Please find the link here, https://codesandbox.io/s/react-18-playground-forked-3vrq4l?file=/src/App.tsx

**Expected behavior**
Actual implementation of react dropdown tree select has to work in the above specified versions

**Screenshots**
<img width="186" alt="image" src="https://user-images.githubusercontent.com/49052583/213092562-005c2fc4-14c4-4015-857f-1be0dbc97ad1.png">

**Environment (please complete the following information):**
 - Browser Chrome- Version 109.0.5414.74
 - OS: Windows x64 
 - node version: v18.12.0
 - npm version: 8.19.2

**Additional context**

**Comment by mrchief** [comment]
You are missing imports for stylesheet. Here's a working version https://codesandbox.io/s/react-18-playground-forked-xsgr4y?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/781818/214371379-09db66d7-4140-4939-8971-6fe98beff51b.png)
