### ISSUE TITLE
React 18 Strict mode warning: "Using UNSAFE_xxxxx in strict mode is not recommended and may indicate bugs in your code."

### ISSUE THREAD

**Issue by salehmdev** [dowjones/react-dropdown-tree-select#618]
**Describe the bug**
When upgrading to React 18, 2 warnings in the console seem to be caused by this package while using Strict mode. From personal usage, the warnings that I see are:
- "Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code."
- "Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code."

**To Reproduce**
* I've forked the sample CodeSandbox from above: https://codesandbox.io/s/react-dropdown-tree-select-forked-1e03bt?file=/package.json

**Expected behavior**
* Support for strict mode in React 18+.
* No errors/warnings showing up in the console when on React version 18+.

**Screenshots**
![image](https://user-images.githubusercontent.com/32750050/217925836-5053ab7e-b011-4915-b71c-f4ba986f67e4.png)

**Environment (please complete the following information):**
 - Browser: Firefox & Chrome
 - OS: Windows

**Additional context**
* The origin of this warning message was difficult to diagnose since the warning doesn't mention what exact component the warning is coming from (as you can see from the screenshot). After scouring google search and checking all dependencies, I think I found a relevant issue in this package that might be directly related.
  * Issue #560 
    * PS - thank you for providing the React 18 support!
  * There are a few cases of using those `UNSAFE_ .. ` methods in the project, probably not just from this issue.

**Comment by StephaneIzi** [comment]
Yeah, i still have the exact same problem

**Comment by mark-codylor** [comment]
Same issue here

**Comment by najathi** [comment]
Same issue here
