### ISSUE TITLE
multiSelect + radioSelect &&  input + multiSelect

### ISSUE THREAD

**Issue by atkxyh** [dowjones/react-dropdown-tree-select#625]
Question1: Assume a tree has many nodes, one is a radioSelect, others are multiSelect
Question2: Assume a tree has many nodes, some are input(content editable), others are multiSelect(checkable)
![Snipaste_2023-04-10_11-39-47](https://user-images.githubusercontent.com/67258027/230821068-8b641cf3-a794-4e1d-91d0-f2c94236816e.png)
![Snipaste_2023-04-10_11-40-02](https://user-images.githubusercontent.com/67258027/230821074-cda6f8ac-bd8e-4665-8256-af0a14be9c10.png)

**Comment by atkxyh** [comment]
BTW, these pictures are from nordic's kconfig component, I wonder if this lib can support the fucntion?

**Comment by mrchief** [comment]
I don't think so.
