### ISSUE TITLE
After react project build this package is not working

### ISSUE THREAD

**Issue by nishantpanamaxil** [dowjones/react-dropdown-tree-select#629]
I'm using latest version (2.8.0) its working fine with local run (npm start) but when we make a build of projects from bundle its not working. Please checked attached screen shot. Here I'm sharing my package.json dependencies. 

"devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-decorators": "^7.0.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "@babel/plugin-proposal-function-sent": "^7.0.0",
    "@babel/plugin-proposal-json-strings": "^7.0.0",
    "@babel/plugin-proposal-numeric-separator": "^7.0.0",
    "@babel/plugin-proposal-optional-chaining": "^7.17.12",
    "@babel/plugin-proposal-throw-expressions": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-syntax-import-meta": "^7.0.0",
    "@babel/plugin-syntax-optional-chaining": "^7.8.3",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "@testing-library/react": "^12.1.5",
    "babel-eslint": "^9.0.0",
    "babel-jest": "^29.3.1",
    "babel-loader": "^8.0.0",
    "clean-webpack-plugin": "^0.1.19",
    "css-loader": "^3.4.2",
    "eslint": "^4.19.1",
    "eslint-config-react-app": "^2.1.0",
    "eslint-plugin-flowtype": "^2.47.1",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.19.0",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "jest": "^29.3.1",
    "jest-environment-jsdom": "^29.3.1",
    "jsdom": "^20.0.3",
    "jsoneditor": "^9.7.2",
    "mini-css-extract-plugin": "^0.4.5",
    "node-sass": "^4.14.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-test-renderer": "^16.13.0",
    "redux-mock-store": "^1.5.4",
    "sass-loader": "^6.0.7",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "url-loader": "^1.1.2",
    "webpack": "^4.41.5",
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.7.2"
  },
  "dependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.0.0",
    "@babel/polyfill": "^7.0.0",
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.57",
    "@tinymce/tinymce-react": "^3.13.0",
    "axios": "^0.21.1",
    "classnames": "2.2.6",
    "compression-webpack-plugin": "^1.1.12",
    "deepmerge": "^4.2.2",
    "dot-object": "^2.1.4",
    "dotenv-webpack": "^7.0.2",
    "file-loader": "^6.2.0",
    "file-saver": "^2.0.2",
    "immutability-helper": "^3.1.1",
    "instantsearch.css": "^7.4.2",
    "javascript-obfuscator": "^2.17.0",
    "jquery": "^3.5.1",
    "material-ui-pickers": "1.0.0-rc.9",
    "moment": "^2.29.4",
    "mui-datatables": "^2.14.0",
    "rc-drawer": "^1.10.1",
    "rc-queue-anim": "1.6.1",
    "react-addons-update": "^15.6.3",
    "react-beautiful-dnd": "^13.0.0",
    "react-color": "^2.19.3",
    "react-content-loader": "^3.4.2",
    "react-countup": "^3.0.3",
    "react-custom-scrollbars": "^4.2.1",
    "react-debounce-input": "^3.2.2",
    "react-dropdown-tree-select": "^2.8.0",
    "react-hot-loader": "^4.13.0",
    "react-intl": "^2.4.0",
    "react-joyride": "1.11.4",
    "react-js-pagination": "^3.0.3",
    "react-notifications": "^1.4.3",
    "react-redux": "^7.2.4",
    "react-router-dom": "^4.2.2",
    "react-select": "^3.1.0",
    "react-sidebar": "^2.3.2",
    "react-slick": "^0.28.1",
    "react-sortable-tree": "^2.7.1",
    "react-toggle-switch": "^3.0.4",
    "reactcss": "^1.2.3",
    "reactstrap": "^8.9.0",
    "redux": "4.0.0",
    "redux-saga": "^0.16.2",
    "screenfull": "^3.3.2",
    "slick-carousel": "^1.8.1",
    "socket.io-client": "^2.3.0",
    "validator": "^10.11.0",
    "webpack-obfuscator": "^2.6.0",
    "xlsx": "^0.18.5"
  }
![Screenshot 2023-05-19 12 18 56](https://github.com/dowjones/react-dropdown-tree-select/assets/67776242/35ab7c37-a1c8-4f5e-ae78-5fc4014ff049)
![Screenshot 2023-05-19 12 18 31](https://github.com/dowjones/react-dropdown-tree-select/assets/67776242/97173367-116d-448e-bcc7-adb12948ec5b)

**Comment by mrchief** [comment]
It looks like you are rebuilding the package. You could try excluding node_modules from your build.
