### ISSUE TITLE
Add snapshot based testing

### ISSUE THREAD

**Issue by mrchief** [dowjones/react-dropdown-tree-select#63]
Either use Ava's snapshot testing or move to Jest. Jest offers more than Ava, so is preferred.

**Comment by Gregcop1** [comment]
I've just changed it in my project (with jest) and it's really great improvment. It's way more simple. Having "__snapshots__" folders everywhere in the app is a bit annoying but I understand their argument on why keeping this rule.
I think I can help you with this in some days.

**Comment by mrchief** [comment]
Ava also supports snapshots. And I like the markdown based snapshot diffs. I think its better than Jest. The only thing I don’t like with ava is lack of grouping abilities- like describe blocks. Ava recommends different files to group tests. Kinda makes sense but not always. Also jest’s cli is slightly easier, especially with matching tests.

**Comment by Gregcop1** [comment]
So Ava or Jest ? ;)

**Comment by mrchief** [comment]
It's a tough one :)

Jest:
- allows grouping of tests 
- easier CLI
- have a [branch](https://github.com/dowjones/react-dropdown-tree-select/tree/test_snapshots) with initial migration of tests
- code coverage comes integrated
-  makes sinon redundant

Ava:
- better diffing, and failure debugging
- minimal migration - just need to add snapshots for the ones we don't have already
- no grouping of tests
- cli slightly more verbose
- no builtin code coverage but we already have nyc setup for that
- probably a bit faster 

I'm leaning towards ava but its a close one. Thoughts?
