### ISSUE TITLE
Not able to add scrollbar and search input within a child node that has children.

### ISSUE THREAD

**Issue by sunday-ucheawaji** [dowjones/react-dropdown-tree-select#630]
**Describe the bug**
Am unable to add a scrollbar and a search bar to a child node that has children

**To Reproduce**
A node having large data say above 100 might require a search input and a scrollbar within it for ease of use. I noticed that there is no HTML element grouping the children of a node to a form a block. This made it impossible for me to add a scrollbar for the children.

**Environment (please complete the following information):**
 - Browser [e.g. chrome v60.12.0, safari 10.1]
 - OS: [e.g. iOS, Windows x64] (if applicable)
 - node version (if applicable)
 - yarn or npm version (if applicable)

**Additional context**

**Comment by mrchief** [comment]
The main input is the search provider and the scrollbars are dynamic - they appear when you scroll. You can see it in the  basic demos. If this is not what you're trying to accomplish, could you please elaborate?

**Comment by sunday-ucheawaji** [comment]
@mrchief Thanks for the reply. I want to be able to implement a search within a nested layer, such that only children within that layer are considered in the search. I also want to be able to implement a scrollbar within the nested layers too such that the scrollbars only apply to the children. Finally, is there a way I could change the default checkbox and the expand icon to my custom checkbox and custom expand icon?

**Comment by mrchief** [comment]
> I want to be able to implement a search within a nested layer, such that only children within that layer are considered in the search. I also want to be able to implement a scrollbar within the nested layers too such that the scrollbars only apply to the children.

Unfortunately, you'd need to fork the project and add those abilities yourself.

> Finally, is there a way I could change the default checkbox and the expand icon to my custom checkbox and custom expand icon?

Yes, check out the readme for links to sandboxes where it uses Bootstrap, Material Design and even esoteric ones like country flags.
