### ISSUE TITLE
The searchTerm in the searchPredicate function is never an empty string

### ISSUE THREAD

**Issue by lennertVanSever** [dowjones/react-dropdown-tree-select#637]
**Describe the bug**
When a user types in the input field, the searchPredicate function is triggered with whatever the user is writing. However, when the user empties his input field, the searchPredicate function is never triggered with an empty string.

**To Reproduce**
```
function searchPredicate(node, searchTerm) {
  console.log(searchTerm) // this is never an empty string ""
  return false
}

return <DropdownTreeSelect data={data} searchPredicate={searchPredicate} />
```

**Expected behavior**
When the input field is emptied, the searchPredicate function is triggered with an empty string.

**Comment by gandhis1** [comment]
Is an empty string a valid search term? What use case do you anticipate for this?

I made a specific change that was accepted a few months ago to do this because there did not appear to be a good reason to incur the search predicate cost across a potentially large number of nodes with an empty string. See https://github.com/dowjones/react-dropdown-tree-select/pull/580

**Comment by lennertVanSever** [comment]
In my project, we use the searchPredicate function to build a custom async tree dropdown. Now our component is not working as expected when the input is cleared, we should be able to show all the options in that case but we can't.

**Comment by gandhis1** [comment]
> In my project, we use the searchPredicate function to build a custom async tree dropdown. Now our component is not working as expected when the input is cleared, we should be able to show all the options in that case but we can't.

So the change I had made would not filter anything if search mode was off, which it was if the query was an empty string. That is, I would expect the default behavior with an empty string is to show all options.

Is this something you can create a code sandbox demonstrating?

**Comment by lennertVanSever** [comment]
Hi, I have a sandbox here with an example: https://codesandbox.io/s/blue-snowflake-jqt35v?file=/src/index.js

if the search term is empty, it is not reflected that way in the searchPredicate

**Comment by mrchief** [comment]
`searchPredicate` was meant to return matches, so an empty string doesn't mean it matches all. That can be a business interpretation for a particular use case but baking that in, makes the control opinionated. 

I like the idea of a separate function to notify when the search input is empty but I wonder why there are so many changed files. We need to verify if every snapshot is still the same, which at a glance appears to be so but again, I don't like the fact that avajs decided to change the render sequence throwing the git diff off.

**Comment by lennertVanSever** [comment]
Thanks for your response @mrchief. The many file changes are indeed related to the avajs. I only executed `ava --update-snapshots` so no idea what went wrong on that regard.
