### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by maxine-l-m** [dowjones/react-dropdown-tree-select#642]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the component in an rtl page but the component does not look right

**Describe the solution you'd like**
I want the component to be styled correctly when rendered in rtl

**Additional context**
I have already made a fix for this, I'm opening this issue for bureaucratic reasons only

**Comment by mrchief** [comment]
> I'm opening this issue for bureaucratic reasons only

What bureaucratic reasons? I'd like to abolish all bureaucracy 😆
