### ISSUE TITLE
By default the last child is focused and checked

### ISSUE THREAD

**Issue by Ilankumaran-developer** [dowjones/react-dropdown-tree-select#645]
**Describe the bug**

I had tried to implement this into my project but ended up with following issue. I used the example data given here https://dowjones.github.io/react-dropdown-tree-select/#/story/with-material-design-styles

1. checkbox and icon not displaying
2. regardless of option selected, always the last child is selected 
3. last child is marked as focused and checked by default

**To Reproduce**
Please include steps to reproduce the behavior;
or an URL to Reproduction repository; 
or a CodeSandbox (you can fork [this](https://codesandbox.io/s/842m620yv0) one)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Browser [e.g. chrome v60.12.0, safari 10.1]
 - OS: [e.g. iOS, Windows x64] (if applicable)
 - node version (if applicable)
 - yarn or npm version (if applicable)

**Additional context**

**Comment by mrchief** [comment]
Do you have a codesandbox that can reproduce this?
