### ISSUE TITLE
Issue when click item in long scrollable list

### ISSUE THREAD

**Issue by nguyenson2012** [dowjones/react-dropdown-tree-select#652]
**Describe the bug**
When I provide a long list of item(20 item) to component dropdown tree, I also add scrollbar for the list. 
But when I scroll and click the item 10, it's not selected, it select item 8 instead.
**To Reproduce**
+ Create list of 20 item
+ Provide list item with scrollbar
+ Scroll and click the item 10

**Expected behavior**
Specified item is clicked correctly

**Environment (please complete the following information):**
 - Browser chrome v60.12.0
 - OS: Windows x64
 - node version  16.6.0
 - yarn or npm version  1.22.19

**Comment by mrchief** [comment]
Can you do a sandbox? I don't see it happening in the demo.
