### ISSUE TITLE
react-dropdown-tree-select - Get all selected values

### ISSUE THREAD

**Issue by mahesh-insight** [dowjones/react-dropdown-tree-select#653]
In several places, I saw your @mrchief resolution [comment](https://github.com/dowjones/react-dropdown-tree-select/issues/108). 
Really Appreciate it.

Assign node paths to your tree via an [[HOC]](https://dowjones.github.io/react-dropdown-tree-select/#/tree-node-paths-hoc) - I am done with this point.

Take the node path (any extra props on the node object are returned as is) to grab the children from your input data.
Not getting this actually. How to check the specific value from the node path.

_Note - The Tree Data comes from the API._

![Screenshot 2023-11-04 at 11 50 23 AM](https://github.com/dowjones/react-dropdown-tree-select/assets/144375931/d5c5ac3a-5931-4cd2-85f7-c32eb3889e6b)

On the selection of the parent element - AKS - I need the related children value - deploymentNode
![Screenshot 2023-11-04 at 11 52 14 AM](https://github.com/dowjones/react-dropdown-tree-select/assets/144375931/9e54b0ea-29f3-41bc-aee7-6c7247f8e3ef)

It's only returning the _rdts...nodenames, where I need to value name.
Reference - https://codesandbox.io/s/amazing-goodall-dkxt45

I am looking for a positive revert.

**Comment by mrchief** [comment]
Thanks for the kind words! You're mostly on track. What you're missing is the piece that connects node paths to your original `data`. The idea is that you take the nodepath from the event object, and use it to locate the node within your own data. 

Any fields prefixed with an underscore are internal and you should not rely on them. However, any custom props you pass are always bubbled back, like your `bread` prop. So pass `nodePath` as an additional prop and when you get that back, you can use to look it back up.

**Comment by mahesh-insight** [comment]
We are using the dynamic API for the tree data. 
What I have done - 

- On the change of dropDown - passes the selected nodes and the whole endpoint data.
- Then two different array objects are taken - one for the parent (when the parent label is selected and returns all its children, and the second one for the children's selected value (when the children are selected).
- On the selection of parent label - takes that value and scans in the whole endpoint data - and returns the related children when it matches.
- At last concat those two arrays.
