### ISSUE TITLE
Clicking on label for radioSelect doesn't select a node

### ISSUE THREAD

**Issue by mkaluzny** [dowjones/react-dropdown-tree-select#661]
With radioSelect mode clicking on a label of a node should set a value to the clicked node, however it should set the value to the selected node (as it happens for singleSelect mode).
Currently nothing happend after clicking the label (besides closing the dropdown). Use have to click on radio to select the node, it would be much more intuitive if clicking on label would also select the node.

**Comment by putramtp** [comment]
hi , i found a same problem , 
I temporarily changed the data structure and set the desired value to checked === true , it worked for me,
ex: 
data =  
{ label,          // required: Checkbox label
  value,          // required: Checkbox value
  children ,       // optional: Array of child objects
  checked : true 
}

I hope it helps you : )
