### ISSUE TITLE
How can I remove the tags that appear when a node is selected in the dropdown?

### ISSUE THREAD

**Issue by siddhishree** [dowjones/react-dropdown-tree-select#667]
<img width="671" alt="Screenshot 2024-03-15 at 8 01 15 PM" src="https://github.com/dowjones/react-dropdown-tree-select/assets/27063433/3cae25d5-056f-4bbc-adc6-b0a832e66987">

I want to remove these tags - "marmara university", "dublin Institute of technology" from the dropdown. How can I achieve this?

**Comment by bogdewi4** [comment]
You could resolve it with css.

SCSS:

`.tag-item {
  display: none;
  &:last-child {
    display: inline;
  }
}`
