### ISSUE TITLE
uncontrolled warning on console

### ISSUE THREAD

**Issue by mikdatdogru** [dowjones/react-dropdown-tree-select#77]
i can use react 16.2.0

All versions above 1.3.0 have the following warning to console; (1.4.0, 1.5.0, 1,6,0, 1,6,1 ... 1.7.0)

 
**When choosing item from Dropdown options**

> index.js:2178 Warning: A component is changing an uncontrolled input of type checkbox to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
    in input (created by c)
    in label (created by c)
    in c (created by C)
    in li (created by C)
    in C (created by l)
    in ul (created by l)
    in l (created by t)
    in div (created by t)
    in div (created by t)
    in div (created by t)
    in t (at App.js:43)
    in div (at App.js:38)
    in App (at index.js:7)

**clicking outside and closing the dropdown**

> Warning: An update (setState, replaceState, or forceUpdate) was scheduled from inside an update function. Update functions should be pure, with zero side-effects. Consider using componentDidUpdate or a callback.

![image](https://user-images.githubusercontent.com/10121255/38283604-8840e462-37bf-11e8-90a0-a1ab156e879f.png)

**Comment by mrchief** [comment]
Thanks for reporting this. This is a known issue and #73 will fix this.

**Comment by mrchief** [comment]
@mikdatdogru Try with the latest version and let me know if you still see it.

**Comment by josvegit** [comment]
I just updated to 1.8.0 and I can still see the error when clicking outside. The other one is harder for me to reproduce, will let you know.

**Comment by mrchief** [comment]
@josvegit I was able to repro the click outside issue by:

- Go to demo page: https://dowjones.github.io/react-dropdown-tree-select/#/story/basic-no-extra-styles
- Open the dropdown
- Click outside

It doesn't happen afterwards. I'll be looking into this. 

Please feel free to send a PR if you happen to have a quicker fix.

**Comment by josvegit** [comment]
@mrchief  nah seems to work fine anyway, just an annoying console warning that triggers devs :)

**Comment by josvegit** [comment]
@mrchief btw good work with this component, using it in production, works great ! Only quirk with it is that search gets slow when the tree becomes very large (15k nodes). Best react component for the job, by far.

**Comment by mrchief** [comment]
@josvegit Thanks for the kind words! I'm glad you find it useful.

Regarding the search, would you mind sharing your dataset? If not, can you tell me more about the structure? E.g. Is it 15k of serialized data or 15k nodes? How deep the nodes go and so on so I could play around with it?

**Comment by josvegit** [comment]
I'm pretty sure I cannot give you the actual data.. even though it probably would not matter at all (don't wanna lose my job :D). The size according to chrome is 177kb. The Data is an array(size 25), each of these elements has between 50-100 children, which then have more children and so on..  Should probably not load all the data at once but w/e .. got deadlines..

**Comment by mrchief** [comment]
I don't need the actual data, just an idea of how many levels to look for and overall size of the data. The tree doesn't render all the nodes - only the visible ones. With something like virtualized lists, I think we can reduce that number even further but I'm not sure if the tradeoff is worth the added complexity. Search tree initialization/search is another area that can be improved. It's on my radar, just need to find some weekend for it. :)
