### ISSUE TITLE
when i use .setState(..) dropdown is not showing any item

### ISSUE THREAD

**Issue by mikdatdogru** [dowjones/react-dropdown-tree-select#79]
I want to set the selectedNodes data from the onChange to the state.

but when i use .setState(..) transferred to state but dropdown is not showing any item.  
doesn't selected any items and doesn't show any selected items.

![image](https://user-images.githubusercontent.com/10121255/38381616-03f7fa22-3910-11e8-87ea-0e46cb16dcf2.png)

**Comment by mrchief** [comment]
> I want to set the selectedNodes data from the onChange to the state.

The component maintains its own selection state. You don't need to do that.

**Comment by mikdatdogru** [comment]
@mrchief  but i need to selectedNodes data.

so how else can get the data of the items I have checked ?

**Comment by josvegit** [comment]
I also call setState,  idk thought that was the react way :). They way I solved it:

Create initial tree, with paths to each node. When toggled, find the node that was toggled and set it as toggled/not-toggled (if it becomes closed => close its children etc). When checking/unchecking traverse tree and update etc. I also keep track of the path to each node so that I know If I can ignore part of the tree. This is maybe overkill, but feels like you have better controll with the setState solution.

Below is some example code:  `setSelectedHardware = (checkedNode, selectedNodes) => {
    const { initialTree, renderedTree } = this.state;
    let treeNodes = null;
    if (renderedTree != null) {
      treeNodes = renderedTree.map(item =>
        this.handleRecursiveChecked(item, checkedNode)
      );
    } else {
      treeNodes = initialTree.map(item =>
        this.handleRecursiveChecked(item, checkedNode)
      );
    }
    this.setState(prevState => ({
      ...prevState,
      renderedTree: treeNodes,
      selected: selectedNodes
    }));
  };

  toggleHardwareLeaft = currentNode => {
    const { initialTree, renderedTree } = this.state;
    let treeNodes = null;
    if (renderedTree != null) {
      treeNodes = renderedTree.map(item =>
        this.handleRecursiveToggle(item, currentNode)
      );
    } else {
      treeNodes = initialTree.map(item =>
        this.handleRecursiveToggle(item, currentNode)
      );
    }
    this.setState(prevState => ({
      ...prevState,
      renderedTree: treeNodes
    }));
  };

  setInitialTree = tree => {
    const initial = tree.children.map(child => this.createTree(child));
    this.setState(prevState => ({
      ...prevState,
      initialTree: initial
    }));
  };

  handleRecursiveToggle = (currentItem, touchedItem, pathIndex = 0) => {
    if (
      currentItem.leafId === touchedItem.leafId &&
      currentItem.parentLeaftId === touchedItem.parentLeaftId
    ) {
      if (touchedItem.expanded) {
        return {
          ...touchedItem,
          children: currentItem.children
        };
      } else {
        return {
          ...touchedItem,
          children: currentItem.children.map(child => {
            return this.recursiveMap(child, 'expanded', false);
          })
        };
      }
    } else {
      if (touchedItem.path[pathIndex] !== currentItem.leafId) {
        return currentItem;
      } else {
        return {
          ...currentItem,
          children: currentItem.children.map(child =>
            this.handleRecursiveToggle(child, touchedItem, pathIndex + 1)
          )
        };
      }
    }
  };

  handleRecursiveChecked = (currentItem, touchedItem, pathIndex = 0) => {
    if (
      currentItem.leafId === touchedItem.leafId &&
      currentItem.parentLeaftId === touchedItem.parentLeaftId
    ) {
      if (touchedItem.checked) {
        return {
          ...touchedItem,
          children: currentItem.children.map(child => {
            return this.recursiveMap(child, 'checked', true);
          })
        };
      } else {
        return {
          ...touchedItem,
          children: currentItem.children.map(child => {
            return this.recursiveMap(child, 'checked', false);
          })
        };
      }
    } else {
      if (touchedItem.path[pathIndex] !== currentItem.leafId) {
        return currentItem;
      } else {
        if (!touchedItem.checked) {
          return {
            ...currentItem,
            checked: false,
            children: currentItem.children.map(child =>
              this.handleRecursiveChecked(child, touchedItem, pathIndex + 1)
            )
          };
        } else {
          return {
            ...currentItem,
            children: currentItem.children.map(child =>
              this.handleRecursiveChecked(child, touchedItem, pathIndex + 1)
            )
          };
        }
      }
    }
  };

  recursiveMap = (current, key, val) => {
    return {
      ...current,
      [key]: val,
      children: current.children.map(child => this.recursiveMap(child, key))
    };
  };

  createTree = (
    item,
    pathToLeaf = [],
    parentLeaftId = null,
    parentfilterString = null
  ) => {
    const leafId = item.type + ':' + item.value;
    const checked = false;
    const expanded = false;
    const value = item.value;
    const type = item.type;
    const path = pathToLeaf.concat(leafId);
    const filterString =
      (parentfilterString != null ? parentfilterString + '||' : '') +
      item.type +
      ':' +
      item.value;
    return {
      ...item,
      path,
      parentLeaftId,
      leafId,
      checked,
      expanded,
      value,
      type,
      filterString,
      children: item.children.map(child =>
        this.createTree(child, path, leafId, filterString)
      )
    };
  };`

Some of this specific to my domain, like filterString and stuff. The component is used to select affected switches for an ISP blackout (idk what its called in english) . Maybe all of this is overkill. Maybe the better solution is to just set a variable with the selectedNodes and don't call setState..

**Comment by mikdatdogru** [comment]
ahhh. i understand now. of course you right.

thanks for example. I think I should improve myself on HOC
thanks again.

**Comment by mrchief** [comment]
> Maybe the better solution is to just set a variable with the selectedNodes and don't call setState..

Yes, its perfectly valid to hold data in a variable if it doesn't affect the UI. 

> Create initial tree, with paths to each node.

`onChange` will return this data - both `currentNode` and all nodes in `selectedNodes` will also bubble up any extra props you pass with the nodes. So you can use the paths to keep track of what's selected and what's not. It does that with a reason - to accommodate domain specific stuff without having to go crazy.  

I use it the same way (i.e. create paths and then just use that to manipulate/send data to backend). 

Re-initializing something like a tree is not cheap, and so should be avoided. You also loose any previous search memoizations when you re-initialize the tree.

@josvegit Maybe avoiding re-render will help with your 15k nodes as well.

**Comment by josvegit** [comment]
Yeah felt a bit like I was doing something that was already solved. Ill see if It makes a big difference, and maybe I can get you some scrambled version of the data I use to populate the component.

**Comment by josvegit** [comment]
Wow made the component feel much more responsive ! Search is still slow, ill get you the data somehow :)

**Comment by mrchief** [comment]
FWIW, you can maybe use one of these tools to generate data that's similar (in terms of complexity)

https://www.json-generator.com/
https://mockaroo.com/
http://www.freedatagenerator.com/json-data-generator

**Comment by mrchief** [comment]
Just created #80 to track search improvements. Can this be closed now?
