### ISSUE TITLE
Is it possible to use a custom node and to hide the tag list?

### ISSUE THREAD

**Issue by random-one** [dowjones/react-dropdown-tree-select#85]
I was wondering is it possible to use custom node component. I would like to replace the checkbox with another widget and I mean widget, not just styling the input. As far as I saw in the source code- the node is not a prop. Maybe if I use a HOC?

And my second question is regarding the tags list - is it possible to disable it?

**Comment by mrchief** [comment]
> is it possible to use custom node component

Not at the moment. I don't think you can do this one via an HOC. 

As far as the component is concerned, it's possible but will also introduce a certain amount of complexity. I wanted to wait and see if there is any demand for a feature like this (to justify the added complexity). 

> tags list - is it possible to disable it

Do you mean show it but in a disabled state or not emit it at all? 

Either one is not something that the component does at the moment, although you can hide it completely using CSS.

**Comment by random-one** [comment]
> Do you mean show it but in a disabled state or not emit it at all?
> 
> Either one is not something that the component does at the moment, although you can hide it completely using CSS.

I meant - not show the tag list at all.

> As far as the component is concerned, it's possible but will also introduce a certain amount of complexity. I wanted to wait and see if there is any demand for a feature like this (to justify the added complexity).
For my use case I would really like to use a custom one with more like an action button instead of checkbox.

One more question, although I already can guess the answer. 
The `searchModeOn` state variable is there a way to keep it always ON, so that the dropdown is always expanded?

**Comment by abhinav1602** [comment]
Is it possible to hide the search bar and just display the tree?
