### ISSUE TITLE
Would it be interesting to have an onChangeAfter?

### ISSUE THREAD

**Issue by toofff** [dowjones/react-dropdown-tree-select#87]
When we use the onChange method, we have to rewrite the desired behaviors, which I find problematic.

Could we consider having an `onChangeAfter` entry, to retrieve the event on the current element and the data modified by the component?

Here is my problem, when I want to update my store I go through the onChange method to retrieve the selected items.

So if I select or deselect a node, I get the selected item, but the different desired behavior are not done anymore:
- selection of children
- parents' deselection
- ...

Maybe have a simpler solution and already implemented?

**Comment by mrchief** [comment]
> but the different desired behavior are not done anymore:

selection of children
parents' deselection
...

This should be (and already is) handled by the component. You (the caller) should not have to worry about setting child or parent state. 

Are you saying its not happening? Can you provide a Codesandbox that reproduces this?

**Comment by toofff** [comment]
Good evening @mrchief,

I tried to reproduce a little bit of my application.

https://codesandbox.io/embed/5w37lmz4ok

Without the onChange method, everything is working.
With the onChange method :(

**Comment by mrchief** [comment]
@toofff Can this be closed?

**Comment by toofff** [comment]
I'll be back to you next week to better explain the problem we had with @Gregcop1.

But if I understand correctly the problem is between the HOC system with recomposed and the method shouldComponentUpdate used in your plugin.

**Comment by Gregcop1** [comment]
@mrchief IMHO, we can close this. It's a problem with recompose
